### ISSUE TITLE
Add Container.remove_paths API to delete multiple paths

### ISSUE THREAD

**Issue by PietroPasotti** [canonical/operator#1042]
I would like to be able to delete in one go multiple files from a folder via Pebble:
this to help make the transaction atomic and prevent a workload who's watching that folder to do inconsistent things before the second file is deleted too.

`container.remove_paths("/path/to/some/dir/foo.yaml", "/path/to/some/dir/bar.yaml")`

However, this means that I'd have to list_dir before I know what filenames are in that directory, so that's two API calls instead of one.
If I know I want to delete all files of a certain kind, I could use a globbed path:

`container.remove_path("/path/to/some/dir/*.yaml")`

Right now, I have to

`container.exec(["find", "/path/to/some/dir/", "-name", "*.yaml", "-delete"])`

which is not very pretty.

**Comment by benhoyt** [comment]
A few things to note here:

* Even if we implemented this server-side, it wouldn't be atomic. Doing it server-side would reduce the "race window", but I don't know of a way to *atomically* delete multiple named files at once. So we'd be solving a performance and API problem here, not an atomicity one.
* The underlying Pebble delete-files API actually [supports deleting multiple named files](https://github.com/canonical/pebble/blob/d3a4c78e1257da0e6efcca9aec1360e4883e0544/internals/daemon/api_files.go#L368) at once (each with their own "recursive" parameter), so we could add a `remove_paths(*paths: str)` or `remove_paths(paths: list[str])` API.
  - There's a precedent for the `*paths` form -- see `start` and `get_services` for example -- but I could be convinced to do `paths: list[str]`.
  - Or it could be `remove_paths(*paths: str | PathToRemove)` with a `PathToRemove(path: str, recursive: bool=False)` dataclass, though I'm not sure being able to specify *recursive* for each path adds enough value to pay for its complexity.
  - Alternatively, could overload `remove_path` to allow path to be a list, but I think that's a bad idea, 1) because the name `remove_path` is singular, and 2) because str is iterable so allowing `str | list[str]` is error-prone. So I think a separate `remove_paths` plural is the way to go.
* With the above API, you'd still need to do two API calls: `entries = container.list_files('path', pattern='*.yaml')` and then `container.remove_paths(*[e.path for e in entries])`. But 2's a lot better than N+1 API calls.
* I actually think your exec+find example is quite elegant and clear! Nothing wrong with that approach if you have thousands of files.

Overall, I think adding `remove_paths(*paths: str)` to make use of the Pebble multi-delete feature is reasonable. Thoughts @tonyandrewmeyer (and @PietroPasotti)?

**Comment by sed-i** [comment]
Some thoughts:
- Is it possible to use a `**` glob in `container.list_files('path', pattern='**/*.yaml')` like we can in `pathlib.Path.glob`?
- To mimic atomicity, pebble could do something similar to [git-sync](https://github.com/kubernetes/git-sync/blob/162e543e05200bbbddf764a59102620d54b992c1/main.go#L2017) with symlinks. To make use of it, we would probably need new API for "manifest" wholesale updates, e.g. `container.replace_path(mainfest: Dict[Path, Union[str, bytes]])`.

**Comment by tonyandrewmeyer** [comment]
> There's a precedent for the *paths form -- see start and get_services for example -- but I could be convinced to do paths: list[str].

I don't feel like the Python world has really settled on either of these variants. I prefer the `*paths` form personally (but could also be convinced otherwise), and having existing examples in `ops` is a strong argument in favour.

> Or it could be remove_paths(*paths: str | PathToRemove) with a PathToRemove(path: str, recursive: bool=False) dataclass, though I'm not sure being able to specify recursive for each path adds enough value to pay for its complexity.

I really don't love this. I assume there must have been some reason that the API supports this, so maybe I'm missing important use-cases. However, unless there's real demand for it, I wouldn't include this. It's also a pretty straightforward change to add at a later time without backwards compatibility issues.

> because str is iterable so allowing str | list[str] is error-prone.

Agreed. You'd really want it to be `Iterable[str]` and so type checking would not help, since `str` is a perfectly fine `Iterable[str]`. Hard-typing to `list[str]` or `list[str]|tuple[str]` seems very un-Pythonic.

> With the above API, you'd still need to do two API calls: entries = container.list_files('path', pattern='*.yaml') and then container.remove_paths(*[e.path for e in entries]). But 2's a lot better than N+1 API calls.

I assume this means that you'd implement this using the support for removing multiple paths at once? What was the reason for not doing that with `pull_path`?

> I actually think your exec+find example is quite elegant and clear!

+1

> Overall, I think adding remove_paths(*paths: str) to make use of the Pebble multi-delete feature is reasonable.

+1

> * Is it possible to use a `**` glob in `container.list_files('path', pattern='**/*.yaml')` like we can in `pathlib.Path.glob`?

I don't believe so. If I understand correctly, it's [Go's pathpkg Match](https://pkg.go.dev/path#Match) under the hood, and I don't see any support for `**` there.

> * To mimic atomicity, pebble could do something similar to [git-sync](https://github.com/kubernetes/git-sync/blob/162e543e05200bbbddf764a59102620d54b992c1/main.go#L2017) with symlinks. To make use of it, we would probably need new API for "manifest" wholesale updates, e.g. `container.replace_path(mainfest: Dict[Path, Union[str, bytes]])`.

Indeed, it seems like this would be a separate request that would need an API for files that get managed in this special way.

**Comment by benhoyt** [comment]
Yeah, I don't think we'll be adding much to the Pebble file APIs at this point, so no `**` or `replace_path` for now.

> I assume this means that you'd implement this using the support for removing multiple paths at once?

Yes, that was my thinking. It's fairly straight-forward in the case of remove_path.

> What was the reason for not doing that with pull_path?

Just to keep things simple in the first implementation. I think we could do it with `pull_path` and `push_path`, but the implementation would be somewhat more complex. That said, I'd be happy to consider that if there's a demonstration of an efficiency need in a real charm.

I agree with @tonyandrewmeyer's thoughts above. Some I'm going to update this issue's title to reflect what we plan: adding `def remove_paths(self, *paths: str) -> None`. Could potentially have a `recursive: bool = False` parameter that applies to all of them.

**Comment by benhoyt** [comment]
We looked at the corpus of our charms, and it's generally quite small lists (like 3 certificates) that are being `remove_path`ed. We would consider adding this if there's a demonstration of an efficiency need in a real charm, but for now, we think the additional API surface probably isn't worth it.

In addition, there's a straight-forward workaround if a charm does need ultimate efficiency with the exec-find trick.
