### ISSUE TITLE
[ops2.9][testing] Can't modify Juju secret

### ISSUE THREAD

**Issue by juditnovak** [canonical/operator#1088]
As you can verify across the two pipeline runs quoted below: starting to use `ops-2.9.0` those tests that are updating secret contents are failing. 

Secret contents can be set for once, but updates take no effect. The contents remain in their original state, added content doesn't make it into the secret.

We can't use `ops-2.9.0` as long as we can't test secrets modifications with it :-(

Failing, every single time on secret update since `ops-2.9.0`: 
 - https://github.com/canonical/data-platform-libs/actions/runs/7040693783/job/19162055425#step:4:9
 - https://github.com/canonical/data-platform-libs/actions/runs/7054418202/job/19203247068#step:4:9
 - https://github.com/canonical/data-platform-libs/actions/runs/7067069178/job/19239945602#step:4:9

All good on `ops-2.8.0`:
 - https://github.com/canonical/data-platform-libs/actions/runs/7026715678/job/19119922152#step:4:9
 - https://github.com/canonical/data-platform-libs/actions/runs/7012869360/job/19078123869#step:4:9
 - https://github.com/canonical/data-platform-libs/actions/runs/6999372293/job/19038577150#step:4:9

**Comment by tonyandrewmeyer** [comment]
This is a documented change in ops 2.9.0, to match the upcoming change in Juju. From the next releases of Juju, and in 2.9.0 of ops (Harness), the special case where the secret owner would automatically peek at the latest version of the secret (and therefore could not use refresh) is being removed, and everyone gets the same behaviour: `get_content()` returns the tracked revision, `peek_content()` gets the latest revision, and anyone can do `get_content(refresh=True)`.

This means that if you set new secret content and want to verify that the content has changed, you need to use `peek_content()` (or `get_content(refresh=True)`) not `get_content()`, because you'll continue to get the revision you are tracking.

This diff fixes the failing tests (once #120 is also merged):

```diff
diff --git a/tests/unit/test_data_interfaces.py b/tests/unit/test_data_interfaces.py
index 5fbdea0..3be5d25 100644
--- a/tests/unit/test_data_interfaces.py
+++ b/tests/unit/test_data_interfaces.py
@@ -332,7 +332,7 @@ class TestDatabaseProvides(DataProvidesBaseTests, unittest.TestCase):
         }
 
         secret = self.harness.charm.model.get_secret(id=secret_id)
-        assert secret.get_content() == {
+        assert secret.peek_content() == {
             "tls": "True",
             "tls-ca": "Canonical",
         }
@@ -661,7 +661,7 @@ class TestKafkaProvides(DataProvidesBaseTests, unittest.TestCase):
         }
 
         secret = self.harness.charm.model.get_secret(id=secret_id)
-        assert secret.get_content() == {
+        assert secret.peek_content() == {
             "tls": "True",
             "tls-ca": "Canonical",
         }
```

Note that you can use `peek_content()` with ops older than 2.9.0, but if you use `get_content(refresh=True)` then that will work in 2.9 and fail in older versions, because (unfortunately) this is a breaking change in Juju, and we decided that ops should always work in the "fixed" way, rather than model the older broken behaviour via a `JujuVersion` control.

You might also need to review the lib code itself to make sure that it's compatible with the forthcoming Juju change - I haven't done that.

**Comment by juditnovak** [comment]
Thank you very much for the detailed response.

I have one important question. Is this only a change in the behavior of the `Harness`, or `ops` overall. I mean, impacting the charm?

**Comment by tonyandrewmeyer** [comment]
In production, `ops` really just reflects the Juju behaviour. So if the Charm is running with Juju 3.1.6 then you'll get the "secret owner always peeks" behaviour, and if the Charm is running with Juju 3.17 then you'll get the "everyone gets the tracked revision unless peeking" behaviour.

I believe there isn't going to be a Juju 3.2 release that changes this, but there will be a 3.3, so 3.3.0 has the old behaviour and 3.3.1 will have the new behaviour. Juju 3.4.0 will have the new behaviour.

**Comment by juditnovak** [comment]
So, you confirm that regarding the `ops` library, only the `Harness` behavior has changed.

Retrieving and updating secrets within the charm will continue using the "implicit" peek behavior -- as long as executed over Juju <= 3.1.6

**Comment by tonyandrewmeyer** [comment]
Yes. And Charms running on 3.1.7+ will not have implicit peeking even if using ops 2.8-.

It is an unfortunately messy situation 😞.
