### ISSUE TITLE
Do not raise an exception when secrets are not found by label

### ISSUE THREAD

**Issue by arturo-seijas** [canonical/operator#1095]
Hi!

IMO, a scenario like the one below is normal flow and shouldn't be handled via exceptions:

```python
try:
    password_id = self.model.get_secret(label="smtp-password").id
except ops.SecretNotFoundError:
    pass
```
If not found, the `get_secret`method should return a `None` value instead.

**Comment by tonyandrewmeyer** [comment]
Hi @arturo-seijas! In Python, exceptions are (despite the name) part of normal control flow. Can you outline why you believe that:

```python
password_secret = self.model.get_secret(label="smtp-password")
if password_secret is None:
    # handle
else:
    password_id = password_secret
```

is an improvement over the example you have in the issue description?

Note that raising an exception matches the behaviour of other `ops` methods - `get_check()`, `get_notice()`, `get_service()`, `get_container()`. `get_relation()` does return `None`, though.

**Comment by arturo-seijas** [comment]
For startes, that seems less verbose than
```
password_secret = None
try:
    password_secret = self.model.get_secret(label="smtp-password")
except ops.SecretNotFoundError:
    pass
if password_secret is None:
    # handle
else:
    password_id = password_secret.id
```

**Comment by tonyandrewmeyer** [comment]
> That seems less verbose than
> 
> ```
> password_secret = None
> try:
>     password_secret = self.model.get_secret(label="smtp-password")
> except ops.SecretNotFoundError:
>     pass
> if password_secret is None:
>     # handle
> else:
>     password_id = password_secret.id
> ```

But you've included code that doesn't need to be there :smile:. `get_secret` returns a `Secret`, not `Secret|None`. So the current code is what you have in the description, ie.:

```python
try:
    password_id = self.model.get_secret(label="smtp-password").id
except ops.SecretNotFoundError:
    # handle
```

So it's actually very slightly less verbose - one fewer line, plus no need to have a second name to hold the secret (assuming you are only actually interested in the ID).

> On the other hand, the convention is to use exceptions for abnormal execution flow.

This is not really true in Python (it certainly is in other languages). Some common examples:

* `ImportError` - it's very common to have a try/except block that chooses between packages based on whether an `import` raises `ImportError` (or `ModuleNotFoundError`) (e.g. the stdlib does this to use an optimised library if available and pure Python if not).
* `StopIteration` - you don't typically catch these, but they're part of the core `next()`/`__next__()` functionality.
* The "easier to ask forgiveness" pattern that's commonly used to avoid races in Python is generally done with exceptions (e.g. rather than checking if a file exists and then opening it, attempting to open it and catching the exception if that fails because it doesn't exist).

> So I'd say that, if the resource is always expected to exist an exception should be returned, otherwise, we should return an empty object or None.

Exceptions are generally used for the less common case (I wouldn't call that "abnormal"). However, that would generally be the expectation with secrets as well - most of the time you'd expect that the secret does exist, and you're just wanting to handle the situation where they haven't been configured yet.

Sometimes both forms are available - the obvious example being a dictionary, where you can do `d[k]` and get a `KeyError` or `d.get(k, default=None)` and get `default`. If you use the default as a "doesn't exist" flag rather than a default value, then you often end up with race conditions, though (admittedly, probably not in this case because within the hook Juju keeps the observed state of the model static). It's easy to imagine a version of this for secrets, like `model.secrets[id]` and `model.secrets.get(id, default)` - but what would a meaningful value be for the default in this case? and how do you handle the option of getting by label?

Even if @canonical/charm-tech was convinced this was a change that should be made, we need to maintain backwards compatibility, so this could only happen in an `ops 3.0`, or by adding a new `get_secret_no_raise` method (which is a heavy change), or by changing the signature in a backwards compatible way like `get_secret(*, id=None, label=None, default=None)`. The latter would have the most chance, but (as noted above) I don't see what meaningful value could be provided as a default.

> From my point of view, this is analogous to the relation. The charm having the relation is optional, and both possibilities fall within the normal execution flow, not an invalid charm state or invalid operation.

I definitely agree that it's unfortunate that `get_relation` doesn't behave in the same way as all the other `get_*` methods. However, I think the more appropriate improvement would be for `get_relation` to raise if the relation isn't established (but this would be a backwards compatibility issue in the same way).

**Comment by benhoyt** [comment]
Thanks for "raising" this (heh, couldn't help myself). However, as Tony points out, this would be a backwards-incompatible change, and with `get_secret` raising I think we chose the way that's both more Pythonic and more consistent with existing `get_foo` methods in Ops. Sorry!
