### ISSUE TITLE
facilitate common exit hook pattern?

### ISSUE THREAD

**Issue by PietroPasotti** [canonical/operator#1108]
Before the `collect_status` events were introduced, I could write:

```
class MyCharm(CharmBase):
    def __init__(self, framework):
        super().__init__(framework)
        
        for event in self.on.events().values():
            self.framework.observe(event, self._on_event)
```

and rest assured that `_on_event` would be called exactly once, no matter what event the charm was processing.

However, nowadays, `_on_event` will be called three times!

I wouldn't consider this a bug/regression because that pattern was not widely accepted/publicised, but it is still public API and many of my simpler tester charms that have a very simple holistic control logic implement it because it's quick and dirty.

No production charm I'm aware of is affected by this. Only testing code.

As a workaround, I can filter out the `collect_status` events and omit listening to those in my `observe` calls, but that is suddenly a lot of code for a semantically simple ask: whatever event I see, run this handler.

In some or many situations it would be acceptable to simply put the code in `__init__` instead of observing anything at all, since I want the code to execute unconditionally (and only once). But I can also imagine needing access to the event object.

Is it maybe a good idea to add a `self.framework.observe_any(self._handler)` or something similar to facilitate this use case? Or is it a use case we don't want to facilitate?

**Comment by tonyandrewmeyer** [comment]
> Before the `collect_status` events were introduced, I could write:
> 
> ```
> class MyCharm(CharmBase):
>     def __init__(self, framework):
>         super().__init__(framework)
>         
>         for event in self.on.events().values():
>             self.framework.observe(event, self._on_event)
> ```
> 
> and rest assured that `_on_event` would be called exactly once, no matter what event the charm was processing.

As you note, the simple case is something like:

```python
class MyCharm(CharmBase):
    def __init__(self, framework):
        super().__init__(framework)
        self._on_event()
```

But there's no clean way to get an event object there, because the charm isn't yet handling an event. You said you can imagine wanting that object - does that mean you don't currently use it, even in the tester charms?

> As a workaround, I can filter out the `collect_status` events and omit listening to those in my `observe` calls, but that is suddenly a lot of code for a semantically simple ask: whatever event I see, run this handler.

I guess the main question I have is what use cases there are (especially outside tester charms) for "I want to run this bit of code for every hook event? That's a pretty wide range of things happening (e.g. stop and relation-changed don't seem like they would generally have common code, but maybe that's my inexperience?).

My other concern is that you're saying "call once per event" but ops considers collect-status to be an event, so you are actually currently getting "once per event". I think what you want is "once per hook event" (maybe instead of `observe_any()` there could be a `on.hook_events()`).

I'm not totally convinced that this is "a lot of code", either :smile::

```python
class MyCharm(CharmBase):
    def __init__(self, framework):
        super().__init__(framework)
        
        for event in (kind for kind in self.on.events().values() if isinstance(knd, ops.HookEvent)):
            self.framework.observe(event, self._on_event)
```

It doesn't seem unreasonable - I guess I would just like to understand more about how useful this would actually be, compared to either (a) not needing the event object so just calling a method or running the code in `__init__`, or (b) having a simple filter in your `for` loop.

(Side note: this seems a tangentally linked to #736, ie. the whole question of whether `__init__` is called per event or not).

**Comment by benhoyt** [comment]
I agree with @tonyandrewmeyer's assessment here, basically that this kind of code is fairly "fringe", and there are two reasonable workarounds (run in `__init__` or filter on the event kind) for code that really does need it.
