### ISSUE TITLE
expose JUJU_ACTION_UUID envvar

### ISSUE THREAD

**Issue by PietroPasotti** [canonical/operator#1121]
Some old hooks-based charms use the JUJU_ACTION_UUID envvar.
When porting them to use ops, it would be nice if there was an opsy way to access its value.
How about adding an `ActionEvent.uuid -> int` property to fetch it?

**Comment by tonyandrewmeyer** [comment]
For reference, of the ~150 charms I have locally, only `certbot-charm` really uses this (for getting a unique temporary location to store a file). Looking at [GitHub](https://github.com/search?q=JUJU_ACTION_UUID+language%3APython&type=code&p=1&l=Python) there's indeed a lot that are using charm-helpers, plus a [bunch](https://github.com/search?q=JUJU_ACTION_UUID+language%3AShell&type=code&l=Shell) of shell hook ones.

It looks like it's most commonly used for logging or for (like `certbot`) unique files/directories. Those seem reasonable to me.

I guess we could be complete here and add both `.uuid` and `.tag`. I think the ID should perhaps be named `.id` (or `.task_id`?) since in modern Juju it's not really a UUID in the form people would expect.

Any objections to adding this @benhoyt?

**Comment by benhoyt** [comment]
@tonyandrewmeyer Thanks for the analysis. Do any of the charms use the tag? I'm inclined to leave `.tag` out for now (the tag is also just `action-{id}`). We can always add it later.

I agree with your assessment that it should be called `.id` as it's not a UUID any more. (I don't think it's a task ID either -- actions have a task, or multiple tasks.)

**Comment by tonyandrewmeyer** [comment]
> @tonyandrewmeyer Thanks for the analysis. Do any of the charms use the tag? I'm inclined to leave `.tag` out for now (the tag is also just `action-{id}`). We can always add it later.

+1. I didn't read through all the hook ones, but couldn't find any use when skimming,

> I agree with your assessment that it should be called `.id` as it's not a UUID any more. (I don't think it's a task ID either -- actions have a task, or multiple tasks.)

👍
