### ISSUE TITLE
Relation units are available only if the relation is set before harness.begin_with_initial_hooks()

### ISSUE THREAD

**Issue by amandahla** [canonical/operator#1161]
Hey,

I'm not sure if this is an expected behavior but while getting units from a peer relation and creating a unit test for it, I noticed that for this code:
```
peer_relation = self.model.relations[synapse.SYNAPSE_PEER_RELATION_NAME]
if peer_relation:
      relation = peer_relation[0]
      print(f"{relation.name} has {relation.units} units")
```

- This works
```
rel_id = harness.add_relation(synapse.SYNAPSE_PEER_RELATION_NAME, "synapse")
harness.add_relation_unit(rel_id, "synapse/1")
harness.begin_with_initial_hooks()
```
Output:
```
synapse-peers has {<ops.model.Unit synapse/1>} units
```

- This doesn't work
```
harness.begin_with_initial_hooks()
rel_id = harness.add_relation(synapse.SYNAPSE_PEER_RELATION_NAME, "synapse")
harness.add_relation_unit(rel_id, "synapse/1")
```    
Output:
```
synapse-peers has set() units
```

If this is correct, could be documented please?

**Comment by IronCore864** [comment]
Hi @amandahla,

I think you are right; I'm using `ops==2.11.0` and I can reproduce with the simple tests below:

```python3
import pytest

import ops.testing


@pytest.fixture
def harness():
    harness = ops.testing.Harness(ops.CharmBase, meta='''
        name: sample-k8s
        peers:
          foo:
            interface: bar
        ''')
    yield harness
    harness.cleanup()

def test_add_relation_first(harness):
    rel_id = harness.add_relation('foo', 'sample-k8s')
    harness.add_relation_unit(rel_id, "sample-k8s/1")

    harness.begin_with_initial_hooks()

    peer_relation = harness.model.relations["foo"]
    if peer_relation:
        relation = peer_relation[0]
        assert len(relation.units) == 1
        print(relation.units)
        

def test_harness_begin_first(harness):
    harness.begin_with_initial_hooks()
    
    rel_id = harness.add_relation('foo', 'sample-k8s')
    harness.add_relation_unit(rel_id, "sample-k8s/1")

    peer_relation = harness.model.relations["foo"]
    if peer_relation:
        relation = peer_relation[0]
        assert len(relation.units) == 0
        print(relation.units)
```

Output:

```bash
$ python -m tox -e unit
unit: commands[0]> coverage run --source=/Users/tiexin/work/sample-k8s/src -m pytest --tb native -v -s /Users/tiexin/work/sample-k8s/tests/unit
=================================================================== test session starts ====================================================================
platform darwin -- Python 3.8.18, pytest-8.1.1, pluggy-1.4.0 -- /Users/tiexin/work/sample-k8s/.tox/unit/bin/python
cachedir: .tox/unit/.pytest_cache
rootdir: /Users/tiexin/work/sample-k8s
configfile: pyproject.toml
collected 2 items

tests/unit/test_charm.py::test_add_relation_first {<ops.model.Unit sample-k8s/1>}
PASSED
tests/unit/test_charm.py::test_harness_begin_first set()
PASSED

==================================================================== 2 passed in 0.06s =====================================================================
unit: commands[1]> coverage report
Name           Stmts   Miss Branch BrPart  Cover   Missing
----------------------------------------------------------
src/charm.py      19      7      0      0    63%   32-33, 36-39, 44
----------------------------------------------------------
TOTAL             19      7      0      0    63%
  unit: OK (0.32=setup[0.02]+cmd[0.23,0.06] seconds)
  congratulations :) (0.36 seconds)
```

---

I have done some research into the `Harness` code and I think it is by design, see [here](https://github.com/canonical/operator/blob/main/ops/testing.py#L426): "If the user has directly added a relation, leave it be, but otherwise ensure that peer relations are always established at before leader-elected."

This means, that if you call `harness.begin_with_initial_hooks()` first, it creates a relation for you. Then you call `harness.add_relation` and this creates a second relation, and when you call `harness.add_relation_unit`, it adds to the second relation, not the first, so when you print `peer_relation[0]`, it's empty because it's the relation Harness created when `begin_with_initial_hooks` is called.

I can confirm the above logic by the following two tests:

```python3
def test_harness_begin_first_v2(harness):
    harness.begin_with_initial_hooks()
    
    rel_id = harness.add_relation('foo', 'sample-k8s')
    harness.add_relation_unit(rel_id, "sample-k8s/1")

    peer_relation = harness.model.relations["foo"]
    if peer_relation:
        relation = peer_relation[1]
        assert len(relation.units) == 1
        print(relation.units)

def test_harness_begin_first_v3(harness):
    harness.begin_with_initial_hooks()
    
    rel_id = 0
    harness.add_relation_unit(rel_id, "sample-k8s/1")

    peer_relation = harness.model.relations["foo"]
    if peer_relation:
        relation = peer_relation[0]
        assert len(relation.units) == 1
        print(relation.units)
```

The `v2` asserts on the 1st (0-indexed) relation, and the `v3` doesn't add a relation but uses the relation harness created in `begin_with_initial_hooks` with id 0.

---

The documentation doesn't say anything about this behaviour in [`Harness.add_relation`](https://github.com/canonical/operator/blob/main/ops/testing.py#L804), but it does mention it [here in the Harness docstring](https://github.com/canonical/operator/blob/main/ops/testing.py#L380).

However, I do agree that this isn't clear enough. I suggest that we add a short paragraph in the `add_relation` docstring as well, stating something like:

`Harness.begin_with_initial_hooks` will automatically create peer relations defined in `metadata.yaml`; for peer relations, you don't have to `add_relation` before `begin_with_initial_hooks`. If you choose to add peer relations by yourself, make sure to call `add_relation` first before `begin_with_initial_hooks` so that Harness doesn't create it again.

Do you think this is necessary? @benhoyt @tonyandrewmeyer

**Comment by benhoyt** [comment]
That's an excellent diagnosis, thanks @IronCore864. I think the existing paragraph is almost enough, but it wouldn't hurt to add what you've suggested, Tiexin -- if you could please put up a PR with that addition, that would be great. Though note that we've been avoiding "you" in the docstrings and using more passive tense instead: "if you" -> "if the caller", that type of thing.
