### ISSUE TITLE
Framework source not imported when deploying on microk8s

### ISSUE THREAD

**Issue by relaxdiego** [canonical/operator#120]
(Not sure if this is the right place to post this as I don't know if we have a chat room for this project. Apologies in advance if this is spam)

I'm getting my hands dirty with this framework (quite happily, fyi). Right now, I'm seeing that the framework (as git submodule) isn't being downloaded into the operator pod:

```
$ kubectl exec -it -n demo-charm demo-charm-operator-0 /bin/sh
# cd /var/lib/juju/agents/application-demo-charm/charm
# ls
README.md  config.yaml  hooks  lib  metadata.yaml  mod  revision  src  version
# ls -l mod/operator/ops
ls: cannot access 'mod/operator/ops': No such file or directory
# ls -l mod
total 4
drwxr-xr-x 2 root root 4096 Jan 29 04:58 operator
# ls -l mod/operator
total 0
# pwd
/var/lib/juju/agents/application-demo-charm/charm
```

Effect is that the `ops` package cannot imported at runtime:

```
# python3.6
Python 3.6.9 (default, Nov  7 2019, 10:44:02)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
'/var/lib/juju/agents/application-demo-charm/charm'
>>> import sys
>>> sys.path.append(f"{os.getcwd()}/lib")
>>> import ops
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'ops'
```

What did I miss here? My demo project is at https://github.com/relaxdiego/demo-charm/tree/4495e821da3b1191148609698f3fdbca72d8398a

**Comment by jameinel** [comment]
Running your project, I get:
demo-charm/0*  maintenance  idle                   Configuring container

Which looks like all that you have in your charm.py

I think the issue is that when you 'git clone' a project with submodules
you either have to:
 'git clone --recurse-submodules'

or after you have done
`git clone`; you have to `git submodule init; git submodule update`.

If you just 'git clone' then the submodules are empty directories. And
'juju deploy' doesn't have anything to package up.
The modules are not built/installed at runtime, they need to be available
before you deploy.

John
=:->

**Comment by relaxdiego** [comment]
D’oh! Looks like I just got hit by the git submodules PEBKAC bug. ;-)

**Comment by relaxdiego** [comment]
Just to close this issue with how I fixed it, the reason the submodule was not cloned was because I did a `git push` to the remote machine where I ran the installation commands. This does not push the submodules. To fix it, I had to run `git submodule update --recursive --init  mod/operator/` in the git repo in the remote machine.

Thanks for the quick response, @jameinel!
