### ISSUE TITLE
`self.model.config` confuses pyright

### ISSUE THREAD

**Issue by lengau** [canonical/operator#1212]
It looks like #1183 had an unintended side-effect, confusing pyright for charms. The following charm:

```
import ops


class TestCharmCharm(ops.CharmBase):
    """Charm the service."""

    def __init__(self, framework: ops.Framework):
        super().__init__(framework)
        framework.observe(self.on.config_changed, self._on_config_changed)

    def _on_config_changed(self, event: ops.ConfigChangedEvent):
        """Handle changed configuration."""
        log_level = self.model.config["log-level"].lower()


if __name__ == "__main__":  # pragma: nocover
    ops.main(TestCharmCharm)  # type: ignore
```

gets no typing errors with ops 2.12 installed, but with 2.13 gets:

```
$ pyright
/home/lengau/Work/Test/2024-05-08/simple/src/charm.py
  /home/lengau/Work/Test/2024-05-08/simple/src/charm.py:60:52 - error: Cannot access attribute "lower" for class "bool"
    Attribute "lower" is unknown (reportAttributeAccessIssue)
  /home/lengau/Work/Test/2024-05-08/simple/src/charm.py:60:52 - error: Cannot access attribute "lower" for class "int"
    Attribute "lower" is unknown (reportAttributeAccessIssue)
  /home/lengau/Work/Test/2024-05-08/simple/src/charm.py:60:52 - error: Cannot access attribute "lower" for class "float"
    Attribute "lower" is unknown (reportAttributeAccessIssue)
3 errors, 0 warnings, 0 informations 
```

This is because pyright assumes that each item in a `Dict[str, Union[bool, int, float, str]]` can be any of the types.

I'm unsure of how to solve this completely, but a `Dict[str, Any]` may be a more appropriate value to prevent users having to explicitly cast config values every time.

**Comment by tonyandrewmeyer** [comment]
Hi @lengau - we did mention this in the release notes and the Discourse post and the Matrix post. We're happy to hear any suggestions about how we can better publicise changes in the future if you have ideas.

I opened PRs for the 24 charms I found that would have failing tests as a result (about 3 weeks ahead of the release, in the hope that they would mostly be merged by the time of the release). If I didn't open any for yours, could you let me know what charms they were? Either they are missing from our list of known charms (and I'd like to add them, so that they're included in the analysis we do ahead of changes) or my tooling failed to detect them (maybe the linting step isn't in a tox environment that I tried, but in any case I'd like to fix this).

As for the change, this is correct behaviour - the type was wrong before - we said that config would return `str` but that was not true, it would return `str`, `int`, `float`, or `bool` depending on the `type` in charmcraft/config.yaml.

The fix is to tell the type checker what type the value is, with an assert or a `typing.cast`.

`typing.Any` was considered (there's a thread in the PR that has some of the discussion). However, that's really just saying "ignore the type", and that goes against the point of having type annotations. It's better to have the correct type and use it appropriately so that you're not (essentially) turning type checking off for these values.

I do think we can do better with config values. The challenge is that the Python code doesn't know what the actual type is (Juju provides the int/float/bool/string in JSON, ops doesn't convert to that type, and it's obviously defined in YAML originally). I have some thoughts about how we might work around that. The Charm Tech team is planning on discussion potential improvements around config in general, but including this, next week at the Engineering sprint.

**Comment by tonyandrewmeyer** [comment]
> If I didn't open any for yours, could you let me know what charms they were?

Ah, I looked at the linked PRs - was this only for the charmcraft templates? I did indeed forget to think of those, sorry 😞. This is a bit different to the usual charm/bundle in a [mono]repo case, but I think I can add "run against a fresh charm generated with each charmcraft profile" to our testing regime.

(Please do let me know if there are other places that were missed).
