### ISSUE TITLE
Interface class repository

### ISSUE THREAD

**Issue by majduk** [canonical/operator#122]
The reactive framework, apart from a notion of layers, had also a notion of defined interfaces.

The new framework also provides the interfaces and a pattern of creating interface class. Since the interface code in essence would be reusable, is there a plan of creating some kind of repository where interface definitions would be stored? This way, when we refer to mysql relation we would have MySQLInterfaceRequires and MySQLInterfaceProvides stored in a central place and regardles of a charm providing it, we would have a consistent set of data expected and provided regardles of whoever wrote the charm internals.

**Comment by relaxdiego** [comment]
I'm curious what the pros and cons are for putting it in a separate repository vs putting it this repository. Seems like the framework and the interfaces it supports would go hand in hand in terms of releases but I'm almost certain I'm missing a thing or two.

**Comment by jameinel** [comment]
I think fundamentally it depends how 'stable' a given interface is. I would
expect the operator framework itself to eventually reach stability, and
then it would only track updates that go along with changes in the Juju
model. While interfaces update at the rate of the charms that are
interacting with those applications. Some of those will be quite stable,
but all new charms being written will likely have at least 1 new interface,
since that application is providing something new to the world.

There are certainly advantages to having things centralized. If we do find
a better pattern for handling a given type of relation, then we can update
a lot of interfaces to use it. In my head, the lifecycles of interfaces are
quite decoupled from the lifecycle of the underlying framework.

I do think we'll be collecting known interfaces and intending to share
them/publicize them with others. At the moment the intent is to just track
this as a post in https://discourse.jujucharms.com/
There is some internal Canonical discussions about having clean ways of
providing interface definitions, usage, and examples as part of charmhub
(the evolution of jujucharms as we split off what is Juju vs what are
Charms vs what is JAAS and the various people that are more interested in
the different parts of the stack.)
I believe the intent is that Charmhub becomes focused on charm developers
and documenting/indexing interfaces ends up part of that site.

**Comment by facundobatista** [comment]
There will be no specific repository for this. You will be able to install any interface, component or charm/project dependency from the usual places where you install Python stuff (PyPI, disk, github, etc.).

After bringing that Python code through the usual mechanisms, you will be able to use the needed interface(s) using the mechanism that is being implemented in #244.
