### ISSUE TITLE
ActiveStatus() doesn't accept a message

### ISSUE THREAD

**Issue by barryprice** [canonical/operator#126]
Many of our current pre-operator charms use the Message field of "juju status" to display useful information about the running unit, e.g. the Postgres charm displays whether it's running as master or slave, the Livepatch charm displays the current patch status, and so on.

This functionality seems to be deliberately disabled in the ActiveStatus class, with messages only able to be set within a BlockedStatus, a MaintenanceStatus, or a WaitingStatus.

Can this be reconsidered? Sometimes a unit is not waiting, blocked or in maintenance, but we still want to see what it's doing.

**Comment by dshcherb** [comment]
There was a discussion around https://github.com/canonical/operator/pull/52 where I originally had it allowed.

IIRC, @niemeyer's point was that it does not make sense to allow it for messages like "ready", "active", "installed" because they do not carry a lot of useful information compared to a unit/app being active without a message. Likewise, messages that expose a snapshot of an application or unit state "3 units active" are highly likely to actually be lies because Juju is not a monitoring system with live data collection.

As far as I remember, we concluded that we can add this functionality if there are good examples of messages provided by the framework users. If you have any, please include them - that would help moving this conversation forward.

My point of view is that there are not that many charms currently that expose useful messages in the active status. Moreover, when `update-status` is not properly implemented, messages like "active", "ready", "x units up" may be very misleading and you end up looking at the target units or your monitoring system anyway.

The mismatch with the functionality `ActiveStatus` provides now has already lead to an interesting problem: if you have an overly broad `except` clause, it will catch the `TypeError` thrown when you pass the unexpected message parameter to `ActiveStatus`.  For example, @cmars had something akin to this:

```
def on_install(self, event):
    # ...
    try:
        # ...
        self.mode.unit.status = ActiveStatus(msg)
        # ...
    except Exception as e:
        # will be infinitely deferred
        event.defer()
```

**Comment by sajoupa** [comment]
Hi,
I would agree that a message can be very useful in the active status.
ntp uses it, as well as telegraf, landscape-client, filebeat, easyrsa, ...

**Comment by niemeyer** [comment]
@sajoupa @barryprice I think what you're both saying is that communicating information to the administrator can be very useful, which is of course true and vital for proper operation of systems. What I found out while talking to people is that this message is being used to carry all kinds of information. Some examples were provided above:

> the Postgres charm displays whether it's running as master or slave, the Livepatch charm displays the current patch status, and so on

The purpose of this field is to say whether the unit is waiting for something, or functioning normally. Not as a conveyor of arbitrary data for the charm, as this would be far from ideal. My recommendation is to preserve the active status empty, and eventually disable it in juju altogether so that it doesn't show anything anymore (it would not break, for compatibility, but it wouldn't show anything). At the same time, let's work with the juju team to have a proper way to feed such valuable information to the administrator in a structured way.

**Comment by cmars** [comment]
There is another use case for an active status message. From the [Juju hook tool documentation on status-set](https://discourse.jujucharms.com/t/hook-tools/1163#heading--status-set) (emphasis mine):

> A unit in the active state with should not generally expect anyone to look at its status message, and often it is better not to set one at all. _In the event of a degradation of service, this is a good place to surface an explanation for the degradation (load, hardware failure or other issue)._

The documentation generally agrees with the perspective that the active status shouldn't be relied upon, but also acknowledges there may be edge cases where a description is appropriate. Zookeeper does this, for example, if you don't have enough, or the wrong number of nodes in the cluster.

It seems wrong to take away functionality that is currently provided by Juju and relied upon by many charms (canonical-livepatch, postgresql, etc), at least until a better alternative exists. I think the pragmatic solution is to allow an active message parameter but mark it deprecated.

**Comment by niemeyer** [comment]
> It seems wrong to take away functionality that is currently provided by Juju and relied upon by many charms

That's exactly the rationale applying here. The operator framework has never offered this functionality, so this is the time to discuss how we _want_ charms to be designed. The conversation here is not about how things used to work, but how we _want_ them to work.

In those terms, every single time I've had this conversation so far, people came up with completely different reasons why they want the message in place. How many nodes are in place, whether the node is slave or master, whether it's degraded or fully working, etc. This smells like bad design on our side. What if you want to say both whether it's slave or master, and whether it's degraded or not, and also the node count?

We are the designers. Please join me making juju fantastic.

**Comment by stub42** [comment]
I think it has been an easy channel to provide information about _how_ the charm is active. Active, in developer mode. Active, replica database from external source. Active, profiling enabled. Active, public endpoint https://example.com. Active, backing up /var/lib/reports. This could all be determined by an administrator by interrogating the charm config, relations etc. If they have enough knowledge about the charms in play. It is much easier however if an administrator responding to an alert at 4am can just run 'juju status' to get an overview, rather than tracking down and reading documentation, playbooks & guides that in practice may not have been written yet. 'juju status' has become a useful tool, providing a common dashboard for exposing arbitrary information administrators find useful for maintaining production systems. At a glance. The Juju gui similarly for people using it. Canonical Livepatch status, Landscape client status, the role of particular units in an asymmetric charm (master, standby). Information required for example to run an action against the correct unit. While in some cases the information lags behind reality (such as livepatch status), it is still practically useful to tell between working and broken. In other cases, where state is being driven by the charm, the status is an up to date source of information. Such as when charm state is driven by actions (eg. failover, switchover, drain actions, 'read only' mode).

The short, single line status message has never been a great approach for conveying all this sort of information. There is lots of useful information a charm may wish to provide, but there is only room for the most immediate and useful. If we want to replace this communication channel with something that allows a charm to convey multiple pieces of arbitrary information, that would be great, if combined with a quick and common way to view it (eg. 'juju status -v', 'juju status -v appname'). Even if just exposed in the status yaml/json data, a plugin could aggregate and render it, but preferable if it was built into the Juju CLI so it could be referenced in charm operations documentation etc. But I guess this issue is on the operator framework rather than juju core, so maybe best not to design new features here.

**Comment by woutervb** [comment]
I agree with the usefulness, as described by @stub42 above. Having a quick dashboard with an overview of the 'message' on active units would be great. 
Hiding this with an additional flag like -v (verbose) is a workable solution imho.

What might be a thing to consider, is giving only a single line of information (as is currently the case) for 'juju status -v', but give more lines (if available, as it will be something new) if a single, or multiple charm's are queried. So e.g. juju status -v <charm1>, would give up to 5 lines of output. 
A use case I can come up with is e.g. the ntp charm, where the detailed output would give information about peers, offset, sync frequency.

For the postgresql charm, it could indicate (if there is a master/slave setup), if the slaves are still syncing and their last recorded offset.
Same /similar for the mongodb charm (which would have prevented unplanned downtime in multiple occasions, as cluster was broken)

It will require some changes to juju in order to facilitate this, but it might be something.

**Comment by evhan** [comment]
For what it's worth I prepared #138 without even noticing this issue (sorry about that, bad form I know!). Our rationale for that patch was two-fold. One reason was to provide information about the "mode" the app or unit is operating in, like others have already mentioned in this thread (primary vs. replica, the name of the work queue the software is pulling from, processed job count, etc.). The other reason was just to make metaprogramming easier, since having different signatures for what are otherwise equivalent classes caught us out two different times, so it seemed like a nice quality-of-life improvement.

**Comment by niemeyer** [comment]
@stub42 Yes, again, I know there are dozens of different interesting pieces of information that are put in the status. That's exactly why this is not a proper user interface or experience. As I said, I also realize that people do that because there's no better way.
 
Anyway, I see we're hitting a nerve and I the operator framework should feel great, and not liking it because of this simple issue would be a terrible outcome.

So here is what I suggest we do next:

1. We'll support a message in the operator framework.
2. We'll add support in juju for providing structured information to admins
3. Juju itself will stop communicating the active message, so setting it becomes irrelevant, via the operator or otherwise.

**Comment by dshcherb** [comment]
Closing as #138 got merged.
