### ISSUE TITLE
Prevent use_juju_for_storage=True on Juju 4

### ISSUE THREAD

**Issue by benhoyt** [canonical/operator#1284]
Per https://github.com/juju/juju/pull/17721, controller storage is being removed in Juju 4.0, so we should prevent its use there. We should also update the various documentation (Ops reference docs, any SDK docs or tutorials).

Note that it's already [deprecated](https://github.com/canonical/operator/blob/5a21cd28a47b8d5f1142d794130ae70f23b5cd26/ops/main.py#L459-L464) with a deprecation warning in `ops/main.py`.

**Comment by dimaqq** [comment]
Would this rather be a `charmcraft lint` item requiring an `assumes` setting?

Or a run-time fail that's only triggered if Juju is indeed 4.x?

**Comment by benhoyt** [comment]
@james-garner-canonical Another small one for you. I'd recommend just a run-time fail if Juju is indeed >=4.x.

**Comment by jameinel** [comment]
Juju isn't dropping state-set/state-get in 4.0 (afaict), which is what is
used by JujuStorage
<https://github.com/canonical/operator/blob/98a4e4f44d37d3361a253bc1eff49eee2ca6d140/ops/storage.py#L219>.
That specific PR is about charms that used a Persistent Volume Claim for
their local state.
I'll reach out to confirm. I'd be open to dropping "use_juju_for_storage",
but more in favor of explicit lifetimes for StoredState objects. (Are they
persistent for the lifetime of a unit, vs persistent for the lifetime of
this container.)

I don't think the one-big-hammer for all StoredState is what we want to
have.

FWIW, that particular PR was also rejected.

John
=:->

**Comment by tonyandrewmeyer** [comment]
> Juju isn't dropping state-set/state-get in 4.0 (afaict), which is what is used by JujuStorage <https://github.com/canonical/operator/blob/98a4e4f44d37d3361a253bc1eff49eee2ca6d140/ops/storage.py#L219>. That specific PR is about charms that used a Persistent Volume Claim for their local state. I'll reach out to confirm. I'd be open to dropping "use_juju_for_storage", but more in favor of explicit lifetimes for StoredState objects. (Are they persistent for the lifetime of a unit, vs persistent for the lifetime of this container.) I don't think the one-big-hammer for all StoredState is what we want to have. FWIW, that particular PR was also rejected. John =:->

Note that this issue isn't suggesting dropping all the `StoredState` functionality, just using Juju as a backend rather than a local sqlite3 database.

Right now, `use_juju_for_storage is already very deprecated. The [docs](https://ops.readthedocs.io/en/latest/index.html#ops.main) say it shouldn't be used, and we emit a [warning](https://github.com/canonical/operator/blob/98a4e4f44d37d3361a253bc1eff49eee2ca6d140/ops/_main.py#L456) if it is explicitly enabled. It's only used without being explicitly enabled [if it's a podspec charm](https://github.com/canonical/operator/blob/98a4e4f44d37d3361a253bc1eff49eee2ca6d140/ops/_main.py#L348), which is hopefully very few now.

If state-set/state-get will still be in Juju 4, that takes away the priority for this issue (and means we should adjust our docs) but they'll still be almost unused with ops charms. If there's a use-case we believe is valid outside of podspec charms, then we'd need to adjust things to guide towards that.

**Comment by benhoyt** [comment]
Let's discuss with @jameinel in our next Charm Tech sync with him.

**Comment by benhoyt** [comment]
Per the above and a follow-up voice discussion with John M, we're not going to remove this, as it's not going away in Juju 4. We'll leave `use_juju_for_storage` in place but keep it deprecated. However, we'll keep pushing people to use peer relation data or the application data bag for longer-term stored state.

The main problem with StoredState is that its lifetime is unclear (is it lifetime of unit? pod? container?). So later, if needed, we could design a specific feature that allowed storing state with explicitly-specified lifetimes.
