### ISSUE TITLE
Timeout not being respected for `container.exec` 

### ISSUE THREAD

**Issue by paulomach** [canonical/operator#1329]
Hi folks,

on the mysql-k8s charm, we have a test that will freeze one workload instance (mysqld) out of a three instance cluster, by sending a `SIGSTOP` to it. One failed run [here](https://github.com/canonical/mysql-k8s-operator/actions/runs/10500119558/job/29088191706)

Event handlers that try connect to the stopped mysqld instance will hang, hanging the whole handler. To avoid getting stuck, `timeout` are added to the `container.exec` calls [where this connection](https://github.com/canonical/mysql-k8s-operator/blob/a301a4a79febd3f5130598c4a74288a9fc5f8bb1/src/mysql_k8s_helpers.py#L615) is attempted.

What we see is that the timeout are not respected, i.e. the `container.exec` calls are not returned.

One workaround is wrapping the commands passed to `container.exec` with coreutils timeout, which works as expected.

Before I try a sample charm to reproduce it, do you have thoughts on that?

**Comment by tonyandrewmeyer** [comment]
It seems to me that this should work. Under the hood, there are a couple of different timeouts - Pebble is told the timeout for doing the execution, and then ops waits for that amount of time as well (but should be getting the failure from Pebble).

A sample charm to reproduce would be really great if you're able to make that. Otherwise if you can reproduce with mysql-k8s outside of CI then digging into what Pebble is doing after the timeout would be informative (to see which side things are going wrong on).

**Comment by paulomach** [comment]
I've wrote a charm to test the issue in isolation, and it works as expected. I'll inspect the issue again in the context of mysql-k8s charm. If I cant reproduce it, I'll close this one.

**Comment by benhoyt** [comment]
Going to close this preemptively as it seems like it's likely not an issue now - feel free to reopen if you end up reproducing.
