### ISSUE TITLE
self.model.pod.set_spec should only be run on leader

### ISSUE THREAD

**Issue by mthaddon** [canonical/operator#161]
Currently self.model.pod.set_spec should only be run on leader to avoid the following charm error:

raise ModelError(‘cannot set a pod spec as this unit is not a leader’)

Would it be worth updating that function call to only execute on the leader, to avoid the need for charm writers to do this?

**Comment by dshcherb** [comment]
I think it would be inconsistent with the behavior for other things a leader can do vs non-leader units, for example:

- setting app status;
- writing to app relation data.

**Comment by jameinel** [comment]
Given app data and pod spec, I feel like exploring charms that only run any
hooks on the leader is worth prototyping.

You can imagine writing 'is_leader' before even calling main() and just
ignoring the rest of the code.  Especially on K8s where the only real
interaction is restricted to the leader.

John
=:->

**Comment by niemeyer** [comment]
As I understand it, the issue here is that setting the spec will already fail today if it's not the leader, and the specific proposal is to make the set_spec ignore the call if it happens on a unit that is not the leader. This sounds like an error prone behavior.. it would be error prone to just ignore the call as if it had worked. The solution is to have something similar to:
```
if unit.is_leader():
        # ... do something ...
```
Which is straightforward to read and write.

I'm closing this issue with that background, but please do let us know if I'm mischaracterizing it somehow.
