### ISSUE TITLE
Handling of application level relation config feels wrong

### ISSUE THREAD

**Issue by gnuoy** [canonical/operator#164]
I believe that part of the purpose of the operator framework is to abstract the charm author from having to understand the mechanics of Juju. When it comes to application level relation config you have to know how the juju mechanics work to be able to utilise it. You have to know that it can only be set by the leader and that it is a special subclass of relation data accessed via the '.app' relation attribute. It felt a bit unclean to me when using it but I appreciate that it is subjective and a minor issue.

**Comment by johnsca** [comment]
> I believe that part of the purpose of the operator framework is to abstract the charm author from having to understand the mechanics of Juju.

I don't think this is true.  I think the reactive framework tried to abstract aspects of Juju and that lead to much of the confusion for new users since there were now two sets of mechanics that needed to be understood.  The philosophy of the operator framework is to stay as true and close to the Juju model and mechanisms as possible while translating that into a Pythonic style of code and APIs.

**Comment by gnuoy** [comment]
fair enough
