### ISSUE TITLE
RFC: Grafana and Prometheus Charms

### ISSUE THREAD

**Issue by relaxdiego** [canonical/operator#173]
Hi, apologies if this is the wrong place for this but I could not find a mailing list or a discourse site where this would be more appropriate to discuss. I finished the first iteration of the operators for prom and grafana on k8s and I’m submitting it here for the community to scrutinize: https://youtu.be/bf-YClFjANw

Links to the repos are in the video description.

**Comment by relaxdiego** [comment]
Closing and moved to https://discourse.jujucharms.com/t/requesting-feedback-charmed-prometheus-and-grafana-on-k8s-using-operator-framework/2783?u=mmaglana

**Comment by stub42** [comment]
I am curious why http_interface.Client wraps the entire endpoint rather than a single relation. Some work I'm doing is very similar, except the signature to the Client accepts the relation rather than the relation_name. It seemed cleaner to let the charm decide how to handle an endpoint with multiple relations and have a client that deals with a single relation, rather than a client dealing with an entire endpoint (0 or more relations) and a more complex API. I think the code as it stands will not support relating grafana to multiple prometheus servers, which may well be fine for your use cases. But may be worth reconsidering if this is to become shared code. I can't provide a counter example yet, as I'm not as far advanced as you are, but hopefully this week.
