### ISSUE TITLE
Support application-version-set hook tool

### ISSUE THREAD

**Issue by stub42** [canonical/operator#174]
I can't find an interface to the `application-version-set` hook tool. Has it been deprecated, or is it just missing from the framework?

**Comment by jameinel** [comment]
I think it is just missing from the framework. It should probably go on
something like Unit.set_application_version. We might want to think about
it a bit, because it feels weird to be setting "application" stuff on the
Unit. Maybe Unit.workload_version = 'X.Y.Z' ?

I think application-version-set predated the switch from Services to
Applications, cause it is now poorly named.

John
=:->

**Comment by niemeyer** [comment]
@jameinel Let's put it on the pipeline.

**Comment by johnsca** [comment]
@jameinel +1 to calling it `workload_version` instead, but it should be noted that it is in fact set at the application level (by the leader) and not the unit level.

**Comment by niemeyer** [comment]
It needs agreement between the framework and juju itself. We can't call it one thing here and a different thing there. Also, if this field is in the application, and it's called version, it's _indeed_ the application version not the workload version. Each unit will have its own workload, potentially with different versions.

Ultimately this is a poor man's way to communicate information to the user. Eventually we need a proper way to communicate arbitrary data.

**Comment by jameinel** [comment]
It is set per-unit and not by the leader the way Juju currently implements
it (determined by digging through the Juju code). It uses a sorting
algorithm to choose the "highest" version to display.

If Juju provides an future way of setting it for the overall application,
then we can expose it on the Application object as well as the Unit.

I believe it is called Application because that is what we were calling the
workload in Juju 1.X (when Applications were called Services).

**Comment by niemeyer** [comment]
@jameinel Makes sense, and that makes it even worse. It's inconsistent inside juju itself already.
