### ISSUE TITLE
We need to build strings using the logger infrastructure

### ISSUE THREAD

**Issue by facundobatista** [canonical/operator#176]
IOW do NOT do this:

```
logger.debug('Creating a new relative symlink at {} pointing to {}'.format(event_path, target_path))
```

but this:

```
logger.debug('Creating a new relative symlink at %s pointing to %s', event_path, target_path)
```

**Comment by chipaca** [comment]
it'd be nice if logger had a new-style flavour, but yes, 100%.

**Comment by relaxdiego** [comment]
Why not f-strings?

logger.debug(f'Creating a new relative symlink at {event_path} pointing to {target_path}')

**Comment by chipaca** [comment]
> Why not f-strings?
> 
> logger.debug(f'Creating a new relative symlink at {event_path} pointing to {target_path}')

we're not using f strings because we support python 3.5 which doesn't have them yet.
And, that has the exact same issue as doing .format: you're paying for serialising the things irrespective of whether you're actually doing the logging (ie if you're on INFO the logger.debug call should be a NOP, and it is --- but that's for naught if you're dumb)
