### ISSUE TITLE
Improve how to access the events

### ISSUE THREAD

**Issue by facundobatista** [canonical/operator#187]
We currently can do:

     events = charm.on[name]
     self.framework.observe(events.relation_joined, ...)

Using `on` as a kind of dict looks weird. Specially because it's not a dict at all.

In IRC we thought about improving that and just using a method:

     events = charm.on.get_events_for(name)
     self.framework.observe(events.relation_joined, ...)

This will be much more discoverable and not be sending the wrong signals about what's underneath.

**Comment by chipaca** [comment]
There are two sides to this:
* the `on[foo]` thing is not discoverable, and has not been explicitly called out sufficiently in the documentation to be clear, and
* because there is no public method and on is not really a dictionary it can be surprising that you can use it in this way

we'll address the first of these soon, and leave this issue open and come back to it to fix the latter further on, if we still deem it to be an issue.

**Comment by jnsgruk** [comment]
I believe this is now fixed since the change that introduced `ops.framework.ObjectEvents`, which is the base class for `ops.charm.CharmEvents`.

Closing for now :)
