### ISSUE TITLE
Initial selection of reviewed charms

### ISSUE THREAD

**Issue by dshcherb** [canonical/operator#205]
Opening this issue to track PRs for 3 example charms:

https://github.com/canonical/cockroachdb-operator/pull/1
https://github.com/canonical/haproxy-operator/pull/1
https://github.com/canonical/keepalived-vrrp-operator/pull/1

A bundle example can be found here:
https://github.com/dshcherb/bundle-cockroachdb-ha

**Comment by chipaca** [comment]
I looked at the three PRs. Thank you! They look very promising.

However, right now they all depend on interfaces that are still under a personal account.
If these are to be our examples (and I don't see why not), then they should build on things in the framework itself, or at least on components that are of an adequate quality with shared ownership -- which means we need to look at those components and discuss onboarding them one way or the other.

Let's discuss that tomorrow.

Mostly: I like what I see; my issues are not about functionality nor (at first pass) about the logic, but about what would make these great examples; namely: comments and docstrings explaining what's going on, what the intent is, etc. After that, naming and formatting issues. And, to repeat, because we want these to be our example charms, we need to look recursively into the interface components and bring all of it up to the right level.

**Comment by niemeyer** [comment]
I've renamed the issue so that we track other initial charms up for review here as well.

**Comment by jameinel** [comment]
https://github.com/jameinel/ubuntu-lite/pull/2

is the 'minimal' Ubuntu-lite charm.

**Comment by jameinel** [comment]
https://code.launchpad.net/~wordpress-charmers/charm-k8s-wordpress/+git/charm-k8s-wordpress/+ref/master

is also a charm to track.

**Comment by relaxdiego** [comment]
I might as well add these too:

* https://github.com/relaxdiego/charm-k8s-prometheus
* https://github.com/relaxdiego/charm-k8s-grafana

**Comment by chipaca** [comment]
I'm closing this issue, as we're tracking these things separately now. Thank you all!
