### ISSUE TITLE
can not determine the number of instances of the application

### ISSUE THREAD

**Issue by narindergupta** [canonical/operator#206]
Currently, the framework does not support to get a number of instances of an application. It should be a replication of the application in kubernetes. Zookeeper while starting the server needs to pass the number of servers exists in the cluster.

**Comment by dshcherb** [comment]
To add more context, the container image expects a number of servers to be passed in:

https://github.com/kow3ns/kubernetes-zookeeper/blob/24482601ee7f27156f0014fb19f9f8526c9f7a38/docker/scripts/start-zookeeper#L101-L102

Which is later used to generate a list of server names to be placed into a zookeeper config:

https://github.com/kow3ns/kubernetes-zookeeper/blob/24482601ee7f27156f0014fb19f9f8526c9f7a38/docker/scripts/start-zookeeper#L180-L205

It seems like the authors of that image were missing a way to interrogate the deployment state to get hostnames of existing units so they instead exposed an option to specify the amount of servers and let whoever deployed this app provide the target amount of units in order to then generate a list of hostnames of other units.

Juju has a feature called `goal-state` that allows you to get the number of units of a given application but we do not currently have it exposed in the framework because of certain design considerations, one of which is that this state may change over time and there are no explicit events to tell a unit about a state change.

My initial guess is that exposing a config option to say whether you want an HA deployment or not could be a way forward. That way you could start (apply a pod spec) right away if `require-ha=False` and, if `require-ha=True`, wait for at least 3 operator pods to observe each other and let the leader pod apply a spec with the size specified based on `len(peer_relation.units) + 1`.

Zookeeper requires a quorum to be present for an HA setup to work and it is better to have an odd number of machines in a cluster - that's where the 3 unit condition comes from.
https://zookeeper.apache.org/doc/r3.2.2/zookeeperInternals.html

Then, as you scale the deployment up, you can trigger pod spec changes as new units are observed by the leader operator pod.

**Comment by jameinel** [comment]
I think we can use 'goal-state' to get the count and expose that as part of the Relation object.

Then you can use relation-created events on a peer relation to start tracking that "there should be 5 other units of this application" and as those units come up, you'll get 'relation-joined' for them, and you can use the `Relation.units` attribute to find the names for the units that actually start.

We could expose this as something like `Relation.expected_unit_count`. I'm not sure about that exact name, but that would be a start for exposing what 'goal-state' provides, but without the rest of the context of 'seeing the future that might not occur'.

There is still the problem that if some does:

```
juju deploy app -n 5
# one of those fails to start
juju remove-unit app/4
# no event will be given by Juju to tell you that the expected unit count is now 4 not 5
# but if they do
juju add-unit app
# to go back to 5, or to go up to 7, you'll get relation-joined events with updated counts.
```

**Comment by jameinel** [comment]
duplicate: #165
