### ISSUE TITLE
Expose leadership settings

### ISSUE THREAD

**Issue by stub42** [canonical/operator#215]
I hear rumors that leadership settings have been or are deprecated, but I have use cases for the feature and peer relations are much more cumbersome to deal with. I think leadership settings should be exposed by the operator framework and the feature undeprecated.

Alternatively, provide charms and library code a simple API that exposes the application relation data on the peer relation as a simple dictionary, readable by all units and writable by the leader. This approach is problematic, however, as an implicit peer relation will need to be provided by Juju if there is not already one. Also, if there are several peer relations one of them will need to be chosen consistently. Note that library code has no way of declaring a peer relation for the charm that is using the library code.

Currently reviewing code that is attempting to initialize a pod after it is ready. The initialization can only happen once, so the lead unit needs to store the fact in leadership settings or in peer relation application data after initialization. If it does not do that, then initialization would run again when leadership changes. Also, we need to handle leadership changes while waiting for the pod to become ready, so we cannot rely on deferred events and the unit handling the deferred event may no longer be leader when the pod has become ready.

**Comment by jameinel** [comment]
I think we should definitely have a conversation about this. It seems a bit odd for a component to put data into what would otherwise be a shared bucket without being told to use it. (leadership settings or a peer relation both feel like something you should be explicitly asked to use, and told where in that bucket to put your data.)
As such, there doesn't have to be an implicit peer relation, but we can have the charmer tell the component where it can store the additional data.
I think it is appropriate that a component can't declare your charm has a peer relation. It can say "I need a peer relation to do X, and you can tell me what that is".

**Comment by stub42** [comment]
The operator framework should still expose leadership data, even if labelled as deprecated, to allow existing charms to be migrated to the operator framework and upgrade-charm handlers written and tested. While it is trivial to wrap leader-set/leader-get, it does mean the wrappers need to be mocked in tests rather than the Operator Framework test harness handling this.

**Comment by jnsgruk** [comment]
Closing for now; see discussion in: #466
