### ISSUE TITLE
Debugger "at" reserved words

### ISSUE THREAD

**Issue by facundobatista** [canonical/operator#234]
Currently you can call `juju debug-code` passing an `--at` parameter specifying the breakpoint name, or `all` (for all breakpoints) or `hook` (for hook-interrupting functionality).

Both `all` and `hook` are reserved names, the developer can not name breakpoints with them.

We were thinking today about the possibility of extending current debugger behaviour to allow the developer to interrupt methods registered to **internal events**. Having this conversation, we talked about the possibility of having "all" and "hook" part of a namespace, so no restrictions are applied to names.

The best we came up is moving those to `+all` and `+hook` respectively. 

Bad side of this is that `juju` will need to change its default: when `--at` is not specified at all, the `JUJU_DEBUG_AT` variable would become `+all`.

**Comment by jameinel** [comment]
juju debug-code --at=+all
doesn't feel great to type as a user. The original 'all' and 'hook' seem
quite nice, and I don't expect named breakpoints to care terribly about
colliding with them. The nice thing about 'all' is that it does feel
reasonably generic, that most charms would want to implement support for.

**Comment by jameinel** [comment]
The current functionality around --at is here:
https://github.com/canonical/operator/blob/8ee3fc1c5581cd1607223ca07232f73864935589/ops/framework.py#L764

At that point we have "event_path" which is an identifier of what event is being triggered. I think we could take the 'basename' of that path, and then check for:
```
if (basename in self._juju_debug_at) or (is_juju_hook and 'hook' in self._juju_debug_at):
```
And that cloud give us a way to drop into a handler for any event. We *could* use the full event_path, but those are generally not very nice names, and using just the simple event name instead of its full path does mean you might not be able to be very precise, but the tradeoff is the common case is much nicer to type.

**Comment by facundobatista** [comment]
The functionality we need to provide is the ability to interrupt the call to a method that was registered to an internal event (without touching the code, of course, otherwise you could always add a *breakpoint*).

So, we thought about checking the strings passed by the user; if they match with the event name, we interrupt the call.  For example:

    --at=on_myinterface_joined

Of course, if you name a breakpoint with that specific name, and the code goes through that breakpoint, it will also be interrupted; it's the developer responsibility to use good names, and the worst thing it will happen is that code will be interrupted twice....

**Comment by benhoyt** [comment]
I don't think this is important enough to spend time on right now, closing.
