### ISSUE TITLE
Feature request: Harness helper function/flag to run initial hooks as juju would execute?

### ISSUE THREAD

**Issue by Vultaire** [canonical/operator#237]
As a new user of the operator framework and of the Harness class, one of the things that caught me off-guard at first is that Harness.begin() does not trigger install, config-changed, or other hooks which would normally be expected to trigger when first installing a new unit of a charmed application.

Now, I've had time to think about this since and it does make sense, especially as the target of ops.testing.Harness appears to be unit testing and not integration/functional testing.

That being said, I can see where it may be useful to prep an initial state of a charm (initial relations, remote units, relation data, config data) and, after running e.g. harness.begin(run_initial_hooks=True) be able to have it trigger the normal set of hooks you'd expect to fire as if you were deploying the charm "for real".  It feels like we have part of this kind of functionality already with the framework triggering handlers on config and relation changes after Harness.begin() is called.

Again, for "pure" unit testing this may be going too far.  But I at least wanted to bring up the idea and solicit feedback.  This seems like it may be a common enough flow that it may be of use to others.

**Comment by jameinel** [comment]
The goal, very much, is to be able to test any part of your charm's
lifecycle. We currently like the idea of something like:

Harness.emit_install()

And having a similar 'emit_*' for all of the Juju events. You can currently
do the equivalent with:

 harness.charm.on.install.emit()

As that particular event doesn't take additional arguments. However, some
events do require more build up, and we would like to have a standard
pattern around it.

Mostly it is just a case of the most difficult bits to test were
config-changed and relation hooks, so that is where we started.

I wouldn't be opposed with something like: Harness.initialize_charm(),
which would run through all the Juju hooks up to the start() hook.
(x-storage-attached, install, relation-created, leader-elected (if you're
the leader), config-changed, start)

Having the right naming for the function is pretty useful to convey what it
is doing.Some brainstormed names:

   - initialize_charm
   - initial_events
   - run_to_start
   - simulate (we could include relation-joined and relation-changed post
   start if we wanted to do the 'full set' of Juju events). eg, you'd set up
   the entire model of related things before begin(), then begin() +
   simulate() and it would trigger the events as though deploy was happening.
   This is much less of a unit test, though.


In the mean time, we can certainly add helpers for emit_* of all the
standard events.

John
=:->

**Comment by chris-sanders** [comment]
Just found this, was looking for this same functionality. It is pretty easy to work around, having all of the 'normal' hooks fire would be nice a lot of people won't know what the right combination and order of those hooks are.

What about something that mirrors what you tell juju to get the hooks to fire.

- harness.deploy
- harness.add_unit

As examples
