### ISSUE TITLE
Action writing requires image dependencies

### ISSUE THREAD

**Issue by natalytvinova** [canonical/operator#239]
In the process of writing actions with operator framework, I noticed two not very obvious issues for the charm authors:
1. Framework copies the code to workload containers, which requires every container image to have python installed
2. It also requires PyYaml module

Is there any way to exclude those dependencies from container images?

**Comment by jameinel** [comment]
Juju currently runs actions in the application pod. This isn't due to the framework, it is due to where Juju runs actions.
There is an open bug in Juju (https://bugs.launchpad.net/juju/+bug/1870487) that we want to be able to support actions that should run in the Operator pod rather than the Application pod. (The idea was that you could put metadata on a particular action for Juju to know that it should exec that in the operator pod, not the application pod.)

We appreciate the feedback, and we definitely want to hear about issues like this, but it isn't something that can be fixed in the operator framework.
