### ISSUE TITLE
When install hook fails no other hook symlinks are created

### ISSUE THREAD

**Issue by woutervb** [canonical/operator#257]
Possibly related to the issue reported in #256.

I observed during the creation of a new charm that if for some reason the initial install hook never completes successfully none of the hook symlinks are created. During development this is annoying but okay.

But I fear that it also means that on production deployment this behavior can cause trouble, as for example the install fails due to some conflicting config settings and bad error handling on the python side the install fails. You end up with a unit that has a charm deployed that is non functional. And it cannot be fixed without redeployment as e.g. the config-changed and/or upgrade hooks are not created.

**Comment by jameinel** [comment]
If 'install' fails, does it fail without an error? Because if it had an
error, then Juju wouldn't progress to the next hook, but would want to run
install again. If it 'fails' softly (eg doesn't do what you want, but does
exit 0 telling Juju that it succeeded), then I could somewhat see what you
describe.

I'm not sure how you're seeing what you are seeing from the operator side,
though. If I look at the source:
https://github.com/canonical/operator/blob/master/ops/main.py#L219

That is where we set up the symlinks during main(). That happens before:
https://github.com/canonical/operator/blob/master/ops/main.py#L231

Which is where we tell your charm to handle the 'install' event.

That said, it does happen after:
https://github.com/canonical/operator/blob/master/ops/main.py#L209

which is where we initialize your charm class.

So it is true that if in your Charm's __init__ it raises an exception, then
we won't set up the symlinks. (We do that because we need the charm to
exist to know what relations it has, to know what relation hooks to create.)

Now we could do that differently. We currently use Charm.on.events() and
look for Hook or Action events. We *could* instead just look at the
CharmMeta object. It means you couldn't define your own HookEvent or
ActionEvent in code, but Juju wouldn't trigger those anyway, because it has
to be declared in metadata.yaml and actions.yaml for Juju to know about
those events.


So

   1. We could create the symlinks before instantiating your Charm, however
   2. How is your setup failing such that it *isn't* returning nonzero to
   Juju, such that Juju will want to run install again. (maybe you did 'juju
   resolved --no-retry, in which case you explicitly told Juju that you didn't
   want install to be run)
   3. Another way I could see that happening is if you were running under
   debug-hooks and you ran the install hook, saw that it failed, and then
   exited the terminal window without doing 'exit 1' to tell Juju that install
   failed. (juju relies on the exit code of the process that runs for the
   hook, and under 'debug-hooks' that is the debugging terminal.


I'd be ok with a 'belt-and-suspenders' patch that creates the symlinks
earlier. It isn't a fundamental problem (the current ordering is correct,
and an exception will return nonzero causing it to get retried until it is
successful), but it does mean that when people are playing with
it/tinkering with it, then it is likely to fail in less catastrophic ways.

(2) and (3) are not the 'correct' way to do things, but they are *obvious*
ways to interact with the system, and we should fail gracefully.

**Comment by woutervb** [comment]
Okay, I see what I was doing wrong. It was indeed the `__init__` that already failed due to a syntax error in some files that where included. So it actually failed before it even could reach `__init__`.

Not sure that there is a solution for this, possilby I could add a charm-upgrade symlink, but that is a bit beyond  the idea of not having to manage symlinks

**Comment by facundobatista** [comment]
A syntax error would be always detected when running the charm unittests locally in the developing environment. Maybe the best course of action here is to add (at least a couple of very simple) test cases.

**Comment by benhoyt** [comment]
Per above, this seems to have been a combination of `__init__` failing due to a syntax error. Not sure why Juju didn't retry in this case, as `SyntaxError` would have caused a non-zero exit code and Juju would have retried, but perhaps they were doing `juju resolved --no-retry` as John pointed out. In any case, any trivial charm tests or linting would have caught the syntax error.
