### ISSUE TITLE
How to use the interface for bidirectional communication

### ISSUE THREAD

**Issue by woutervb** [canonical/operator#260]
Looking to the documentation of interfaces (https://discourse.juju.is/t/implementing-relations/1051) this suggest to me that communication should be bidrectional.

The problem that I am facing, is that in the Requires part of the interface I would like to update the databag for a specific relation. But running something like (in the interface object):

        for relation in self.model.relations[self.relation_name]:
            if not relation.units:
                continue
            for unit in relation.units:
                if unit.name == unit_name:
                    logger.info('Found our unit entry of interest')
                    relation.data[unit].update({"repo_uri": repo_uri})

 fails with an exception;

    File "lib/ops/model.py", line 470, in __setitem__
    raise RelationDataError('cannot set relation data for {}'.format(self._entity.name))

So I am / was wondering how this is supposed to work.

**Comment by jameinel** [comment]
Relation data is made up of a bucket for each unit and application in the
relation. So if you have 'foo' related to 'bar' and foo has 2 units, and
bar has 3 units, there will be buckets for:

foo
foo/0
foo/1
bar
bar/0
bar/1
bar/2

Each of those is an associated space for that unit / app to convey its
information to the others. What you are doing above is *from unit foo/0*
you are setting the data in the unit bar/1's data bag. Which is not allowed.

Relations don't have directional bags, where foo/0 has a data bag only for
bar/1.

It gets slightly more complex, because foo might also be related to 'quux'
on a different relation. (that is the 'for relation in relations[endpoint]
in your above loop.)

So what you really want is:

    for relation in self.model.relations[self.relation_name]:
        if not relation.units:
            continue
        for unit in relation.units:
            if unit.name == unit_name:
                logger.info('Found our unit entry of interest')
                relation.data[*self.unit*].update({"repo_uri": repo_uri})


Put another way 'relation.data[unit]' is the data 'unit' is telling you,
'relation.data[self.unit]' is the data that *you're unit* is telling the
related units on the other side of the relation.

(Just for completeness, the application data set by foo can only be set and
read by the leader of foo, but can be read by all units of bar.)

**Comment by woutervb** [comment]
Hi, Thanks,

This is indeed the part that I got wrong and with the change, I can see that the result is actually returning to the other unit. This unblocked me for this part.
