### ISSUE TITLE
Warn that model.unit.is_leader() can raise an exception

### ISSUE THREAD

**Issue by timClicks** [canonical/operator#269]
We should add a note that the `is_leader()` method can return an exception. 
`is_leader()` is called when a charm is attempting to determine if it will be able to invoke hook tools that are restricted to leaders, presumably to avoid the possibility of exceptions.

https://github.com/canonical/operator/blob/ccf1dce276141d1e8641d63382bb6c3055eee731/ops/model.py#L182-L184

I would personally be more comfortable with logging the problem at WARN level and returning `False` or `None` if it's called in the context of a remote application.

**Comment by jameinel** [comment]
if you call remote.is_leader() then it is a programming error. hence the
exception. It doesn't protect you, and if you are trying to use it in that
fashion, you aren't getting the answer you think you are asking.

(eg, you are asking if the wrong thing is the leader which would always
return false and then *you* would not do what you should when you are the
leader.)

I think an exception is correct here.

I would potentially take it further and have a different Unit class for
yourself vs all other units, and not even have the method on units that
aren't you.

John
=:->

**Comment by jamesbeedy** [comment]
From a charm author perspective, we just want to know if we are the leader or not. To me, the naming `is_leader()` implies that would be able to get a boolean return similar to the `is-leader` command. I'm wondering if it would be more consistent and direct to mirror the functionality/output of the `is-leader` command and allow charm authors to simply handle a boolean return instead of a possible exception. I feel this more closely mirrors the existing `is_leader()` functionality in charmhelpers, and would allow the charm author to more directly solve the problem of determining if the unit is the leader.

Am I way off base here, does this make sense to others too?

**Comment by jameinel** [comment]
is leader does return a boolean.

It just raises an exception if you do:

unit = self.model.get_unit('other-app/0')
unit.is_leader()

self.unit.is_leader()

just returns a boolean.

**Comment by facundobatista** [comment]
We just discussed this on IRC. 

The proper behaviour is to return an exception, yes, as you can not check if other units are leaders. It will return a `bool` if you call it on own unit.

Leaving this open so we:

- improve documentation alerting this can raise an exception (as @timClicks suggested), explaining why

- improve the exception message, making explicit that this is a problem of "the code" and not something transient to "the process being run"

**Comment by jameinel** [comment]
We brainstormed some possible exception messages to see if it is clearer why we are raising the exception:

* You're calling is_leader on a different Unit that yours, which doesn't make sense
* cannot determine leadership status for remote applications
* invalid request: leadership status of remote units is not available
* invalid request: you can't do that dave
* is_leader is only valid for yourself
* leadership status of remote units is not visible to other applications
* leadership status is only visible for your own application

**Comment by facundobatista** [comment]
+1 to "leadership status of remote units is not visible to other applications"

**Comment by timClicks** [comment]
I understand the rationale here. @jameinel's example makes it clear that charm authors can't stumble into the exception, and thus the error state. 

Raising an exception is the perfect thing to do from a Python-perspective. But charms operate in a much different context to most Python programs.

An unhandled exception could be very costly to someone deploying a charm. A non-zero exit is very difficult to recover from in a live model. Unless you are writing a charm, the error state is very difficult to resolve. Accordingly, we should only raise exceptions if we genuinely believe that we can't proceed. 

In this case, `is_leader()` could easily return `False` in cases where its argument is invalid. Callers would be well behaved and the model would progress happily.

**Comment by timClicks** [comment]
I've expanded my thinking slightly [in a discourse thread](https://discourse.juju.is/t/when-to-send-an-application-into-an-error-state/3046)

**Comment by stub42** [comment]
is_leader() could certainly lie to buggy charm code, returning False, and hiding the logic error from the charm author, keeping them unaware of the problem or keeping them busy chasing their charm failure in unrelated code. I don't think this is as helpful as raising an exception, alerting the charm author as close to the root cause as possible. I don't care if it is a RuntimeError, like the existing code, or an AttributeError, if you remove the method from non-local units.

**Comment by jameinel** [comment]
https://github.com/canonical/operator/pull/279 should address the issue of documenting why we are raising an exception.
We should also clean up the exception message.

I think the longer discussion about whether it is ok to go into an Error state due to a programming error is good to have in a discourse post, and we can use that discussion to move forward.

**Comment by jameinel** [comment]
I also updated the error string in #279
