### ISSUE TITLE
hook exception logged at DEBUG

### ISSUE THREAD

**Issue by jetpackdanger** [canonical/operator#289]
hook output is logged at the DEBUG level, which is not visible by default in "juju debug-log". In order to see this output, the user must have run "juju model-config logging-config='<root>=DEBUG'" beforehand. This  makes debugging charms more difficult that it needs to be, especially if one is creating new models a lot.

This output should be logged at some log level that is visible by default, perhaps WARNING for stdout and ERROR for stderr. INFO might be more semantically appropriate for stdout, but since the default log level is WARNING, this would still result in stdout still being hidden by default, and in the normal case I'd expect a charm to output nothing.

Example:
```
application-mattermost: 13:41:50 DEBUG juju.worker.uniter [AGENT-STATUS] executing: running start hook
application-mattermost: 13:41:50 DEBUG juju.worker.uniter.runner starting jujuc server  {unix @/var/lib/juju/agents/unit-mattermost-3/agent.socket <nil>}
application-mattermost: 13:41:50 DEBUG unit.mattermost/3.start Traceback (most recent call last):
application-mattermost: 13:41:50 DEBUG unit.mattermost/3.start   File "/var/lib/juju/agents/unit-mattermost-3/charm/hooks/start", line 156, in <module>
application-mattermost: 13:41:50 DEBUG unit.mattermost/3.start     main(MattermostK8sCharm)
application-mattermost: 13:41:50 DEBUG unit.mattermost/3.start   File "lib/ops/main.py", line 191, in main
application-mattermost: 13:41:50 DEBUG unit.mattermost/3.start     charm = charm_class(framework, None)
application-mattermost: 13:41:50 DEBUG unit.mattermost/3.start   File "/var/lib/juju/agents/unit-mattermost-3/charm/hooks/start", line 60, in __init__
application-mattermost: 13:41:50 DEBUG unit.mattermost/3.start     self.framework.observe(self.db.on.database_joined, self.on_database_joined)
application-mattermost: 13:41:50 DEBUG unit.mattermost/3.start AttributeError: 'PostgreSQLClientEvents' object has no attribute 'database_joined'
application-mattermost: 13:41:50 ERROR juju.worker.uniter.operation hook "start" (via explicit, bespoke hook script) failed: exit status 1
```

**Comment by jameinel** [comment]
This is very much by design. I understand the difficulty when debugging
your own charm, but when you have lots of things running at the same time,
you probably don't want the verbosity all the time.

As for the issues with multiple models, Juju already has 2 solutions for
that. If it is just a testing controller, you can do:

  juju bootstrap --debug

Which will enable debug logging by default everywhere.

If it is a more stable controller that you don't want to rebuild, then you
can use:
  juju model-defaults logging-config=DEBUG

Which won't change the config of existing models, but will state that all
new models will use DEBUG as their default logging. You can also do
something like:

  juju model-defaults logging-config="<root>=INFO;unit=DEBUG"

which doesn't enable DEBUG logging for all of the juju workers, but does
enable debug logging for all unit messages.

We really feel that most people don't want to see the DEBUG messages most
of the time. And it doesn't seem that onerous to turn on when you do want
them.
If there is a particular message that feels more useful than others, then
I'm happy to discuss it and possibly change the log level. Generally we
want to keep this structure:
  DEBUG: useful when you want to focus on something but noise when there is
a lot going on
  INFO: shown by default. a particular hook invocation should really only
generate a small number of INFO messages
  WARNING: someone should be filing a bug if they see WARNING messages. It
may not need immediate response by a person, but it indicates something
that needs fixing. WARNING should never be a *normal* part of operation.
  ERROR: Needs human intervention right now
  CRITICAL: indicative of a programming error. Should generally not be
used, but is the sort of 'panic' or 'assert' that is being violated.
Critical actually tends to be an indicator for a programmer that they left
a log message in that they need to remove.

John

**Comment by stub42** [comment]
By the above criteria, this isn't a DEBUG message and should have been logged as ERROR or CRITICAL. The example is a Python traceback.

If stdout and stderr are both considered DEBUG, then the framework needs to catch exceptions and log them as ERROR or CRITICAL (then reraising or exit(1) to ensure the unit goes into an error state)

**Comment by facundobatista** [comment]
I think that @jetpackdanger has a point here. And also @jameinel.

All normal logging should be in DEBUG, "hidden" from normal output unless you enable debug logging. But if the charm crashes, and you have a failure and a traceback, that should be logged in ERROR.

**Comment by jameinel** [comment]
Agreed. I missed the fact that it was a traceback, which should, indeed, be logged at higher priority.

**Comment by jameinel** [comment]
I think we can have a catch-all handler for exceptions in ops.main.main() and have it log an exception: https://docs.python.org/3/library/logging.html#logging.Logger.exception
