### ISSUE TITLE
use charm state for Juju 2.8

### ISSUE THREAD

**Issue by jetpackdanger** [canonical/operator#317]
When Juju 2.8 arrives, charms will no longer be able to always rely on persistent local storage.

The operator framework should use state-set and friends where possible. Links: [overview](https://discourse.juju.is/t/whats-new-in-juju-2-8/2859#charms-no-longer-need-a-persistent-volume-for-charm-state), [details](https://discourse.juju.is/t/whats-new-in-juju-2-8/2859#new-capability-for-charms-controller-backed-key-value-store).

(I understand this is tracked internally and being worked on, but I couldn't find a public issue to refer folks to, hence this.)

**Comment by stub42** [comment]
https://discourse.juju.is/t/whats-new-in-juju-2-8/2859#new-capability-for-charms-controller-backed-key-value-store

**Comment by jameinel** [comment]
In 0.7, you have the option to request state to be persisted in the Juju controller instead of local disk. This is done with:
```
main(MyCharm, use_juju_for_storage=True)
```

For 0.7 this is not done automatically, for a variety of reasons:

1) Juju 2.8 does not allow you to call state-get and state-are not available during collect-metrics. While we still allow you to write a hooks/collect-metrics script and it will get called, but it won't fire on.collect_metrics (because it can't load/save the events because of no state-get.)
2) Interacting with state-get and state-set are expected to be a little bit slower than reading and writing to an SQLite database. We want to make sure it doesn't become a critical bottleneck (especially if you scale to many units running at the same time.)
