### ISSUE TITLE
Create symlinks when Juju version doesn't support dispatch

### ISSUE THREAD

**Issue by gnuoy** [canonical/operator#362]
I recently migrated a charm to use charmbuild and the charm deploy failed because only the install,start and upgrade-charm hooks were ever fired. After some head-scratching I believe this was down to the new ops dispatcher code relying on a version of Juju greater than the one I was using (2.7.6). If the operator framework requires a minimum Juju version then I think that it should throw an exception if this min version is not met rather than failing silently. 

Fwiw I've also raised https://github.com/canonical/charmcraft/issues/104

**Comment by jameinel** [comment]
It shouldn't require a newer version of Juju. If you use dispatch, it does,
but if you symlink start for older versions of Juju, then it will create
the rest of the symlinks on the first event. (Juju <2.7.6 fires 'start' as
the first hook.)

**Comment by gnuoy** [comment]
I build my charm with charmbuild and deployed to a 2.7.6 env. So charmbuild created the dispatcher file so the operator frame work did not create the symlinks and the hooks failed to fire.

**Comment by gnuoy** [comment]
Sounds like https://github.com/canonical/charmcraft/issues/104 is valid and this bug is not.

**Comment by jameinel** [comment]
This is related to the fact that charmcraft creates hooks/install that points at 'dispatch' which then force sets JUJU_DISPATCH_PATH to get the right hook event triggered. However that code path on older Juju versions causes it to *not* create the symlinks for events other than install, etc.
If we want to continue linking 'dispatch' instead of 'src/charm.py' then we have to have it set JUJU_DISPATCH_PATH because otherwise you can't get sys.argv[0] to point to what you want. (playing games with 'exec -a' don't work because Python is writing sys.argv based on its arguments, and there doesn't seem to be an override in *python* for doing it differently.)
We'll use JUJU_VERSION the environment variable to determine if we think we need the symlink paths (or if a charm doesn't have a dispatch regardless of the version of Juju).
