### ISSUE TITLE
Testing harness update_config() isn't updating the config

### ISSUE THREAD

**Issue by ed1000** [canonical/operator#467]
I was writing some tests for a charm that required a change in a configuration value. When trying to override configuration values in a test, using update_config(), I found out that the configuration isn't being changed.

You can find the code here: https://osm.etsi.org/gerrit/#/c/osm/devops/+/9948/11/installers/charm/ro/tests/test_charm.py

**Comment by jameinel** [comment]
I don't know the specifics of what you were expecting that isn't happening,
but you can see that we have direct tests that update_config changes the
values that are seen by the charm:
https://github.com/canonical/operator/blob/ee7194fdf85e5d5865afc2339314f7d02b089996/test/test_testing.py#L456

The code also doesn't require the charm to have registered a config handler
to update the config that it knows about. (The internal records of the
contents of config are updated before we attempt to send an event.)

I don't know if it is relevant or not that "enable_ng_ro": "False" is
setting a string filled with "False" which evaluates to boolean True
(because it isn't an empty string).

so if you were doing:

if config['enable_ng_ro']:

Then that would evaluate to True, because non-empty string is boolean True,
while
update_config({"enable_ng_ro": False})

evaluates to boolean False.

Because charm config.yaml has types in its schema, I'm pretty sure you
would get a Boolean and not a String from the real config, but I'm not sure
how to go from the "patch set" that you list on that URL to the actual code
to find metadata.yaml to point you to your settings.

**Comment by ed1000** [comment]
I had a doubt about the type to pass because the type points to Mapping[str, str] (https://github.com/canonical/operator/blob/master/ops/testing.py#L595) but I've tried both str and bool and the result is the same (doesn't change the value).

**Comment by ed1000** [comment]
Closed the issue because it was a small error.
