### ISSUE TITLE
Tests pass even if charm isn't deployable, due to invalid config type, for example

### ISSUE THREAD

**Issue by mthaddon** [canonical/operator#482]
If you write a charm and set a config entry to have an invalid type (e.g. `integer` rather than `int`) tests will still pass, with no indication that the charm isn't deployable.

I've created an example charm https://code.launchpad.net/~mthaddon/+git/charm-test to demonstrate this. If you build and then deploy this charm you get:

```
$ juju deploy ./charm-test.charm
ERROR invalid config: option "thing" has unknown type "incorrectvariabletype"
```
However, running tests things look fine:
```
$ ./run_tests 
test_config_changed (tests.test_charm.TestCharm) ... ok

----------------------------------------------------------------------
Ran 1 test in 0.003s

OK
Name           Stmts   Miss  Cover   Missing
--------------------------------------------
src/charm.py      19      1    95%   36
--------------------------------------------
TOTAL             19      1    95%
```

I've also filed https://github.com/canonical/charmcraft/issues/249 as I think `charmcraft build` should also fail to build a charm that won't deploy.

**Comment by rbarry82** [comment]
This validation is coming directly from Juju. I guess we could try to type it and see if we can cast it to `str`, `int`, `float`, or `list(dict)` (more or less what the Juju code is doing), but it looks like the Charmcraft validation has this covered, and the cause is a little too far from the effect for Of to handle it. Even here, we call out to `juju config-get` and trust that it's returning something we can deal with rather than individually validating.
