### ISSUE TITLE
is_running() method for services

### ISSUE THREAD

**Issue by martinrusev** [canonical/operator#494]
While developing Charms, we frequently have to check if the service is currently running, like so:

```
    def _is_running(self, container, service):
        """Helper method to determine if a given service is running in a given container"""
        try:
            service = container.get_service(service)
        except ModelError:
            return False
        return service.current == ServiceStatus.ACTIVE
```

```
        # Check we can get a list of services back from the Pebble API
        if self._is_running(container, "grafana"):
            logger.info("grafana already started")
            return
```

Could be useful if we have that method available as a part of the Operator Framework.

**Comment by jnsgruk** [comment]
Perhaps a method implemented on the `Container` [class](https://github.com/canonical/operator/blob/1a1a079c70d5971082c5b3fdcbf271c62b298b08/ops/model.py#L1015)

Something like:

```python
def service_status(self, service_name: str) -> pebble.ServiceStatus
```

Might be nice?

**Comment by niemeyer** [comment]
Having a is_running() method in the service sounds nice, but the implementation above is a bit suspect. It hides an API error and pretends the service is just not running. That doesn't look like a great API behavior that we'd want to support in the operator framework itself.

This conversation and the code review also made me think that these APIs are not so nice to use. Maybe we should have a single get_services() method that returns something like a ServicesInfo, the plural of ServiceInfo. That type could indeed support more helpful methods, such as services.grafana.is_running() or/and services.is_running("grafana", "logger"). With that API the error checking might be done only once at the get_services() level, and the follow up usage would be free from exceptions because the data would be local.

@benhoyt What do you think?

**Comment by benhoyt** [comment]
Yeah, I agree any API/networking errors should be raised as exceptions (in Python land) and not hidden. However, I think what @martinrusev has here is okay, because it's only catching the specific `ModelError` exception, which is raised in the case of service not found. Other API or networking exceptions will still be raised.

I don't know if the way Martin's writing his charms means that he will sometimes call `_is_running` with a service name that's not (yet) known to Pebble -- if so the `ModelError` handling and `return False` makes sense. I would think you'd only want to know if a service is running *after* you've started it, so it should be an error if the service isn't found, but I'm not sure the context.

Note that `Container.get_service(name)` already returns a `pebble.ServiceInfo` object. The current way of spelling this (with exceptions bubbled up) is simply:

```python
is_grafana_running = container.get_service('grafana').current = ServiceStatus.ACTIVE
```

But we could easily add an `is_running()` helper method to the returned `ServiceInfo` object to simplify that.

**Comment by niemeyer** [comment]
> because it's only catching the specific ModelError exception,

That's a good point. Still, even if we implement that method, the pattern we are encouraging doesn't seem ideal. Every get_service is an independent API call to the server, while we could very well have a single status update request that gives us a general overview of what's going on at the moment.  This might be seen as early optimization, but my concern is that the API we're putting in place won't enable us to easily fix that issue later. Besides that, the get_services call returns a list, and if you don't know upfront what the names of the services are, that list has no convenient way to access it since we don't know the order of the services on it.

One possible way to fix that is to implement something along the lines of what was suggested above, changing get_services() to return a richer object. We could implement a matching API on that object and on the container itself, so that both could implement:
```
container.is_running(service)
services = container.get_services()
services[service].is_running()
```
The latter object is something like ServicesInfo, so that we can implement other things besides a bare mapping API (similar to existing patterns we have there). But the mapping API itself already gives us plenty of interesting features that we lack at the moment (`"grafana" in services`, etc).

In terms of implementation, it seems just as easy to implement an API that gives us all the current services than one that returns a list of services such as the current get_services method does.

So I suggest we act on it quickly before that API is stable in 2.9.

**Comment by jameinel** [comment]
Given things like pod restarts, vs charm state, I would want to be careful
to have an API that helps guide charms towards good behavior. Specifically,
I'm worried about persistent state vs ephemeral state and pods getting
rescheduled, etc. The fact that the logic inside charms already gets
restarted on each hook is already a point of confusion for users (our
abstractions make it look a lot like everything stays in memory between
restarts, because of StoredState objects), but other attributes of objects
do not.

Anyway, mostly I'm trying to point out that a charm may have every reason
to believe it has already told Pebble about a service, but because
pebble/the pod/(some other reason) was restarted, etc, it doesn't actually
know about it. So it is definitely a 'common case' that we want to make
easy in the api. We could
a) Raise a clear exception (NotFound/KeyError/,ModelError)
b) Return a 'tri-bool' (None for not found, True for running, False for
known-but-not-running). I like aspects of this since naive code can treat
the None as not started, but I worry that it is too clever and not obvious.
c) Change the return to be clear about whether we know about the service
separately from whether the service is started.

I do like the idea of a Pebble API that can give the collapsed information
about all known services.

**Comment by benhoyt** [comment]
@niemeyer: I do think that it's probably optimizing (well) before we need to. For the charms that do have multiple services in one container, they can be contentious use `get_services` to get them all at once.

> Besides that, the get_services call returns a list, and if you don't know upfront what the names of the services are, that list has no convenient way to access it since we don't know the order of the services on it. One possible way to fix that is to implement something along the lines of what was suggested above, changing get_services() to return a richer object. We could implement a matching API on that object and on the container itself, so that both could implement:
>
>     container.is_running(service)
>     services = container.get_services()
>     services[service].is_running()

We could change this, though if it stays as is I'm not worried about it. Python dict comprehensions make it so easy to turn a list into a dict:

```python
services = {s.name: s for s in container.get_services()}
services[service].is_running()
```

@jameinel I don't love the None-able bool -- IMO those are always more confusing than they're worth. I think that raising a clear exception is most Pythonic (this is what `get_service` singular does now).

**Comment by jameinel** [comment]
I think I agree with exception vs None, but we should be cognizant that we
are asking every call to is_running() to wrap it in a try/except because
Pebble may not know (yet) about the service, because the pod may have been
restarted.

**Comment by niemeyer** [comment]
> For the charms that do have multiple services in one container, they can be contentious use get_services to get them all at once.

Is that a realistic concern?  How many services would you have to have running for that to be an issue, and how many cases do we know that get anywhere near that limit?

> Python dict comprehensions make it so easy to turn a list into a dict:

Sure, but isn't that saying that Python can be used to workaround a poorly designed API?  Ideally we'll design thinking how best to use the API, rather than why it's not so bad.

**Comment by benhoyt** [comment]
Okay, so here's a concrete proposal:

* We change `Container.get_services` to return a dict that maps service name to `pebble.ServiceInfo`. This will provide easier access by service name, and allow us to extend it later with a customized mapping type if we want to provide more features.
  - However, the lower-level `pebble.Client.get_services` would still return a list, as those functions are supposed to be more "raw".
* We add an `is_running` method to `pebble.ServiceInfo`, which just returns `self.current = ServiceStatus.ACTIVE`.

**Comment by niemeyer** [comment]
Yeah, that sounds fine, but let's please not have a bare dict as the return from get_services in container.  Let's return a proper object that we can later on improve when/if the time comes, similar to other cases already in place there (I think we talked about one such case recently).

**Comment by benhoyt** [comment]
Sounds good -- will do today or tomorrow.
