### ISSUE TITLE
A Guarantee that workload is never null

### ISSUE THREAD

**Issue by balbirthomas** [canonical/operator#519]
### Introduction
At present in some events `event.workload` returns a container but not in others. I presume `self.unit.get_container()` always returns a container. Hence it is not clear why this difference in behaviour of the two. Prima facie it seems possible to guarantee that `event.workload` is always present, particularly if `self.unit.get_container()` provides such a guarantee.

### Use case
While it may not be possible to anticipate every use case, here is one -- In storage attached events, letting `event.workload` be the charm container allows the charm to pre populate the storage with data that may be useful/essential for the application when the application container starts subsequently.

**Comment by jnsgruk** [comment]
event.workload only exists for PebbleReadyEvents at the moment, and that's because the event is specific to a container.

I don't think this proposal would work because it is possible to specify multiple containers, and therefore event.workload could become ambiguous.

The current pattern of using self.unit.get_container() stops that ambiguity for those events that aren't for a specific container (I.e. config-changed)?

**Comment by jnsgruk** [comment]
Also worth noting that most methods on the Container object (push, pull, etc.) rely upon the Pebble API having been initialised - something that hasn't happened when the storage-attached event fires - so it's unlikely we'd be able to prepopulate files at that stage with the current implementation

**Comment by jameinel** [comment]
So you can't guarantee event.workload because a given charm can have >1
container. Just like you don't always have an event.relation, because there
can be many.

The reason why pebble_ready has an event.workload is because you are
explicitly saying "this container's pebble is now ready".

For charms that have a single container, it isn't as much of an issue. But
as a test example snappass-test very explicitly has 2 containers (one for
snappass and one for redis). For that charm, you should expect a
snappass_pebble_ready event and a redis_pebble_ready event. (just like we
do for eg db_relation_changed vs proxy_relation_changed).

**Comment by balbirthomas** [comment]
Closing in view of clarifications of infeasibility provided.
