### ISSUE TITLE
Unexpected behaviour on accessing StoredState across class boundaries.

### ISSUE THREAD

**Issue by balbirthomas** [canonical/operator#526]
## Issue
Suppose class A derives from `ops.framework.Object` and declares a `ops.framework.StoredState` class member called say `_stored`. Now suppose class B derives from class A and also declares a class member of type `ops.framework.StoredState`. If B tries to access `self.super()._stored` a runtime error is thrown with a messages something like "two objects claiming to be ... have been created". As far as I understand this happens because of the particular way in which  a `ops.framework.Handle` representation of the two `StoredState` objects are constructed (one which is a class member of B and the other which is accessed using the super class accessor). Both representations happen to be the same. Since `Handle` is fundamental to the identity of many `ops` objects this behaviour may not be particular to `StoredState` but probably also occur in situations other than the one described above. 

Perhaps this behaviour is as intended. If so, in the least could this be made explicit in documentation, for instance something along the lines "stored state must not be accessed across class boundaries" etc.

**Comment by rbarry82** [comment]
This is easy enough to avoid, and, in general, trying to access instance level variables in Python with `super().attribute` is bad practice as much as peeking behind a singularity, especially a protected variable.

**Comment by balbirthomas** [comment]
If the decision is that `StoredState` must not be accessed across class boundaries, then perhaps this should be explicitly documented in the [Operator Framework Documentation](http://ops.rtfd.io).

**Comment by rbarry82** [comment]
I have mixed feelings about this, principally because "Antipatterns to avoid" is a potentially endless documentation section, and the likelihood of a user actually calling `super()._stored` are very low outside of this ticket, considering that it has been more than 2 months with no additional reports.

**Comment by balbirthomas** [comment]
It is not a matter of "Antipatterns to avoid". It is a matter of documenting surprising behaviour. Consider if any other class member in Python shows behaviour like `StoredState` ? Will a Python developer be surprised by the behaviour of `StoredState` access across class boundaries ? This behaviour is probably not just limited to stored state . If this was an implementation detail perhaps it could be left undocumented, but it is in the public interface of the Operator Framework. Even if it was an implementation detail, is it Pythonic to not try and explain it, given that 
```
import this
...
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
...
```
I do not think there is such a thing as "too much documentation". There can be poorly written and verbose documentation for sure. But making things explicit, obvious and clear is never a bad idea. Finally I see no reason not to have an ever growing list of "Best Practices" and "Antipatterns to Avoid" documentation somewhere, that coaches the community of charm writers in the right direction and helps them navigate the complexities and peculiarities of the Operator Framework.

**Comment by rbarry82** [comment]
Better than documenting that "you should not access `StoredState ` across boundaries" or "`StoredState` should always be `__private` to signal to authors that it should not be accessed" would be making `Handle` would be an implementation in `__getattr__` which returns a cached handle (`Framework` already tracks a list of objects, and `Object` knows its parent's handle) if it's called this way.

I'm happy to re-open that and leave that as a future, low priority issue rather than documenting an edge case. This is purely prioritization.

As a matter of project priorities, time invested in documenting things which we should simply fix is not well spent. Documenting that `Object`s are tracked by `Handle` and should only have a single instance is, partly, duplicating what we already do have documented, and would involve writing docs, fixing this just in case someone does do it, potentially confusing authors, then re-writing or editing docs when it's done.

I'm hard pressed to think of a single project which has a "don't do this" documentation section, since having the code behave in expected ways obviates the need for this). The exception which was raised is very clear, and already says "don't do this", for something which is an unusual use case. 

The existing docstring. "Uniquely identifying the object" seems clear.

```
  class Handle:                                                                                                                                                                                                                               
      """Handle defines a name for an object in the form of a hierarchical path.                                                                                                                                                              
                                                                                                                                                                                                                                              
      The provided parent is the object (or that object's handle) that this handle                                                                                                                                                            
      sits under, or None if the object identified by this handle stands by itself                                                                                                                                                            
      as the root of its own hierarchy.                                                                                                                                                                                                       
                                                                                                                                                                                                                                              
      The handle kind is a string that defines a namespace so objects with the                                                                                                                                                                
      same parent and kind will have unique keys.                                                                                                                                                                                             
                                                                                                                                                                                                                                              
      The handle key is a string uniquely identifying the object. No other objects                                                                                                                                                            
      under the same parent and kind may have the same key.                                                                                                                                                                                   
      """         
```

There is a risk in having "too much documentation". Both for the reputation and adoption of a library, since it begs the question "if this antipattern is so common that they'd had to document not to do it, why isn't it just fixed?", as well as in giving people ideas. The point of a framework is, in general, to guide towards best practice through well-thought-out implementations, and to solicit PRs/bugs to fix the default behavior when it doesn't work as expected. We've all seen (or written) code which is firmly in the antipattern category, and there is a definite risk to technical blogs, StackOverflow docs, or official docs saying "you shouldn't do this", because developers may not have thought about the possibility at all until before that.

**Comment by balbirthomas** [comment]
Firstly, it is not my intention to insist that this issue by fixed "right now". As a developer I respect that careful work takes time, effort, deep thought and discussion. And of course priorities are completely the prerogative of the Operator Framework team. 

If I understand correctly that you are contemplating alternative means of redressing the issue such as

1. Make it hard to access objects that use `Handle` across class boundaries
2. Modify aspects of the implementation so that access across class boundaries does not raise an exception and behaves as expected
3. Any thing else

then by all means feel free to reopen the ticket and work at your own pace and I would certainly welcome that.

Once again I beg to differ that there is such a thing as "too much documentation". Let me make that precise in this context

1. Just stating in the docstring of `Handle` that it should only have a single instance is not enough, since the role that `Handle` plays in the Operator Framework has not been clarified and referenced within docstrings of other objects that use it. That handle provides the identity for `Object` must be made explicit. That hence `Object` derived/composed objects must also be singletons must be made explicit. That failing to do so an exception such as ... will be raised must be made explicit. 
2. What you refer to as a "risk in having too much documentation" is in my view an understandable reticence (I can empathise with) in explicitly documenting surprising behaviour within the Operator Framework. However this is not a problem of documentation. This is a problem of the implementation and/or API. If you feel the need to hide or obfuscate (though lacking documentation) some aspect of your software API then it should not be implemented as such in the first place, and definitely not in an open source product.
3.  Obfuscation through inaccurate and incomplete documentation is not the solution to fixing any mistakes we make as programmers (we all do, including me). Software engineering is hard and there is no silver bullet. On the other hand attempting to document ALL behaviour is precisely what creates the conditions to force recognition of shortcomings in the design or implementation. Hence as developers I think we should embrace comprehensive, carefully integrated and well knit documentation as it will make us better programmers, software engineers and hence improve the quality of our products. Expressing, vocalising and explaining our thoughts is precisely what clarifies and refines them. 

With respect for your time, I feel I have presented my views as cogently as I can and I would not wish to belabour the point any further. I respect you may have an alternative view point on the matter and the responsibility here is ultimately yours so I am happy to leave the final decision to you.
