### ISSUE TITLE
Stored State object do not play nice with serialization

### ISSUE THREAD

**Issue by balbirthomas** [canonical/operator#527]
## Issue

Attempting to serialize (for example `yaml.dump`) `ops.framework.StoredState` data structures such as `StoredDict` or `StoredList` do no result in standard Python representations of these data structures but produce something like `ops.framework.StoredList([...])`.
As a result charm code needs to convert the stored data structures into standard Python data structures before serializing them. The task is more involved when dealing with nested stored data structures.

It will be nice if it were possible to directly serialize  the stored lists and dictionaries and obtain the same results one would expect from standard Python lists and dictionaries.

**Comment by balbirthomas** [comment]
Just to elaborate bit further : this issue becomes particularly problematic when trying to build nested data structures and serializing them to strings so that they can be set in relation data. For example suppose `X` and `Y` are two stored state objects and the one needs to create a nested data structure say `Z` like this
```
Z["x"]=X
Z["y"]=Y
```
Doing so as above then serializing `Z` with `json.dumps()` exposes this issue (`X` and `Y` are serialized as `ops.framework.StoredState`)  . What is required is first to serialize `X` and `Y` then nest them under Z as in
```
Z["x"]=json.dumps(X)
Z["y"]=json.dumps(Y)
```
Then another serialization step (`json.dumps(Z)`) is required before dumping `Z` onto relation data.

These two steps have to be reversed in reverse order to obtain a python compliant data structure for Z.

This is but a simple example. Far more complex use cases arise when trying to build nested data structures corresponding to configuration objects or files for applications.

**Comment by niemeyer** [comment]
I believe the problem here is that there's an attempt to serialize a rich object which is not just a Python dictionary, but rather an actual type that implements a persistent layer.

In other words, if we serialize a StoredDict, why should we expect anything other than a StoredDict to be serialized?  The outcome looks correct from that perspective. If you want to serialize a barebones Python `dict` though, have you tried to indeed serialize a dict, as in transform the StoredDict into a dict:  `dict(obj.property)`?

Does that solve your problem?

**Comment by balbirthomas** [comment]
I had not tried taking a `StoredDict` object `X` and doing `dict(X)`. If that returns a `dict` then it would certainly be one solution, provided it is explicitly documented that this is how to use `StoredDict` when serialization is required. It may seem a trivial point to document but it is not self evident because of the way `StoredDict` is initialized. To initialize it one usually invokes the `set_default()` method with a `dict` argument. One does not use a constructor as in `StoredDict({key:value, ...})` . As a result it is not obvious that one has created a rich object. The impression conveyed is that one has stored a `dict` into object storage. 

Another point of view: `StoredDict` is initialized with and operated as a `dict`. Hence one would expect that when `StoredDict` is serialized, it's representation is that of a `dict`. Wouldn't violating this behaviour break duck typing ?

**Comment by niemeyer** [comment]
> I had not tried taking a StoredDict object X and doing dict(X). If that returns a dict then it would certainly be one solution, provided it is explicitly documented that this is how to use StoredDict when serialization is required.

`dict(X)` returns a `dict` because that's the `dict` constructor being handed an object it can iterate on. That's Python 101 rather than us doing anything special or unusual, so we don't need to document that behavior by itself (it's okay to refer to it as part of a larger tutorial, of course). Same applies to serializing a `StoredDict` object.. we don't need to tell people that serializing a `StoredDict` yield a `StoredDict` serialization rather than a `dict`, both because that's implied, and because it depends entirely on the code you're calling to serialize it. In other words, the behavior of a given tool when handed an arbitrary value is up to that particular module.

> To initialize it one usually invokes the set_default() method with a dict argument. One does not use a constructor as in StoredDict({key:value, ...}) . As a result it is not obvious that one has created a rich object. The impression conveyed is that one has stored a dict into object storage.

You've called a `set_default` method on a `StoredDict`, which was actually initialized by calling its constructor, which is unsurprisingly named `StoredDict`. That method, `StoredDict.set_default`, doesn't even exist on a `dict`. Why would one imagine that accessing that `StoredDict` will suddenly yield anything other than a `StoredDict`?

> One does not use a constructor as in StoredDict({key:value, ...})

How are you constructing the `StoredDict`, if not by calling `StoredDict`?

> Another point of view: StoredDict is initialized with and operated as a dict. Hence one would expect that when StoredDict is serialized, it's representation is that of a dict. Wouldn't violating this behaviour break duck typing ?

No, it wouldn't. Any good serialization package will serialize Foo as a Foo, not a Bar. That's unrelated to duck typing.

**Comment by balbirthomas** [comment]
I agree on most of your points. A tutorial in a larger context, that mentions serialization of stored state would be good.

> How are you constructing the `StoredDict`, if not by calling `StoredDict`?

Typically this is like this
```python
class MyCharm(CharmBase):
     _stored = StoredState()

    def __init__(self, *args):
        super().__init__(*args)
        ...
        self._stored.set_default(X={"some_key":"some_value"})
```
Hence the use of `StoredDict` is transparent here. It feels like object storage.

> No, it wouldn't. Any good serialization package will serialize Foo as a Foo, not a Bar. That's unrelated to duck typing.

Indeed this is a valid point. However it would be obvious only If use of `StoredDict` were explicit but that is rarely the case.

**Comment by niemeyer** [comment]
I see, thanks for the example. You're right that this looks less clear than I expected, since it's actually the `StoredState` that is being explicitly created and not the inner `StoredDict`.

For some context, the reason we need the custom type is because we need to flag the data as dirty if you change it, otherwise something like this:
```
self._stored.X["some_key"] = "other_value"
```
Would not be persisted, unless we do an entire walk on every single map every time a commit is done, which is a disproportionally expensive operation to perform for every single commit, even when nothing has changed.

We can probably reduce your concerns by making those types `dict` subclasses, so I'll look into this.  But even doing so won't solve your underlying request. For example:
```
>>> class Foo(dict): pass
... 
>>> import yaml
>>> yaml.dump({"x": Foo()})
'x: !!python/object:__main__.Foo {}\n'
```

So really the only real solution for this problem would be to drop the entire mapping API altogether, so that the developer could not access the storage area other than by something like `.save` and `.load`. Not sure if that's worth the tradeoff.

**Comment by rbarry82** [comment]
I mentioned this on the PR also, but, `set_default` is a method on `BoundStoredState`, which is essentially invisible to end-users. Our own docstrings [demonstrate using a simple type here](https://github.com/canonical/operator/blob/7edc40238a6e17aa2bcda2fd761ced7c5039ea8a/ops/framework.py#L924), and a new charm author discovering that attempting to serialize something which they instantiated as a simple/supported type throws an exception back is a terrible new developer experience which will harm adoption.

For OF internals, I don't think we need to worry that much about subclassing from the parent's native types. I would be sufficient to recurse through `StoredStateData._cache` when `.snapshot()` is called to also see if any of its children in the dirty cache are also `Stored*` objects, then return their underlying representations until we get to a flattened representation which can be marshaled. I doubt if anyone who has accidentally nested a `StoredDict` inside a `StoredList` really intended it that way, and instead it's come about as a side effect of treating the object cache like the types it pretends to be, and flattening is an acceptable side effect if documented.

Similarly, `RelationData` performing similar checking to avoid "accidentally" trying to put anything complex into Juju could sidestep much of the `rel.data[some_app][some_key] = json.dumps(...` pattern. `RelationDataContent.__setitem__` [requires that the passed value be a `str`](https://github.com/canonical/operator/blob/7edc40238a6e17aa2bcda2fd761ced7c5039ea8a/ops/model.py#L801). For charms exchanging data, this more or less requires `json.dumps()` in order to deserialize it on the other side. If `__setitem__` handled objects of more complexity, including our own objects, we'd see much less of this pattern and serializing to YAML/JSON/XML/TOML/whatever would be a case of workload events only, and much less ubiqutous/intrusive.

This moves the goalposts, since `rel.data["foo"]["bar"]["baz"] = "quux"` will never hit `__setitem__` at all, and `relation_set` will not be called, and would require strong documentation highlighting this, since it cannot be caught with exceptions. I didn't consider this option viable because "losing" data is much worse than other options.

You're right that any good serialization package will serialize Foo as a Foo, not a Bar. That's something we _could_ do, but deserializing a `Stored*` is not useful unless we wanted to reconstruct the entire hierarchy from `Framework` on up, and it wouldn't be the same `StoredData` on the other side of the relation in any case (or the "receiver" charm wouldn't have permission -- I'm not sure which, and I haven't tested, but it's not a useful case to deserialize in this way regardless).

It seems to me that we're hung up on the idea of what makes sense for OF internally as serializations/representations of OF's "own" classes rather than how charmers are using (or trying to use) the tools which we have given them.

**Comment by niemeyer** [comment]
> RelationDataContent.__setitem__ requires that the passed value be a str. For charms exchanging data, this more or less requires json.dumps() in order to deserialize it on the other side. If __setitem__ handled objects of more complexity, including our own objects, we'd see much less of this pattern and serializing to YAML/JSON/XML/TOML/whatever would be a case of workload events only, and much less ubiqutous/intrusive.

This is a limitation in juju itself, and one that we definitely want to see fixed soon. So expect improvements there soon.

> It seems to me that we're hung up on the idea of what makes sense for OF internally as serializations/representations of OF's "own" classes rather than how charmers are using (or trying to use) the tools which we have given them.

Encapsulation is a very important concept in software development. The design of how we set data in relations is disconnected from the requirements of how the charm persists information across events and executions, and how we design either of those do not give us an allowance to monkey patch the interpreter, etc.

With that said, good arguments have been made here.  Balbir's line of argumentation above is reasonable, for example. He demonstrated an expectation that is sane, and that we can keep in mind. That expectation speaks to data persistence, and not to relations.

Makes sense?

**Comment by jnsgruk** [comment]
Had a follow up discussion with @niemeyer this morning about this very issue :)

The BLUF is this: `StoredDict`, `StoredList`, and `StoredSet` are fundamentally not the same as their namesake counterparts (`dict,` `list`, `set`). If a charm author wishes to have a representation of the `Stored<X>` data in a concrete type, they can indeed do as suggested above and use the `dict()`, `list()` and `set()` constructors to get such a representation as a "point in time" snapshot of the data.

The various PRs that seek to address this (#572 and #596) will likely only add confusion down the line.

This is of course a trade-off, we could in a later version of Operator Framework make these types more congruent with standard Dicts/Lists/Sets, but then some of the work we do to commit changes in the background seamlessly could become much less efficient, and the most logical option at that point may be to place that responsibility on the charmers themselves by providing `load` and `save` methods for state, but I think that would be a net negative for charmers.

In the mean time, I think this very issue (and associated PRs) illustrate a need for an update to the framework documentation to make this point more clearly, and provide an example of serialising a snapshot of the data using the various constructors. If this continues to be a blocking issue, we could re-address this in a later version of the operator framework, but it would likely be a breaking change.
