### ISSUE TITLE
[RFE] How to manage restart with datastore/database applications in the operator?

### ISSUE THREAD

**Issue by phvalguima** [canonical/operator#530]
Generally, datastore/database applications demand a set of steps to be executed at a restart in order to avoid any potential data corruption.

Some examples:
https://docs.confluent.io/platform/current/kafka/post-deployment.html#rolling-restart
https://docs.mongodb.com/manual/tutorial/restart-sharded-cluster/

Generally, we need to define an order of restart based on the environment (e.g. if there is AZs on this deployment) or some application-specific, for example: restart the primary DB unit last.

Right now, the way I see it is for the leader unit to share its public SSH key with the peers and that key gets added to authorized_keys.
Once restart is needed, the leader ssh into each unit and restart their services one-by-one, following a pre-defined list.

I wonder if there is a more friendly way to do it within the operator.
I also have the impression this is going to be an issue with the k8s workloads with pebble.

**Comment by jameinel** [comment]
I feel like you could do this with the leader coordinating restarts of
applications via a peer relation, rather than needing to do so via SSH.

Specifically, when seeing the need, the lead unit could set a value in the
application data bag, indicating that a restart is needed. Depending on the
need, it could wait for all peer units to ACK that request, or it could
start by seeding a particular unit to restart. Probably this request needs
to include some sort of "EPOCH" counter, so that you can disambiguate new
vs stale data.

Then when the unit sees its name in the list of requested units to restart,
it can trigger the service restart as requested, and then put into its own
unit data bag on the peer relation. Probably you need the units to report
back the epoch, that they did trigger a restart, and have the opportunity
to say that something failed so the leader should abort. When the leader
sees the unit report back, it can then request the next unit restart.

I feel like a reasonably generic mechanism for coordinating an event
could be a charm library, and possibly in the future integrated into the
core operator framework.

You could feed it the peer relation name, and the name of the event to be
coordinated. It can then trigger events that you register to handle the
actual shutdown/restart of the service.

John
=:->

**Comment by rbarry82** [comment]
Something like a distributed mutex with an epoch could work for this. It's a valuable idea to get into the framework

**Comment by phvalguima** [comment]
Hi,

I've implemented this: https://github.com/phvalguima/charms.wand/blob/main/wand/contrib/coordinator.py
Which gives an interface to Coordinators we used to have in other charm libs. It does use a simple mutex as you've pointed out.

It does not have an Epoch. Worthy looking into it, but I've implemented this logic slightly differently on a recent charm.

What I've tried recently was a bool that says if the charm has ran recently a restart.

If a RestartEvent is issued, that bool is set to False

At processing of RestartEvent, if the bool is false, proceed: (1) run the restart; and (2) move the bool to True
Drop the RestartEvent if the bool is set to True.

That ensures I do not restart 3 times if I have something like:
```
ConfigChangedEvent ---> Emit RestartEvent(1)
ClusterChangeEvent ---> Emit RestartEvent(2)
RelationChangeEvent ---> Emit RestartEvent(3)

Run RestartEvent(1) ---> actually do the restart
Run RestartEvent(2) ---> ignored
Run RestartEvent(3) ---> ignored
```

**Comment by PietroPasotti** [comment]
This has been implemented by @pengale in https://github.com/pengale/charm-rolling-ops/blob/main/lib/charms/rolling_ops/v0/rollingops.py

I'll close this issue for now as we think this functionality is better served by remaining a standalone library. If someone thinks otherwise, we can open a new issue to argue for/against merging that functionality into core ops.
