### ISSUE TITLE
ip address is not available or incorrect on pebble_ready

### ISSUE THREAD

**Issue by sed-i** [canonical/operator#538]
(note: [cross-posted](https://github.com/canonical/pebble/issues/43))

## Environment
mickrok8s in multipass (4 cpus, 8G ram):
```
$ juju --version
2.9.0-ubuntu-amd64

$ microk8s kubectl version
Client Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.7-34+df7df22a741dbc", GitCommit:"df7df22a741dbc18dc3de3000b2393a1e3c32d36", GitTreeState:"clean", BuildDate:"2021-05-12T21:08:20Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}
```

## Description
When I deploy and then add 3 units ([alertmanager](https://github.com/sed-i/alertmanager-operator/tree/feature/pebblization), in my case), occasionally the ip address is not ready.
This does not happen if I manually (slowly) add the units one by one.

## Expected vs actual
Expected: An IP address is ready (and correct) by the time pebble_ready fires.
Actual: Occasionally, when adding multiple units at once, IP address is not available (or old) when queried from within pebble_ready.

### While adding 3 units
Very consistently, the following code assigns `None` to `bind_address`, for 1-2 of the added units:
```python
relation = self.model.get_relation("replicas")
bind_address = self.model.get_binding(relation).network.bind_address
```
Similarly, `unit-get` occasionally returns an empty string under the same circumstances:
```python
bind_address = check_output(["unit-get", "private-address"]).decode().strip()
```

### When restarting the machine
I have 4 units running, and then suddenly I `sudo reboot`. When the application (alertmanager) starts up, `bind_address` returns the IP address from the _previous_ boot.

**Comment by benhoyt** [comment]
Thanks. And sorry for the run-around but Operator Framework simply responds to events from Juju, so this is a bug in Juju, not OF. I've opened an issue there and copied your details across: https://bugs.launchpad.net/juju/+bug/1929364

**Comment by rbarry82** [comment]
There is a Juju bug here, in that a charm can end up in a state where Juju thinks it doesn't have a binding to a relation it provides, even after the charm code is running and it has an address (this is not related to Pebble).

The operating assumption with the Alertmanager charm's "funnel" of events is basically this:
* Some event comes through. `config-changed`, let's say, followed by another, like `pebble-ready`.
* Alertmanager funnels all events down to a common method. That method, near the top, checks whether it knows the address. This is done by `self.model.get_binding(...)`
* `ops.Model.get_binding` calls back to `ops.Model._bindings`, which is ultimately `BindingMapping` [here](https://github.com/canonical/operator/blob/3f20f80f5bea159ab1f3e1d2ba0dc3d97d668520/ops/model.py#L60). 
* If `BindingMapping` has a key, it's returned with an existing `Network` object (which has "actually" queried Juju once, at first invocation). If it doesn't have a key this is done then.
* If, at any other time, `get_binding` is called, this is returned. Through two layers of Caching `ops.Model._bindings -> BindingMapping [cached] -> Binding._network [cached]`

This is great for performance, since querying Juju can be expensive, but the open question here is whether or not this is intended, or whether `Binding._network` should actually have a method to call back out to Juju again to refresh the data for long-running Charm hooks.

If the Juju bug is squashed, this is a lesser issue, but worth raising anyway to see if we want to respond.

@jnsgruk @jameinel @petevg
