### ISSUE TITLE
Variadic methods can't be used as handlers

### ISSUE THREAD

**Issue by knkski** [canonical/operator#545]
I have charm that I have defined like this (cut out from larger example):

```py
class Operator(CharmBase):
    def __init__(self, *args):
        super().__init__(*args)
        self.framework.observe(self.on.install, self.main)

    def main(self, *args, **kwargs):
        ...
```

When deploying that charm, I get this error message:

```py
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-foo-0/charm/./src/charm.py", line 57, in <module>
    main(Operator)
  File "/var/lib/juju/agents/unit-foo-0/charm/venv/ops/main.py", line 390, in main
    charm = charm_class(framework)
  File "/var/lib/juju/agents/unit-foo-0/charm/./src/charm.py", line 24, in __init__
    self.framework.observe(event, self.main)
  File "/var/lib/juju/agents/unit-foo-0/charm/venv/ops/framework.py", line 686, in observe
    raise TypeError(
TypeError: Operator.main has extra required parameter
```

This is due to this line only checking to see if a method has arguments with defaults beyond the first one:

https://github.com/canonical/operator/blob/8e4946f1/ops/framework.py#L683

Which does not take into account the fact that `*args` and `**kwargs` can be unspecified similarly to args with defaults.

**Comment by benhoyt** [comment]
True, these should probably be allowed. But wouldn't it be better to have a more direct signaturer for the event handler? Seems odd to be calling a `main` function which can take a variable number of args as an event handler.

**Comment by knkski** [comment]
@benhoyt It would disallow writing code like this:

```py
class Operator(Charm):
    def __init__(self, *args):
        super().__init__(*args)
        self.framework.observe(self.on.foo, self.foo)
        self.framework.observe(self.on.bar, self.bar)
        self.framework.observe(self.on.install, self.main)

    def main(self, event, **kwargs):
        # Handle all events with common logic (and kwargs if it exists)
        ...

    def foo(self, event):
        kwargs = calculate_special_kwargs()
        self.main(event, **kwargs)

    def bar(self, event):
        kwargs = calculate_special_kwargs()
        self.main(event, **kwargs)
```

It would be possible to handle that all in the `main` function, but if the `kwargs = calculate_special_kwargs()` line is actually complex logic, it makes more sense to split that code out from `main`.

More generally, this seems to be something where Python is flexible enough that we can't really foresee ahead of time all use cases that a check like this might improperly block. Especially given that Python will already raise a `TypeError` if the method is called incorrectly, it doesn't seem like we should be making checks like this.

**Comment by johnsca** [comment]
I think the original intent of the check (as the one who implemented it, but I can't recall if it was specifically my idea) was mainly to provide a "cleaner" error, earlier in the life-cycle, than what you would get if you just let the observer be registered and Python raise the error naturally when the call fails.  The intent of the check is "at least accept the `event` param, and not have any other required args (positional or keyword)".  The check as implemented is definitely too simplistic, since it doesn't take into account [the `param.kind` value](https://docs.python.org/3/library/inspect.html#inspect.Parameter.kind) (specifically, the `VAR_POSITIONAL` or `VAR_KEYWORD` types).

We could improve the logic for the check to better match the intent, or we could just accept that Python already enforces this for us at runtime with an error that provides sufficient info to track down the problem and so remove the check entirely (which would be easier to "implement" and leave less code to maintain).

**Comment by knkski** [comment]
@jameinel: the crucial bit in my above example is that `main` can still act as a regular event handler (and in fact handles `self.on.install`).

Regardless of actual examples, I think the Really Good Reason is that we're doing extra work to do these checks, and they're rejecting valid code. It's not about *supporting* variadic targets, it's about not adding extra code to improperly *not* support them.

**Comment by jameinel** [comment]
So the extra code adds value in its own right, as it makes it harder to
misuse the interactions and get better debugging information. I would be ok
supporting variadic functions if it made a lot of sense to do so, but it
feels a bit wrong to have something that is sometimes a direct event
handler, and sometimes a function called separately by event handlers with
different arguments.
Yes, it is possible to do so, but it leads to hard to understand code,
because the same thing is used in very different ways.

**Comment by rbarry82** [comment]
I tend to agree with @jameinel here. We're not writing in a language which forbids variadic args and/or overloading, but it's much clearer to have a separate method (even a one line one) which takes the additional args and passes them if it needs it.
