### ISSUE TITLE
Permission denied on relation-get

### ISSUE THREAD

**Issue by heitorPB** [canonical/operator#551]
Today I saw the following error on the juju logs, and when running the command with `juju run` I get the same error:

```bash
$ juju run --unit slurmctld/leader "relation-get -r 71 - slurmdbd --app"
ERROR permission denied
```

Here are some logs:

```
machine-32: 17:16:27 DEBUG jujuc running hook tool "relation-list" for slurmctld/11-slurmd-relation-created-2533241742911058760
machine-32: 17:16:27 DEBUG jujuc running hook tool "relation-get" for slurmctld/11-slurmd-relation-created-2533241742911058760
machine-32: 17:16:27 DEBUG jujuc running hook tool "juju-log" for slurmctld/11-slurmd-relation-created-2533241742911058760
machine-32: 17:16:27 ERROR unit.slurmctld/11.juju-log slurmd:72: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-slurmctld-11/charm/venv/ops/model.py", line 1284, in _run
    result = run(args, **kwargs)
  File "/usr/lib64/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '('/var/lib/juju/tools/unit-slurmctld-11/relation-get', '-r', '71', '-', 'slurmdbd', '--app', '--format=json')' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./src/charm.py", line 415, in <module>
    main(SlurmctldCharm)
  File "/var/lib/juju/agents/unit-slurmctld-11/charm/venv/ops/main.py", line 404, in main
    framework.reemit()
  File "/var/lib/juju/agents/unit-slurmctld-11/charm/venv/ops/framework.py", line 732, in reemit
    self._reemit()
  File "/var/lib/juju/agents/unit-slurmctld-11/charm/venv/ops/framework.py", line 767, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-slurmctld-11/charm/src/interface_slurmd.py", line 63, in _on_relation_created
    if not self._charm.slurmdbd_info:
  File "./src/charm.py", line 85, in slurmdbd_info
    return self._slurmdbd.get_slurmdbd_info()
  File "/var/lib/juju/agents/unit-slurmctld-11/charm/src/interface_slurmdbd.py", line 111, in get_slurmdbd_info
    if app_data:
  File "/var/lib/juju/agents/unit-slurmctld-11/charm/venv/ops/model.py", line 394, in __len__
    return len(self._data)
  File "/var/lib/juju/agents/unit-slurmctld-11/charm/venv/ops/model.py", line 384, in _data
    data = self._lazy_data = self._load()
  File "/var/lib/juju/agents/unit-slurmctld-11/charm/venv/ops/model.py", line 748, in _load
    return self._backend.relation_get(self.relation.id, self._entity.name, self._is_app)
  File "/var/lib/juju/agents/unit-slurmctld-11/charm/venv/ops/model.py", line 1351, in relation_get
    return self._run(*args, return_output=True, use_json=True)
  File "/var/lib/juju/agents/unit-slurmctld-11/charm/venv/ops/model.py", line 1286, in _run
    raise ModelError(e.stderr)
ops.model.ModelError: b'ERROR permission denied\n'
unit-slurmctld-11: 17:16:27 ERROR juju.worker.uniter.operation hook "slurmd-relation-created" (via hook dispatching script: dispatch) failed: exit status 1
unit-slurmctld-11: 17:16:27 DEBUG juju.machinelock machine lock released for slurmctld/11 uniter (run relation-created (72; app: slurmd) hook)
```

The charm code that triggered this error is [here](https://github.com/omnivector-solutions/slurm-charms/blob/daemons-initilization-locks/charm-slurmctld/src/interface_slurmdbd.py#L111)

Juju controller 2.9.4, Juju client 2.9.4.

**Comment by heitorPB** [comment]
Just noticed something also (might be a different bug):

When deploying a bundle, sometimes the relations defined in the YAML file are not added to juju, i need to manually `juju relate foo bar` or run the `juju deploy  bundle` again.

THe bundle i'm using is [slum-bundle](https://github.com/omnivector-solutions/slurm-bundles)

**Comment by heitorPB** [comment]
The bug about the relations is reported in Launchpad as well: [1931632](https://bugs.launchpad.net/juju/+bug/1931632)

**Comment by jameinel** [comment]
I'm not sure where you are getting '-r 71' from. Looking at the final
statement:

unit-slurmctld-11: 17:16:27 DEBUG juju.machinelock machine lock
released for slurmctld/11 uniter (run relation-created (72; app:
slurmd) hook)

That looks like the relation is number 72 not 71.
Given that this is happening during 'reemit' that is when we are running
deferred hooks.

So I think this is a case where you related app A to app B and then the
charm deferred a relation-changed hook. But that relation got removed and
when we went to run a different relation-changed hook, it tried to read
information about the original relation, which no longer exists.

**Comment by heitorPB** [comment]
It makes sense. I was testing/debuging a charm and adding/removing units/relations a lot.

How should this be handled? Should I file a bug in Juju? Or this is specific for Operator?

**Comment by jameinel** [comment]
One piece is to try and figure out what *should* the behavior be. You have
asked to defer an event, which then can't happen because the context for
that event is gone.
I don't think this is a common case for production, but it certainly can
happen during testing.
There should be a way to notice that a deferred event is no longer valid
(certainly you get an exception about the relation not existing), and you
should have gotten other events like, relation-departed and relation-broken.
It feels a little weird for the framework to second guess your charm code
(your charm code has said 'send me this information later', but now that
information is invalid).
We *could* have the operator framework say "if a relation event is deferred
but I get a relation-departed/relation-broken for that event, remove the
deferred event". or possibly just 'refuse to defer'.

This also happens wrt if unit 5 triggers a relation-changed, but then unit
5 is removed, should you still have a deferred 'relation-changed (unit 5)'.

I think it really comes down to 'why are you deferring this event'.  Likely
you are deferring relation-changed because of some other event (like you
don't have valid config to support it yet). But there is nothing that says
config will become correct before the relation goes away.

What I'd rather see is a different pattern that doesn't involve deferring
events. Because what you want is something that says "I need both the
relation data *and* something else, so fire my code when both are true".

We talked about a Dependency pattern, where you could register multiple
things that must be true, and ways that those could go back to false again.
(eg, relation-joined => true, relation-departed => false).

**Comment by heitorPB** [comment]
>  What I'd rather see is a different pattern that doesn't involve deferring events. Because what you want is something that says "I need both the relation data *and* something else, so fire my code when both are true". 
>
> We talked about a Dependency pattern, where you could register multiple things that must be true, and ways that those could go back to false again. (eg, relation-joined => true, relation-departed => false).

This is exactly what we are dealing with. We have some internal flags and the code is similar to

```python
if not condition_1_satisfied:
    event.defer()

if not condition_2_satisfied:
    event.defer()

do_it()
```

**Comment by heitorPB** [comment]
The discussion about the Dependency pattern is public?  We have a use case for that, maybe we could give some feedback.

**Comment by jamesbeedy** [comment]
Geh ... I am getting some strange behavior around `relation-get` now.

```bash

$ juju status
Model    Controller           Cloud/Region         Version  SLA          Timestamp
default  localhost-localhost  localhost/localhost  2.9.4    unsupported  19:13:37Z

App              Version          Status  Scale  Charm            Store       Channel  Rev  OS      Message
percona-cluster  5.7.20           active      1  percona-cluster  charmstore  stable   293  ubuntu  Unit is ready
slurmctld        0.6.4-2-g11b...  active      1  slurmctld        local                  0  ubuntu  slurmctld available
slurmd           0.6.4-2-g11b...  error       2  slurmd           local                  1  ubuntu  hook failed: "slurmd-relation-created"
slurmdbd         0.6.4-2-g11b...  active      1  slurmdbd         local                  0  ubuntu  slurmdbd ready
slurmrestd       0.6.4-2-g11b...  active      1  slurmrestd       local                  0  ubuntu  slurmrestd available

Unit                Workload  Agent  Machine  Public address  Ports     Message
percona-cluster/0*  active    idle   0        10.19.68.195    3306/tcp  Unit is ready
slurmctld/0*        active    idle   1        10.19.68.36               slurmctld available
slurmd/0*           active    idle   2        10.19.68.192              slurmd available
slurmd/1            error     idle   5        10.19.68.240              hook failed: "slurmd-relation-created"
slurmdbd/0*         active    idle   3        10.19.68.117              slurmdbd ready
slurmrestd/0*       active    idle   4        10.19.68.144              slurmrestd available

Machine  State    DNS           Inst id        Series  AZ  Message
0        started  10.19.68.195  juju-a3736f-0  bionic      Running
1        started  10.19.68.36   juju-a3736f-1  focal       Running
2        started  10.19.68.192  juju-a3736f-2  focal       Running
3        started  10.19.68.117  juju-a3736f-3  focal       Running
4        started  10.19.68.144  juju-a3736f-4  focal       Running
5        started  10.19.68.240  juju-a3736f-5  focal       Running

(venv) bdx@rodent-02:~/allcode/github/omnivector/slurm-bundles$ juju run --unit slurmd/1 "/var/lib/juju/tools/unit-slurmd-1/relation-get -r 5 - slurmd --app --format=json"
ERROR permission denied
(venv) bdx@rodent-02:~/allcode/github/omnivector/slurm-bundles$ # now from the leader
(venv) bdx@rodent-02:~/allcode/github/omnivector/slurm-bundles$ juju run --unit slurmd/0 "/var/lib/juju/tools/unit-slurmd-0/relation-get -r 5 - slurmd --app --format=json"
{"partition-name":"juju-compute-JxBr","partition_info":"{\"partition_name\": \"juju-compute-JxBr\", \"partition_state\": \"UP\", \"partition_config\": \"\"}","partition_name":"juju-compute-JxBr"}

```


I was under the impression that all units of an application were able to read their own application level data on a relation. If this is correct possibly I am hitting a bug, otherwise I think I had the wrong understanding.

Any ideas here?

Thanks

**Comment by jameinel** [comment]
All units are not able to read their own application data. Eg:

foo <=> bar

foo/0 is the leader of foo
bar/1 is the leader of bar

app data for foo can be read by any unit of bar, and if any changes are
made by foo/0 then all units of bar will have a relation-data-changed event
triggered for the associated application data
app data for foo can only be read and set by foo/0 (or whoever the current
leader is)
if units of foo need to coordinate data, they should *not* do so by setting
app data that is being shared with bar, but by using a peer relation with
foo.
In a peer relation, all units of foo can read the app data (but only the
leader can set app data).

This is because app data in a relation to another app is not meant as a
communication channel with your own units. If it was, then any change to
application relation data would need to trigger relation-data-changed
*both* for all units of bar, but *also* for all units of foo (because they
need to be informed if something they read has been changed). But we
already have a way to have that time of alerting (a peer relation).

There are a lot of bits about making sure the right units have the right
data and ordering, etc that this solves. It also ensures that you won't
read stale data without being told when it is updated.

**Comment by jamesbeedy** [comment]
That makes total sense. Thank you for taking the time to spell it out.

**Comment by johnsca** [comment]
@jameinel I have an issue with that justification. I don't think that "coordinating with peer units" would be the typical reason a non-leader unit would want to read app level relation data set by its leader. Rather, the more common use-case would be to compare some aspect of the data sent in the request to something from the response.  For example, an interface that supports multiple requests might want to use the request ID to associate the response with the proper request, or the request might include a hash to notify both the provider that the request was updated and so that the non-leaders can tell when the updated request has been processed (by comparing the sent hash to one echoed back with the response).  Either of these use-cases would require mirroring some of that relation data on to the peer relation, keeping it associated with the other relation, and keeping it isolated from data mirrored from *other* relations.

**Comment by johnsca** [comment]
I reopened [lp:1911010](https://bugs.launchpad.net/juju/+bug/1911010) because I also ran into this and trying to work around it was not pleasant.

**Comment by jameinel** [comment]
I do believe that peers reading other peers information should be
considered a bug, not an intentional feature.
Specifically you don't have any indication if your information is out of
date nor signaling to inform you if it changes. So it only particularly
works if it never changes.

Can you describe the particular use case in more detail? Certainly we don't
want it to be burdensome, but we also want to make sure you have the
facilities to make things correct, not just work when things align just
right.

John
=:->

**Comment by rbarry82** [comment]
Let's continue this discussion on Launchpad. Strictly speaking, permissions on data bags are "below" the operator framework, and all we can do here is inherit Juju's permissions/behavior.

**Comment by jnsgruk** [comment]
Closing this issue for now, the discussion continues at: https://bugs.launchpad.net/juju/+bug/1911010. I think this is not likely to be fixed by OF, but rather in Juju. Thanks for the feedback! :)
