### ISSUE TITLE
Confusing / inconsistent errors from interaction between Pebble and Juju events and handlers

### ISSUE THREAD

**Issue by johnsca** [canonical/operator#553]
I've frequently seen charm authors who are new to the sidecar pattern write something along the lines of this in their charm:

```python
class MyCharm(CharmBase):
    def __init__(self, *args):
        super().__init__(*args)
        self.framework.observe(self.on.mycharm_pebble_ready, self._create_layer)
        self.framework.observe(self.on.config_changed, self._restart_service)

    def _create_layer(self, event):
        container = self.unit.get_container("mycharm")
        container.add_layer("mycharm", {"services": {"mycharm": {...}}})
        container.autostart()

    def _restart_service(self, event):
        container = self.unit.get_container("mycharm")
        # presumably introspect and / or update the service, then...
        container.stop("mycharm")
        container.start("mycharm")
```

This seems like a straightforward and reasonable way for someone to start out approaching this, but can result in any one of 5 different outcomes:

  * It might work fine.  Depending on timing and how the `_restart_service` handler does or doesn't implement updating the service based on config changes, this might deploy and run fine, at least most of the time.

  * It might raise `ops.pebble.ConnectionError`.  Depending on how quickly Pebble becomes ready to accept connections, it might fail trying to talk to Pebble at all. Worse, this could be an intermittent failure. Additionally, this won't ever happen in unit tests because the `_TestingPebbleClient` is always ready immediately.

  * It might raise `RuntimeError: 400 Bad Request: service "mycharm" does not exist`. This is somewhat related to #514 but is slightly different and might be specific to the `_TestingPebbleClient`.

  * It might raise `ops.pebble.APIError: 400 Bad Request: service "mycharm" does not exist`. A charm that raised the previous `RuntimeError` during unit tests would most likely raise this during an actual deployment.

  * It might raise `ops.model.ModelError: service 'mycharm' not found`. If the `_restart_service` handler does an explicit `container.get_service("mycharm")`, then it will get this rather than either of the previous two errors, unless it calls `container.add_layer(layer_name, layer_definition, combine=True)` first.

It would at least be good to ensure that all of the latter 3 cases result in a single `ops.pebble.UnknownServiceError` or something, but I've found that new charmers will still be confused as to why the service isn't recognized despite them having defined it during the `pebble-ready` event. Maybe the additional message on the `UnknownServiceError` can include a hint such as `(typically due to referencing a service before add_layer is called)`.

It would also be good to make the testing harness always raise `ConnectionError` until the `pebble-ready` event is triggered, to force charm authors to consider that possibility.

A `container.restart(service)` helper would be nice, as well.

**Comment by evilnick** [comment]
I personally hit the second case, which I was able to work around thanks to some comments on the Charmhub chat, and the last case, which was much harder to diagnose/understand at first

**Comment by jameinel** [comment]
So for runtime environment, there is always the possibility that your
previous container got OOM killed and got rescheduled, and thus even though
we have given you pebble_ready, pebble is not actually running at this
point in time (and shortly we would expect another pebble_ready event.)
So whatever solution we implement needs to guide charmers towards that
eventuality. (Some people have done things like record in stored state
whether pebble is currently available, but that's not really long term
stable solution.)

Unifying the types of errors for Pebble-not-available definitely seems
useful. And then the pattern might become:

def _on_event(self, event):
  c = self.model.get_container('foo')
  try:
    c.pebble.add_layer(..., merge=True)
  except PebbleNotReady:
    event.defer()

or we could try to be more active with:
def _on_event(self, event):
  c = self.model.get_container('foo')
  if not c.pebble.is_ready():
    event.defer()
...

When a container gets rescheduled, Pebble loses all of its state, so if you
did have

def _on_install(self, event):
  ...
  c.pebble.add_layer('foo', {'stuff'})

you can't actually assume:

def _on_relation_changed(self, event):
  c.pebble.stop('foo')

Even though you *did* tell a pebble about 'foo' in the past, you may not be
talking to the same pebble in the future. K8s reserves the rights to
restart containers whenever it wants, and Pebble doesn't use a PVC to
maintain its state.
Juju ensures that if this happens we trigger another pebble-ready event.

This does push charmers towards just doing everything in pebble_ready, so
figuring out a better long term strategy is useful.

**Comment by johnsca** [comment]
> So whatever solution we implement needs to guide charmers towards that eventuality.

Agreed. And I think we've started down that path by encouraging handling of `ConnectionError` I just don't think that is sufficient. I also think we should enforce this kind of defensive programming by having the testing harness present as close to the pathological case as is reasonable, by default (hence having it raise `ConnectionError` or `PebbleNotReady` until during the first `pebble-ready` event).

> (Some people have done things like record in stored state whether pebble is currently available, but that's not really long term stable solution.)

100% agree.  Trying to cache Pebble status is doomed to failure.

> Unifying the types of errors for Pebble-not-available definitely seems useful. And then the pattern might become: ...

I think I actually prefer the exception pattern, because it better reflects the fact that, as an external resource, any given Pebble interaction could fail, even if a previous one succeeded.  And that should always be handled gracefully.

> Even though you *did* tell a pebble about 'foo' in the past, you may not be talking to the same pebble in the future.

Agreed, and it's also the case that in relation or config hooks, you're probably dealing with a data change anyway, so there's a good chance that you'll want to update the layer definition and restart if anything changed. In fact, that seems like the default pattern, so maybe we should make the framework provide an easy way to do that.  Something like `container.apply_layer(...)` which is like `container.add_layer(..., combine=True)` plus `container.auto_restart()`.

**Comment by rbarry82** [comment]
The intention here will be to add a property to the container (for when you are building layers or checking layers) which can implicitly tell you whether Pebble is *currently* ready as a guard, with meaningful error logging instead of a spray of exceptions in the log when something goes wrong.

**Comment by johnsca** [comment]
Hrm.  Caching (or even querying) the state of an external service would leave a race condition which could still lead to exceptions being raised, so I think we will still have need for a cleanly defined `PebbleNotReady` exception type. Also, the testing harness should probably have a flag / method to control whether it behaves as if Pebble is ready or not, rather than just driving it based on whether it has emitted the `pebble-ready` event as I originally suggested, to allow for testing the case where Pebble becomes unready unexpectedly.

**Comment by rbarry82** [comment]
Yes, we still have the need for a `PebbleNotReady` exception type, but the goal would be to catch that in the operator framework itself rather than relying on Charm authors looking for `FileNotFoundError` or `URLError` or `PebbleNotReady` (depending on how unlucky they are in the Pebble execution cycle) in the middle of their charm code. There is always the possibility, of course, that Pebble will become unready at some point in the middle of an operation, but at least we can reduce this and catch bugs as they come up.

Instead of driving it based on whether or not it has emitted `pebble_ready` and setting a flag (which may be meaningless in the charm itself), imagine something like:

```
if container.pebble.ready:
   # ...
```

Right now, `ops.model.Container` [assumes](https://github.com/canonical/operator/blob/72fd89cb92750a4f1674818bf8d10d43e9f85f5e/ops/model.py#L1027) that it will be able to [instantiate a Pebble client](https://github.com/canonical/operator/blob/72fd89cb92750a4f1674818bf8d10d43e9f85f5e/ops/model.py#L1542) if one is not already ready, and refer to that later via `self._pebble`.

A relatively small decorator which checks the validity of these assumptions when invoked at least provides a first-pass line of defense against users, and catches the vast majority of cases which are not "I'm going to have one large method which checks to see whether Pebble is ready then does a bunch of pushes and other manipulation, during which time the unit may be stopped and I'll get an exception", and that's something we can mitigate with good docs about what well-written charms look like.

**Comment by petevg** [comment]
Agree that we should try to avoid exposing the exception to the operator framework, mainly because exceptions should be reserved for exceptional situations -- this is something routine that we should handle in a more routine fashion.

The underlying design of Juju is to just let a hook fail with a non zero exit code if there's a timing issue or similar with running it. I like the rbarry82's design above, though I'd like to see the typical pattern look like:

```
def mycoolfunc():
    if not container.pebbly.ready:
        return # Or do something like 'raise WaitingForInfra'
    ...

```

I think that's most in keeping with Python best practices, while handling the vagaries of an asynchronous system.

**Comment by jameinel** [comment]
It is an interesting problem.
Raising an exception will cause the hook to exit non-zero and Juju will
rerun the hook (and not progress the model further).
deferring the event will cause Juju to wait until the next event before the
OF decides it wants to run the deferred event.

I wonder if raising PebbleNotReady but having the OF turn that into a
single 'pebble not yet ready' message (rather than a scary traceback) might
be a good compromise. I'm not sure, because 'juju status' will still show
as error, which isn't genuine.
And with a defer(), there is a strong expectation that pebble_ready should
fire soon after, which will catch the defer.

But having a pattern of

def _on_foo(self, event):
  if not self.container['blah'].pebble.ready:
    event.defer()
    return

might be a reasonable pattern to recommend. And has that check in an
obvious place

**Comment by johnsca** [comment]
It seems like whether it's a guard clause or a try / except, we need to encourage *some* pattern for handling this case. Also, [exceptions aren't as verboten in Python as they are in other languages](https://softwareengineering.stackexchange.com/questions/351110/are-exceptions-for-flow-control-best-practice-in-python), and trying to manage [exogenous exceptions](https://ericlippert.com/2008/09/10/vexing-exceptions/) with guard clauses does leave gaps. There was an example from the Python docs specifically around handling of file access errors where it touched on this, but I can't seem to find it.

**Comment by rbarry82** [comment]
I definitely agree that exceptions aren't as verboten as other languages, and they're a meaningful/common way to handle flow control, just not that we should be dumping those exceptions to the juju logs. It's a 50/50 thing for me. Looking at nginx_errors to see if anything is actually going wrong can be frustrating, but I'm also not stuck looking at the logs for some application wondering whether something is broken when everything is fine.

Does juju have a different mechanism to check here? Can we return `None` or `False`? `event.defer()` isn't always an intuitive pattern either -- defer until when? Why not wait for another rerun? Explicit is better than implicit, but lowering the burden on new Charm authors is my driver here, instead of "here's another antipattern you should follow as best practice"

**Comment by johnsca** [comment]
Ok, so I also agree that these errors don't belong in the Juju log, but more because I think it will be incumbent on the charm author to handle them.  If we encourage them to handle it using guard clauses, I think that will be fine in most cases, though there's a small chance of a race condition. However, in either case, if they don't do the check, something will fail that they don't expect and an error will end up in the log. Ideally, that error quickly and easily points them to what they need to do to fix it, and I think that a stack-trace with a `PebbleNotReady` error at the bottom makes it very clear what went wrong and how to fix it. And, in the end, I think the "I forgot to check it" case is probably going to end up with a `PebbleNotReady` or some other exception being thrown anyway from whatever unguarded code tries and fails to talk to Pebble.
