### ISSUE TITLE
[storage] Expand StorageEvent to provide details of disk by default

### ISSUE THREAD

**Issue by phvalguima** [canonical/operator#571]
Hi,

Supposing we are running a configuration such as:

```
storage:
  data:
    type: block
    multiple:
      range: 0- <<<--- I may have several volumes here
```

When I get a storage detached, I will need to treat the case where among several disks, one is going away under that same storage_name ("data").
Currently, there is no way via operator framework to discover which disk does it relates to. 
The model does provide a Storage class, but there is no way to retrieve that information and get an object pointing to the detaching disk.

I've raised with Juju directly, on the following discussion: https://bugs.launchpad.net/juju/+bug/1936876

So, we can recover which disk is being removed if one runs: ```storage-get``` only, without arguments.

In my view, storage-related events should run that storage-get at __init__ and store storage_id, name and location info.

We should have instead something similar to:

```
class StorageEvent(HookEvent):

    def __init__(self):
         self._storage_json = self._run('storage-get', return_output=True, use_json=True)
         
```

**Comment by jnsgruk** [comment]
This is interesting. @rbarry82 I think we could consider modifying the [StorageEvent](https://github.com/canonical/operator/blob/b1a8fffc053fbbdaf43b826e78c220bfdae4c8fe/ops/charm.py#L420) so that it carries a [`Storage`](https://github.com/canonical/operator/blob/b1a8fffc053fbbdaf43b826e78c220bfdae4c8fe/ops/model.py#L1015) object, similar to how relation events carry information about the relation that's affected.

Needs some work to confirm that running `storage-get` does indeed give us the required information in all cases, but seems like a relatively simple one to implement.

**Comment by rbarry82** [comment]
I'll confirm the output from Juju. If everything is there, this should be simple to implement
