### ISSUE TITLE
improve [Layer -> Plan -> Service] consistency

### ISSUE THREAD

**Issue by sed-i** [canonical/operator#594]
It seems that:
1. `ops.pebble.Plan` constructor should also take `dict`.
1. `ops.pebble.Service` constructor should also take `str` for the `raw` arg.
1. `ops.pebble.Plan` is redundant because both `Layer.services` and `Plan.services` is the exact same `dict[str, Service]`, and `Layer` doesn't use `Plan` internally.

```python
d = {                                        # Layer (raw: str | dict)
    'summary': 'Sum Mary',                   # │
    'description': 'The quick brown fox!',   # │
    'services': {                            # └─ Plan (raw: str)
        'foo': {                             #    ├─ Service
            'summary': 'Foo',                #    │
            'command': 'echo foo',           #    │
        },                                   #    │
        'bar': {                             #    └─ Service (name: str, raw: dict)
            'summary': 'Bar',                #
            'command': 'echo bar',           #
        },                                   #
    }                                        #
}                                            #
```

**Comment by rbarry82** [comment]
Before we worry about constructors which are almost entirely used internally by `ops.Pebble` with `Layer` as the entrypoint for charmers (most charms don't have a great use case for an isolated `Plan` or `Service` which isn't attached to a `Layer`), what's the user story for this change?

**Comment by sed-i** [comment]
The 3 items I listed are not necessarily change requests, they are just examples of inconsistency in the Layer->Plan->Service hierarchy.

> Layer as the entrypoint for charmers

The Layer->Plan->Service hierarchy is not well understood and most charms that I encountered use Service or Plan directly, without Layer. One possible reason is that Layer.services and Plan.services is the exact same thing, and Layer.plan(s) does not exist.

**Comment by jnsgruk** [comment]
I think there may be some confusion here:

- A Pebble Plan is the sum of zero or more layers, that is to say, it is the result of combining multiple layers according to how they were specified and how the `override` element was stated
- There shouldn't be any need for `ops.pebble.Plan` to take a `dict` in it's constructor, given the above. In general, charm authors will not be constructing `Plan`s, they construct `Layer`s which the relevant Pebble will combine into a `Plan`

I think that might address your concern as to why `Layer.plan` does not exist, it does not exist, because a `Layer` never includes a `Plan`.

Let me know if you still feel this issue should stay open given these clarifications?

**Comment by sed-i** [comment]
Thank you for the clarification! Closing.
