### ISSUE TITLE
OF should gracefully handle blank application names in relation-broken hooks

### ISSUE THREAD

**Issue by pengale** [canonical/operator#693]
See the discussion here: https://bugs.launchpad.net/juju/+bug/1960934

In a relation-broken hook, Juju does not set JUJU_REMOTE_APP. This is Working as Intended for Juju, but it raises an exception in the framework, when iterating through relations.

We need to refactor so that we handle the empty value without throwing the exception.

**Comment by jameinel** [comment]
I could be convinced to set JUJU_REMOTE_APP but you'd still want to handle
the case in OF for versions of Juju that don't have that set.

**Comment by claudiubelu** [comment]
I want to mention that I've encountered this type of errors before [1], and that they still happen for the nginx-ingress-integrator charm when a related application is removed (the charm iterates over its relations in order to establish what Kubernetes Services and Ingress Resources need to be created / removed).

[1] https://github.com/finos/legend-juju-gitlab-integrator/pull/6

**Comment by rwcarlsen** [comment]
]If someone is e.g. using the remote app name to access relation data (`relation.data[relation.app].get(...)`), what should happen?  Should we just have `relation.data[relation.app]` return an empty dictionary and log an error?  Or something else...

**Comment by rwcarlsen** [comment]
According to the traceback (why does python reverse the compound word convention from c/c++?) in the linked juju issue, and `relation.data[relation.app].get(...)` is failing in the `.get(...)` call.  And the `relation-get` hook is failing with an empty app name.  This means that relation.app is an existing instance with an empty app name.  I've traced this issue to https://github.com/canonical/operator/blob/e3bc30bf8491716d33c8bb6061eb63bd8306ca1d/ops/model.py#L1642 where we end up returning an empty string instead of None.  The calling code for this function only checks for None (not empty string) as a special case.  I would argue that this is a bug that we can fix easily.  However, this doesn't really resolve the question I asked above - users will instead just get a keyerror for e.g. `relation.data[relation.app]`  because now relation.app will be None.  If the actual relation data still does exist and `relation-get` calls can succeed, how can ops get access to the (gone?) remote app's name?
