### ISSUE TITLE
Make test helpers for simulating common scenarios

### ISSUE THREAD

**Issue by rwcarlsen** [canonical/operator#696]
We already have `harness.begin_with_initial_hooks()` which simulates a "normal" sequence of bootup events for a charm in testing.  But there are other important sequences of hooks/state-change that are important for charms to support - e.g. is `container.can_connect` true or false (#691), relation join events coming in different orders, when does pebble-ready fire w.r.t. install, etc.  This could also be potentially related to a medium+ term solution for resolving other issues such as #678 and https://github.com/canonical/operator/issues/456.

It should be possible to come up with a nice, extensible way to allow charmdevs to select one or more options from a grab-bag of event/state sequence scenarios, tweak them to their own liking and fire them off just like `begin_with_initial_hooks`.

**Comment by jnsgruk** [comment]
So I think this is an interesting direction, my only early comment is on `get_storage_events(shuffle=True)`. I'm not sure how useful this is - is it valuable to have events sent to the charm in a sequence that the controller never would? It might be more sensible to have presets that get a set of events that "simulate a charm being related" for example :)

**Comment by PietroPasotti** [comment]
I based that suggestion on the fact that `begin_with_initial_hooks` at the moment has a bunch of `random.shuffle()`s in place to discourage the harness user from relying on the event ordering; although if you ask me this might lead to unpredictable and hard-to-debug failures if there is in fact some bug in the charm.
So I'm in favour of removing that.

**Comment by jnsgruk** [comment]
Oh interesting - well we could certainly take that into consideration. I suspect @jameinel had something to do with that initial implementation and it's very possible that I've missed something ;-)

**Comment by jameinel** [comment]
I think the idea is sound, the issues are more about what can/cannot be shuffled.
In the above example there are a couple pieces that aren't valid, eg:
```
                harness.events.start,
                harness.events.install,
                harness.events.get_pebble_ready_event('container_name'),
                harness.events.get_action_event('action_name', 'argument 1', 2)
```
(install is always before start)
And
```
        for evt_sequence in itertools.permutations([
                events.start,
                events.stop,
                events.get_action_event('my_action', 'foo'),
                events.get_action_event('other_action', 'bar'),
                events.leader_elected
            ]):
```
It would be very weird to get stop before start, or any action after stop without the corresponding start, etc.

I certainly like the idea of providing an amount of "these are the things that are going to run, and what can be parallel and must be linear is properly respected".
The shuffles are certainly explicit (relation_created is always run at that particular time, but no given relation has precedence over another one).
And in that, I think the Harness and OF can be very valuable to help users because it can provide the real constraint/ordering that a user may not understand when setting things up.


We had discussed this a bit on a call, and I do really like the idea of having Fixtures/Scenarios that would be generally applicable across charms, or at least ways to help them define common patterns for their charm. (A lot of things are specific about the name of the relation, or what relations exist/don't exist, etc.)

**Comment by mmanciop** [comment]
Looking back at the kind of bugs I have encountered, I think we should have facilities in the harness to simulate (and nudge very hard charmers to test):

1) Pod churns with and without existing relations (and joined units)
1) Upgrade processes (A) with no changes in container image (so, mostly no pod churn) and (B) with pod churn (see (1))

**Comment by sed-i** [comment]
It would be nice to have a `harness.upgrade()` to emit all the events expected in an upgrade: stop, pebble-ready, etc., similar to `begin_with_initial_hooks`. This is useful even if "upgrading" to the same charm.

A fuller solution could look as follows:
```python
self.harness = Harness(OldDummyCharm)  # or maybe store past revisions of `charm.py` for testing purposes
# ...
self.harness.upgrade(MyCharm)
```

**Comment by rwcarlsen** [comment]
@jameinel makes an important point.  The constraints on allowed shufflings make things more tricky.  Another important point is that there are state changes within the harness that need to be part of the sequence - i.e. can_connect, that actual config mods for config changed events, etc.  I think this sort of scenario-driven testing, at least initially, should be implemented disconnected from the test harness and ops code initially - and be used to set up and drive the harness.  This will prevent us from prematurely committing to a particular approach/api as well as help identify holes in test-harness functionality (e.g. the ability to set up networking topologies/config).

**Comment by PietroPasotti** [comment]
Worked out something which might help or inspire whoever works this out eventually

https://discourse.charmhub.io/t/on-fuzzing-a-charms-lifecycle/5821

https://github.com/PietroPasotti/charm-events/blob/main/simulator.py

**Comment by benhoyt** [comment]
I think this is an interesting idea, but we'd need a concrete proposal to discuss further. I also think the work @PietroPasotti is doing with ops-scenario helps solve this in a more explicit way. Going to close this issue for now, but we can always open issues for specific event sequence functions as they come up, instead of this more vague/general issue.
