### ISSUE TITLE
Even more graceful service restart?

### ISSUE THREAD

**Issue by sed-i** [canonical/operator#701]
`container.restart` is pretty good, but I consistently find myself writing a wrapper for it that tries to restart more carefully and raises only one kind of an exception if fails for whatever reason.

Could/should something like this be absorbed by OF? 

```python
    def _restart_service(self, service: str) -> None:
        """Helper function for restarting the underlying service."""
        logger.info("Restarting service %s", service)

        if not self.container.can_connect():
            raise ServiceRestartError("Cannot (re)start service: container is not ready.")

        # Check if service exists, to avoid ModelError from being raised when the service does
        # not yet exist
        if service not in self.container.get_plan().services:
            raise ServiceRestartError("Cannot (re)start service: service does not (yet) exist.")

        self.container.restart(service)

        service_running = (
            service := self.container.get_service(self._service_name)
        ) and service.is_running()
        if not service_running:
            raise ServiceRestartError("Attempted to restart service but it is not running")
```

**Comment by benhoyt** [comment]
Just catching up on a few old issues: can you link me to charm(s) where you've used this or a similar function? Breaking it down, it seems to me that:

1) The charm should probably handle `can_connect` more generally, like what some charms do with a connectivity check at the start of each hook and handle it gracefully.
2) The "check if service exists" step seems like it's a coding bug and should raise an exception loudly on restart (ModelError), so that's okay to leave out, right?
3) The "service running" check seems unnecessary to me. `container.restart()` already waits for the change to complete, which means ensuring the command has started successfully and waiting for 1 second to ensure it doesn't exit quickly.

Am I missing some real-world issues your function is catching?

**Comment by sed-i** [comment]
The function was constructed incrementally over time and in the past :) in alertmanager-k8s.

(1) and (2) are there as an outcome of the "common exit hook" pattern: `_restart_services` could have been called during the startup sequence before (1) pebble-ready and before (2) the layer was pushed.

You're right about (3).

Closing.
