### ISSUE TITLE
Exposure of `JUJU_DEPARTING_UNIT`

### ISSUE THREAD

**Issue by MiaAltieri** [canonical/operator#707]
Hi team! Would it be possible to expose `JUJU_DEPARTING_UNIT`? Right now I am accessing it via `os.environ`. 

The motivation is that when a unit is getting removed I don't want the unit that is departing from the application to set any reconfigurations. A simple check for if the current unit is the departing unit seems to solve this. 😄

**Comment by balbirthomas** [comment]
Thanks for creating this issue @MiaAltieri . If it is of any help to `ops` developers the use case here is to handle the situation when the departing unit is a leader unit. The leader unit needs to know not to try and reconfigure its charm because it is a departing unit. The departing leader unit can safely ignore the `RelationDepartedEvent` since when a new leader is elected, the new leader can reconfigure its charm in either the leadership event or the relation events.

**Comment by jameinel** [comment]
Why not have the unit remove itself from the replica set as a way to play
nicely during clean shutdown? (You still need to know about
JUJU_DEPARTING_UNIT so that you don't try to remove the other units from
the replica set.)
