### ISSUE TITLE
refactor Event.framework: externally managed state 

### ISSUE THREAD

**Issue by PietroPasotti** [canonical/operator#719]
HookEvent has a ‘framework’ attr which is managed externally and makes for hard to understand and debug code. We should refactor the flow and make it better.

**Comment by pengale** [comment]
I've been thinking about this (and also reading a lot of code).

In an OF charm, we usually initialize one instance of the Framework class. It contains, among other things, a representation of the Juju model. Charms are typically built around a single subclass of CharmBase -- call it TheCharm. This object contains event handlers, as well as an "on" object to attach those event handlers to. This is achieved by requiring charm authors to include the following lines in their charm.py:

```python
from ops.main import main
# ...
# ...
# ...
if __name__ == '__main__':
    main(TheCharm)
```

The main routine in `ops/main.py` initializes the Framework object, then initializes TheCharm, passing the framework object in as an argument. All the of the magic -- loading and caching the hookenv, registering event handlers, etc. -- happens as a side effect of that invocation of the Operator Framework's main routine. The interpreter executes this code right up front, around import time.

This is maybe a little clever, but it works well, and a lot of code in the Operator Framework is built around that flow.

The issue is that we then run into complexity when writing libraries and other objects that want to have a say in how events are handled. A frequent pattern (one suggested by the docs) is to pass the instance of TheCharm into a constructor, using `super` to "subclass" it. This invokes the logic in ops.framework.Object to attach the framework instance, and also drop in a `.model` helper. You can then use your new object just as you would your charm object, in terms of getting data from the model.

The pattern works, but it is a little bit counterintuitive. A charm author might wonder why they are passing an instantiated CharmBase object to `super` in a helper class's init. I didn't really understand everything about the way things are connected until I started writing this, and started actually thinking through what it would take the refactor the code.

It's a little bit tempting to suggest that we modify the ops.framework.Object metaclass to keep a global reference to a single Framework instance. Currently, Object simply attaches the framework (if any) from an object's parent to the new object, and it wouldn't be too terrible to turn that into a lazy load of a global framework instance. The downside is the same as that of any other implementation of the Singleton pattern: in test fixtures, we have to explicitly clean up the single framework instance, rather than just spinning up a fresh one.

What do other folks think?

**Comment by rwcarlsen** [comment]
I'm not convinced (yet) that a straight up singleton is the best approach, but I'm definitely not a huge fan of the status quo.  I actually don't mind passing in a charm instance to charm library class constructors.  But instead of subclassing using super, I prefer to just store the charm instance as a member and access everything (e.g. framework) through the charm member.

**Comment by pengale** [comment]
@rwcarlsen the invocation to super does a few more things, like map events to a handler.

It's actually pretty cool, in that you can define completely separate classes with completely separate sets of events if you want to. I had a lot of choices in exactly how I implemented that RollingOps library, and the flexibility felt nice. That doesn't mean that it wouldn't feel better to be able to just reference the Framework without a bunch of arg passing.

One point of caution: the timing of the instantiation of the Framework and CharmBase child objects is pretty important. ops.main.main is not a pretty routine, but it is careful about how it sets things up, then .commits and .closes them (the last two are framework calls that live in a in a try - finally block).

The way things are wired and passed currently, that timing is guaranteed. If we moved toward a singleton-ish thing that could be imported, there are cases where charm authors might try to access the Framework before it is ready, which can mess with some of the contracts we make about how we order events, and when we commit things to disk.

**Comment by pengale** [comment]
Heh, the pseudo singleton nature of some of this stuff was already a problem in the testing harness: https://github.com/canonical/operator/blob/45e1e5a9e4e99492d09423436b8378f955c4f0a3/ops/testing.py#L131

(Ran into this while trying to write a RollingOpsManager with a completely separate `on` object. It's a non trivial task to test it.)

**Comment by jameinel** [comment]
I would caution that I've almost always regretted using the singleton
pattern. It makes testing harder is relatively obvious, but as you say
"what is the actual lifetime of the singleton" is another one. And
libraries having singletons is a huge host of that sort of confusion. (It
is slightly better at the app level, but then the library provides a way
for the app to create/teardown the singleton but doesn't manage it by
itself.)
