### ISSUE TITLE
Event and BoundEvent classes should be changed to become class decorators 

### ISSUE THREAD

**Issue by timClicks** [canonical/operator#74]
`Event` and `BoundEvent` are represented as classes, but users are being told to use them as class decorators:

https://github.com/canonical/operator/blob/a14375b91b151c7ca6b4582c4c919f763edfa7af/op/framework.py#L115-L125

It would be more Pythonic to use actual class decorators, rather than classes divorced from the class hierarchy.

**Comment by johnsca** [comment]
I still have the feeling that there ought to be a way to make the descriptor / binding happen without the need to repeat the `Event()` wrapping (even if done as a class decorator).  I mean, if it can be done as a class decorator, it seems like it could be done with a metaclass as well and mean that the syntax could be reduced to:

```python
class CharmEvents(EventsBase):  # I'd also prefer EventsContainer or something
    install = InstallEvent
```

and have everything else work the same.  However, there was thinking that not having the explicit distinction between the descriptor wrapper and the event type itself could lead to confusion.

**Comment by timClicks** [comment]
A declarative API like that would be much nicer.

**Comment by niemeyer** [comment]
> Event and BoundEvent are represented as classes, but users are being told to use them as class decorators:
(...)
> It would be more Pythonic to use actual class decorators, rather than classes divorced from the class hierarchy.

We're using actual class decorators, otherwise it wouldn't work as an actual class decorator. :)

_BoundEvent_ is an implementation detail. People are not told to use it in any way.

I'm guessing what you're trying to suggest is making events become class decorators so that people don't need to see the word _Event(...)_ in the code, as Cory suggests above? The thing is: event types are supposed to be used as events and have an event lifecycle, while the _Event_ instance is trivial convenience type to make usage nice and clean. The _decorator_ has attributes, methods, and behavior which make sense for the decorator, while the emitted instance is custom and carries logic related to whatever business it's serving. Just smashing the two ideas together doesn't sound like a path towards simplicity or clarity, but the opposite.

That said, this is my feeling. If I'm missing some obvious way to make this nicer in a different way, by all means the PR list is on the next tab. :-)

**Comment by timClicks** [comment]
> I'm guessing what you're trying to suggest is making events become class decorators so that people don't need to see the word Event(...) in the code, as Cory suggests above? 

That's right. The current syntax is really cumbersome. It is unclear to me how these classes are supposed to be composed.

> The thing is: event types are supposed to be used as events and have an event lifecycle, while the Event instance is trivial convenience type to make usage nice and clean. 

That's the goal we both share. Which is why I recommend examining design before this decision sets like concrete. Are there any other libraries in the Python ecosystem that use similar conventions? @johnsca had a really good point about re-using Django's model syntax that's been incorporated into the standard library as dataclasses. 

This approach of having a class called base (EventBase) that isn't inherited by other classes (Event) that end up making use of the base class via implicit dynamic dispatch doesn't feel "nice and clean" to me. 

> BoundEvent is an implementation detail. People are not told to use it in any way.

This isn't apparent from anything I've been able to read (and I've looked). The class isn't protected in any sense by Python's conventions. Could you point to me where this is documented?

**Comment by niemeyer** [comment]
Okay, will keep that in mind and see if we can improve somehow.

If you have an actual suggestion, please do let us know.

**Comment by niemeyer** [comment]
We've addressed this on https://github.com/canonical/operator/pull/78 and https://github.com/canonical/operator/pull/91.
