### ISSUE TITLE
Should `observe` be able to take MagicMock?

### ISSUE THREAD

**Issue by sed-i** [canonical/operator#783]
Currently, `observe` [raises](https://github.com/canonical/operator/blob/75fc1073019688318db18f1c6c77639dba633e94/ops/framework.py#L710) if the observer is not `MethodType`:

```python
def observe(...):
    # ...
    if not isinstance(observer, types.MethodType):
        # ...
        raise RuntimeError(...)
```

so mocking an observer doesn't work:

```
RuntimeError: Framework.observe requires a method as third parameter,
got <MagicMock name='_patch' id='139627421371696'>
```

Not sure if this is a bug or a feature.

**Comment by rwcarlsen** [comment]
The only use case I can think of for directly observing a mock is to accomplish testing ops itself.  So it seems unnecessary for charm dev.  If you have run into any use cases I'd be very interested to hear more.

**Comment by PietroPasotti** [comment]
It's a slightly different use case (it checks whether an event was emitted), but testing that the method was called is out of scope as it's a matter of trusting that ops does its part.

**Comment by sed-i** [comment]
Another use case is mocking an entire charm lib that also emits custom events.

The unit test is mocking the entire charm lib:

```python
    @patch("charm.KubernetesComputeResourcesPatch")
    def test_whatever(self, *unused):
        # ...
```

while the charm code registers a custom event:

```python
self.resources_patch = KubernetesComputeResourcesPatch(self, ...)
self.framework.observe(self.resources_patch.on.patch_failed, self._on_k8s_patch_failed)
```

which results in:

```
RuntimeError: Framework.observe requires a BoundEvent as second parameter, 
got <MagicMock name='KubernetesComputeResourcesPatch().on.patch_failed' id='140578321486256'>
```

**Comment by jameinel** [comment]
In internal practical terms, the reason you cannot observe arbitrary
functions is because of `defer`. If you defer an event that was triggered,
the Framework needs the ability to find it again when the next 'run
deferred events' triggers. (Which is an entirely different process, not
just a later call)
So functionally it would be quite hard to support arbitrary event handlers,
and probably sets people up for 'oh I can just use a local scoped function
to handle this' which wouldn't actually work correctly in the broader sense.
So *maybe* you could support mocks, but I'd be very careful about it.

**Comment by benhoyt** [comment]
I think this is problematic to support given the defer/MethodType/"handle" concerns expressed above, and there's other ways to patch this (for example the "capture events" recipe Pietro posted) -- so I'm going to close this.
