### ISSUE TITLE
Adding a relation with empty dataset doesn't trigger relation-changed hook in test harness

### ISSUE THREAD

**Issue by mthaddon** [canonical/operator#794]
In https://github.com/canonical/operator/pull/705 the test harness was updated to avoid issuing relation_changed events with no data delta.

However, because of the way this is being checked (https://github.com/canonical/operator/blob/main/ops/testing.py#L857), it won't trigger a relation-changed event if a new relation is created with empty data. I've confirmed that Juju will trigger a relation-changed hook in this case: https://pastebin.ubuntu.com/p/98VcGVGqQy/. This was done by creating a charm that relates to nginx-ingress-integrator but doesn't pass any relation data unless a particular config entry is set.

Let me know if you need me to publish the charm somewhere so you can confirm.

**Comment by PietroPasotti** [comment]
I see the problem, but I don't think that https://github.com/canonical/operator/pull/705 is related. Even before that change, the harness wouldn't emit changed after joined.

Also to be precise IIRC it's not relation-created that should trigger relation-changed, it's relation-joined.
With that in mind, this is indeed a bug.

**Comment by PietroPasotti** [comment]
On second thought, I remember some discussion that the separation between joined and changed in Harness is intentional and the `add_relation_unit` docstring confirms that:

"        This will trigger a `relation_joined` event. This would naturally be
        followed by a `relation_changed` event, which you can trigger with
        :meth:`.update_relation_data`. This separation is artificial in the
        sense that Juju will always fire the two, but is intended to make
        testing relations and their data bags slightly more natural.
"

So this is a design choice it seems, unrelated with the contents of the databag at the time of the relation joined event. We can discuss the merit of the design choice if you like, but at least we know what's going on :)
