### ISSUE TITLE
Support leader-settings-changed events with the harness

### ISSUE THREAD

**Issue by rwcarlsen** [canonical/operator#812]
The conspicuous absence of leader-settings-changed event emission from the harness was noted recently by @ca-scribner et al.  Notably, the harness already supports changing the leadership status of the charm being tested - it emits leader-elected events when `set_leader(True)` is called.  However, charms may want to test code paths that are triggered in production when e.g. a different unit becomes the leader - which normally triggers leader-settings-changed events for all non-leader units.  We could support this in various ways including:

* emit leader-settings changed when `harness.set_leader(False)` is called
* Allow charm devs to explicitly specify what unit's leadership status they are setting - e.g. `harness.set_leader(True/False, unit='foo/0')`.  But we'd have to deal with edge cases like what if they set multiple units to be the leader, etc.
* Provide an explicit `harness.leader_changed(i_am_new_leader=True/False)` sort of method to trigger the appropriate leader-related events on the charm - leader-settings-changed if not the new leader, and leader-elected otherwise.

**Comment by jameinel** [comment]
So I'm not sure why you need to `harness.set_leader(unit='foo/2'). IIRC juju doesn't really expose to the units who the current leader is, just whether or not *this* unit is the leader. (Asking who the current leader is will always be racy, because it could be changing while you're looking. If *you* are the leader you have a different set of responsibilities, but you shouldn't change your behavior if unit/2 or unit/1 is the leader.)
It would be fine to fire `leader-settings-changed` when you call set_leader(False), but I'd rather we not expose in testing.Harness something that Juju doesn't really expose.

**Comment by rwcarlsen** [comment]
@jameinel - right.  The idea is basically to imitate leader-settings-changed events at times when juju would emit them and not allow charms to see who the leader is.  Just to let them know (indirectly) if it changed and is them or not (i.e. leader-settings-changed means the leader maybe changed, but it isn't you).

**Comment by jameinel** [comment]
Sure. Just that you were looking to update the signature of set_leader, but
I wasn't sure that we really want/need to do that. We already always
trigger on set_leader(True) because of the initialization race issue, we
would be consistent to always do it on set_leader(False).

I would ask that you confirm with real charms the behavior first (you can
ssh into a running machine and use `juju_stop_unit` to force a unit agent
to stop so another unit can take over leadership.)

**Comment by benhoyt** [comment]
Not going to implement this for now -- agreed with John's take above.
