### ISSUE TITLE
Better Error Handling if the pebble socket goes missing

### ISSUE THREAD

**Issue by jameinel** [canonical/operator#844]
On a Microk8s cloud there were some issues causing containers to get restarted.  Because containers were getting rescheduled, it ended up that during the time that a charm hook was firing, it ultimately failed to stay connected to pebble. The error message that you end up getting is "NoSuchFile" which is hard to interpret as "pebble went away".
The specific traceback was:
```
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/venv/ops/pebble.py", line 1331, in _request_raw
    response = self.opener.open(request, timeout=self.timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/venv/ops/pebble.py", line 84, in http_open
    return self.do_open(_UnixSocketConnection, req, socket_path=self.socket_path)
  File "/usr/lib/python3.8/urllib/request.py", line 1357, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 2] No such file or directory>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./src/charm.py", line 777, in <module>
    main(PostgresqlOperatorCharm, use_juju_for_storage=True)
  File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/venv/ops/main.py", line 429, in main
    framework.reemit()
  File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/venv/ops/framework.py", line 794, in reemit
    self._reemit()
  File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/venv/ops/framework.py", line 857, in _reemit
    custom_handler(event)
  File "./src/charm.py", line 381, in _on_postgresql_pebble_ready
    current_layer = container.get_plan()
  File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/venv/ops/model.py", line 1367, in get_plan
    return self._pebble.get_plan()
  File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/venv/ops/pebble.py", line 1615, in get_plan
    resp = self._request('GET', '/v1/plan', {'format': 'yaml'})
  File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/venv/ops/pebble.py", line 1297, in _request
    response = self._request_raw(method, path, query, headers, data)
  File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/venv/ops/pebble.py", line 1344, in _request_raw
    raise ConnectionError(e.reason)
ops.pebble.ConnectionError: [Errno 2] No such file or directory
```

There is a 'pebble.ConnectionError' in there, but the feedback from others is that it really wasn't clear why this was failing.

It would be nice if we could more clearly articulate this as something like "could not connect to pebble, socket not found at /...". Or even better if we could tell that we *did* have a connection earlier in the process, and could report that we *lost* the connection to pebble.

**Comment by taurus-forever** [comment]
Hi, just for the reference, Data Platform team is suffering from this error on GitHub runners: [example 1](https://github.com/canonical/mysql-k8s-operator/actions/runs/4538213806/jobs/7996943655), [example 2](https://github.com/canonical/mysql-k8s-operator/actions/runs/4527667218/jobs/7973768412), ...

Our [investigation](https://warthogs.atlassian.net/browse/DPE-1576) lead us to OOM inside the workload container which cause restart:
```
microk8s kubectl logs another-mysql-1 -c mysql -n test-replication-19v6 --previous
...
2023-03-29T07:30:14.746Z [pebble] Exiting on terminated signal.  
...
```

=> `ops.pebble.ConnectionError: [Errno 2] No such file or directory` while pod/pebble is not reachable through the socket. Just in case if someone is troubleshooting it as well:

```
> microk8s kubectl describe pod another-mysql-1 -n test-replication-19v6
...
Containers:
  mysql:
...
    Last State:     Terminated
      Reason:       Error
      Exit Code:    137  <<< OOM exit code
      ...
    Restart Count:  1   <<< The fact of restart
...
    Environment:
      PEBBLE_SOCKET: /charm/container/pebble.socket   <<< "No such file or directory"
```

To speedup investigations in the future, it would be great to report is as:
`Error: '/charm/container/pebble.socket' (No such file or directory) (container <name> restarted? Check pod restart count and the last exit code)`

**Comment by benhoyt** [comment]
It's a reasonable request to improve this error message. We need to figure out where to put the try/except around opening the socket and how to test for that specific [Errno 2] No such file or directory error.

**Comment by beliaev-maksim** [comment]
@benhoyt if the memory serves me well, the issue was indeed that the socket was closed (so, probably pebble is not started)

the closes test would be to close the socket, but not sure how feasible that will be (and is there a chance that pebble is UP, but the socket is not opened? if answer is positive, then better to check for socket directly)

**Comment by tonyandrewmeyer** [comment]
> Or even better if we could tell that we _did_ have a connection earlier in the process, and could report that we _lost_ the connection to pebble.

We could certainly do this - for example, the `pebble.Client` could keep track of the last `urllib.error.URLError`, clearing it on success, and then adjusting the message depending on whether it was None or the same errno.

However, I'm not sure that there's enough value to do that (as compared to just always providing the same message). In most cases, wouldn't the Charmer know whether previous calls succeeded just through where in the charm code the exception happened? ie. if Pebble was responding previously in the same hook then the charm code that used Pebble would have worked, and if not then it would have failed there rather than at the later call.

(I assume this was about losing the connection during a hook, since keeping a "used to have Pebble" state across hooks would be counter to the general state-less design).

> Error: No such file or directory: '/charm/container/pebble.socket' (container <name> restarted? Check pod restart count and the last exit code)

To provide the container name, we'd need to catch this in the `Container` code rather than in the `pebble.Client` code. I don't think that's worthwhile, just to get the container name in the exception message itself. It's simple enough to get that if you're handling the exception, e.g.:

```python
try:
    self.container.restart(service)
except ops.pebble.ConnectionError as e:
    logger.error(f"Couldn't restart '%s' on %s: %s", service, self.container, e)
```

**Comment by tonyandrewmeyer** [comment]
@benhoyt what do you think is needed in terms of tests here? We already have a unit test that checks that `ConnectionError` is raised if the socket is missing. I've added a similar "real Pebble" test in #1049.

In general, I don't like testing the text of exception messages - I don't feel that's part of the API contract. In this case, that's all that's changing - we raised a `ConnectionError` before, and we do now, but instead of "[Errno 2] No such file or directory" as the message, we have "Could not connect to Pebble: socket not found at '{self.socket_path}' (container restarted?)".

Even though the point of the ticket is to change that message, it doesn't seem like testing for it is the right thing to do.

I could explore adding tests for other ways that Pebble could become unavailable, but that seems tangential to the ticket, and if the result is that the socket file is missing, then it'll have the same outcome anyway.

**Comment by benhoyt** [comment]
@tonyandrewmeyer I agree with you that testing the error message is not usually what we want to do. However, in the case of us specifically replacing the error message with something more specific, it might be worth a test? I'd probably just test the "main part" of it in cases like this, maybe `"Could not connect to Pebble" in str(exc)` or similar. But I'd be happy to not include an automated test at all, and just verify it once manually -- as you say, the message is not part of the contract.
