### ISSUE TITLE
CharmBase stutters

### ISSUE THREAD

**Issue by timClicks** [canonical/operator#85]
Strongly recommend renaming `charm.CharmBase` to `charm.Base`. Otherwise users will need to put up with nonsense like this:

```python
from ops import charm

class Charm(charm.CharmBase):
    ...
```

Bear in mind that this is in a file called `charm.py` that's probably in a code repository titled `<project>-charm`.

**Comment by johnsca** [comment]
I'm not sure it's feasible to use `Base` as a class name, since it would then suffer from the same issue that you raised in #86.  Some factors that could mitigate the repetition:

* You don't have to name your class `Charm` now, so it might become common to name it after the charm itself, such as `Gitlab` or maybe `GitlabCharm`.
* That also applies to the file name, but I'm not sure we want to encourage changing that.
* You could import `CharmBase` rather than the module, making it `class GitlabCharm(CharmBase):` which seems reasonable to me, even if `Charm` is in there twice.

Another thing we might consider is importing what we consider the "public API" classes for the framework like `CharmBase` up to the top-level `__init__.py` so that it could just be `from ops import CharmBase` but I'm not sure if we want to do that.

**Comment by niemeyer** [comment]
Unlike Go, Python developers frequently import names into the current namespace instead of referring to objects via its module name. So we need to respect that.
