### ISSUE TITLE
Potential insecure deserialization

### ISSUE THREAD

**Issue by juli1** [canonical/operator#852]
It seems that the file [`operator/ops/storage.py`](https://github.com/canonical/operator/blob/main//ops/storage.py#L128) is potentially doing a unsafe deserialization. I found this issue while testing our new static analyzer. See the rule related to this issue [here](https://app.codiga.io/hub/ruleset/python-security/deserialize-untrusted-data). 

I am also attaching a full report of the scan. If you want to prevent this type of issue, you can use Codiga to scan your PR or give feedback of your code within your IDE.

[operator-rosie-results.csv](https://github.com/canonical/operator/files/9976495/operator-rosie-results.csv)

**Comment by benhoyt** [comment]
I don't think this is an issue for us. The data here is coming from an SQLite3 database file that's local to the unit or container that the charm code is running on. If something can mess with files on the charm unit/container, it can run arbitrary commands anyway. In other words, we trust it, so using pickle isn't an issue. @jameinel Am I assessing this correctly?

@juli1 It seems like this is more of an advertisement for Codiga than a good-faith attempt to use and improve our codebase. Codiga may be a good tool, but semi-automated issues like this often just cause busy-work for projects.

**Comment by jameinel** [comment]
I believe there are 3 pieces to think about:
a) We are reading from *our* database, where we wrote the data, thus as Ben mentions, it isn't a vector for injection
b) I believe we *are* allowing "arbitrary" snapshots from Charm code to be written here, however that was arbitrary charm code that we were already executing, it could have done whatever it wanted to, rather than rely on injecting it into the pickle.
c) I believe there is a layer that ensures you can Marshal the snapshot before we pickle/unpickle it. That enforces that there are only simple types (and thus not having executable code in the pickle). As I understand it, Marshal doesn't have a format or versioning, so isn't stable for long term save and restore, which is why we use pickle (in case the version of python gets upgraded, etc)

**Comment by juli1** [comment]
Also, to clarify: I am currently testing/evaluating the new static analyzer I am developing on public source code. I am finding some issues (and sometimes some false positives). When I find something that seems like a potential attack vector, I try to warn the developers.

My goal was not to sound spammy, just to raise a potential issue. Apologies if it sounded like this. Thanks for closing if this sounded list promotion/advertisement.

**Comment by benhoyt** [comment]
Thanks @jameinel -- I hadn't seen the pre-save marshal check before, so that's good to know (and I see there's a test for that in `test/test_framework.py`).

Fair enough, @juli1. You may want to word your issue description a bit differently.
