### ISSUE TITLE
Means to test charm upgrade

### ISSUE THREAD

**Issue by sed-i** [canonical/operator#879]
`upgrade-charm` is different from regular charm startup:
1. Not the same events fire
2. `use_juju_for_storage=True/False` may have unexpected results for upgrade

It would be handy if it was possible to cover some aspects of upgrading using unit tests.

Related:
- https://github.com/canonical/operator/issues/736
- https://github.com/canonical/operator/issues/696

**Comment by benhoyt** [comment]
I'm trying to understand this better: why is it not enough to exercise the `upgrade-charm` hook using `self.harness.charm.on.upgrade_charm.emit()` in the test, and assert that it did the right thing? Is it because we care about the *sequence* of events, rather than just the one? Is that appropriate for a unit test?

I've scheduled a video chat with you tomorrow to get a bit more context and understanding here.

**Comment by benhoyt** [comment]
@sed-i I can't for the life of me remember whether our video chat about this happened, but either way, I don't have any notes. :-) Do you remember? And if not, is manually triggering the event per my comment above enough?

**Comment by sed-i** [comment]
I think we did. Afaict,
- Yes the sequence is important, but the sequence won't matter if we don't have charm reinit.
- On upgrade, non persistent storage needs to be wiped by harness.
- On upgrade, realtion data is already in place and the charm needs to be able to start up without relation events.

That being said, perhaps ops-scenario is a better avenue.

**Comment by benhoyt** [comment]
Yeah, let's punt on this for now and spend our energy pursuing ops-scenario and firming up our "testing story" (we have both of those as items on the 24.04 roadmap).
