### ISSUE TITLE
`ops` incorrectly concludes `not a kubernetes charm` for k8s charms

### ISSUE THREAD

**Issue by sed-i** [canonical/operator#880]
When `use_juju_for_storage is None`, ops incorrectly concludes
```
unit-prometheus-0: 17:20:43.568 DEBUG unit.prometheus/0.juju-log Using local storage: not a kubernetes charm
unit-traefik-0: 17:23:27.195 DEBUG unit.traefik/0.juju-log Using local storage: not a kubernetes charm
```

https://github.com/canonical/operator/blob/edc2dda73146c72ddc9a002964f0cbb0cee5721a/ops/main.py#L399-L400

When I explicitly set `use_juju_for_storage=True`, everything is ok.

Omitting `use_juju_for_storage` should produce the same result as an explicit `=True`.

https://github.com/canonical/operator/blob/edc2dda73146c72ddc9a002964f0cbb0cee5721a/ops/main.py#L367-L370

**Comment by benhoyt** [comment]
Ah yeah, it looks like we still use an old method to check if a charm is a K8s charm: `if 'kubernetes' not in meta.series: ...` (but we don't use `series` anymore, I believe). I've [asked](https://chat.charmhub.io/charmhub/pl/k4ifkb3oufd57xhyisdtc85gih) on Mattermost what the right way of determining that is these days, and hopefully can update `ops` to match.

**Comment by benhoyt** [comment]
Update on this after discussing with Gustavo, John, and Jon:

* This debug log is incorrect: it should say "not a Kubernetes *podspec* charm" rather than just "not a kubernetes charm".
* We want to deprecate `use_juju_for_storage=True` as it's generally not what we should be using and really only intended for podspec charms.

I've made both these changes in https://github.com/canonical/operator/pull/882, so closing this.
