### ISSUE TITLE
Operator framework locking .unit-state.db breaking charmhelpers kv() functionality

### ISSUE THREAD

**Issue by dparv** [canonical/operator#909]
Error appeared during series upgrade from focal to jammy on ceph-mon charm:

```
2023-02-04 11:17:54 ERROR unit.ceph-mon/0.juju-log server.go:327 Uncaught exception while in charm code:
Traceback (most recent call last):
  File "./src/charm.py", line 282, in <module>
    main(CephMonCharm)
  File "/var/lib/juju/agents/unit-ceph-mon-0/charm/venv/ops/main.py", line 435, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-ceph-mon-0/charm/venv/ops/main.py", line 144, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-ceph-mon-0/charm/venv/ops/framework.py", line 355, in emit
    framework._emit(event) # noqa
  File "/var/lib/juju/agents/unit-ceph-mon-0/charm/venv/ops/framework.py", line 824, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-ceph-mon-0/charm/venv/ops/framework.py", line 899, in _reemit
    custom_handler(event)
  File "./src/charm.py", line 85, in on_pre_series_upgrade
    hooks.pre_series_upgrade()
  File "/var/lib/juju/agents/unit-ceph-mon-0/charm/src/ceph_hooks.py", line 1218, in pre_series_upgrade
    set_unit_paused()
  File "/var/lib/juju/agents/unit-ceph-mon-0/charm/venv/charmhelpers/contrib/openstack/utils.py", line 1560, in set_unit_paused
    with unitdata.HookData()() as t:
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/var/lib/juju/agents/unit-ceph-mon-0/charm/venv/charmhelpers/core/unitdata.py", line 473, in __call__
    with self.kv.hook_scope(hook_name):
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/var/lib/juju/agents/unit-ceph-mon-0/charm/venv/charmhelpers/core/unitdata.py", line 361, in hook_scope
    self.cursor.execute(
sqlite3.OperationalError: database is locked
```

This seems to be related to the juju operator framework. Adding a time.sleep(100) before the set_unit_paused() function that fails -

-rw------- 1 root root 40960 Feb 23 15:38 .unit-state.db
-rw------- 1 root root 16928 Feb 23 15:50 .unit-state.db-journal

$ sqlite3
SQLite version 3.31.1 2020-01-27 19:55:54
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
sqlite> .open .unit-state.db
sqlite> create table if not exists hooks ( version integer primary key autoincrement, hook text, date text ) ;
sqlite> ^Ceate table if not exists hooks ( version integer primary key autoincrement, hook text, date text ) ;
sqlite> drop table hooks;
Error: database is locked

lsof | grep .unit-state.db
charm.py 3965098 root 3uw REG 253,1 40960 17709992 /var/lib/juju/agents/unit-ceph-mon-0/charm/.unit-state.db
charm.py 3965098 root 4u REG 253,1 16928 17697644 /var/lib/juju/agents/unit-ceph-mon-0/charm/.unit-state.db-journal

seems that juju is locking the db on any hook/event execution preventing the charmhelpers library to amend the state db

this is happening on juju 2.9.38

Seems this is causing it: https://github.com/canonical/operator/blob/807ebc37be1636058e59cee65211f13f78106a44/ops/storage.py#L73

First found by: https://bugs.launchpad.net/juju/+bug/2005137

**Comment by jameinel** [comment]
I'm pretty sure you're ending up with 2 libraries trying to open the same
SQL file:
```
File "/var/lib/juju/agents/unit-ceph-mon-0/charm/src/ceph_hooks.py", line
1218, in pre_series_upgrade
set_unit_paused()
File
"/var/lib/juju/agents/unit-ceph-mon-0/charm/venv/charmhelpers/contrib/openstack/utils.py",
line 1560, in set_unit_paused
with unitdata.HookData()() as t:
File "/usr/lib/python3.8/contextlib.py", line 113, in *enter*
return next(self.gen)
File
"/var/lib/juju/agents/unit-ceph-mon-0/charm/venv/charmhelpers/core/unitdata.py",
line 473, in *call*
with self.kv.hook_scope(hook_name):
File "/usr/lib/python3.8/contextlib.py", line 113, in *enter*
return next(self.gen)
File
"/var/lib/juju/agents/unit-ceph-mon-0/charm/venv/charmhelpers/core/unitdata.py",
line 361, in hook_scope
self.cursor.execute(
sqlite3.OperationalError: database is locked
```
Note that this is clearly "charmhelpers" trying to read a SQLite file. I
don't know whether the *ops* sqlite file ends up as the same
'.unit-state.db', though it would certainly be bad form for both of them to
use the same file.
However, neither *Juju* nor *ops* should be depending on
'charmhelpers/core/*'. Juju itself shouldn't be locking the sqlite file,
and ops is likely to be locking an sqlite file that *it* is using to manage
its events, etc.
Ops does use `$CHARMDIR/.unit-state.db`

https://github.com/canonical/operator/blob/807ebc37be1636058e59cee65211f13f78106a44/ops/main.py#L419

**Comment by benhoyt** [comment]
Yeah, it's very weird that charmhelpers is using the same SQLite db as ops here. Or rather, that ops is using the same SQLite db as charmhelpers ... because charmhelpers has been using that db path [since at least 2015](https://github.com/juju/charm-helpers/commit/515f34b27ce24dd492fa91b1392e70229894f769), and ops hasn't been around that long. :-) In 2020 ops [started taking an exclusive lock](https://github.com/canonical/operator/commit/a15f3d3d8e3e9e95b9d8e9548370560d764c1a6f) on the db file.

It seems like we should be using ops storage for this? (But again, I guess charmhelpers predates that.)

I'm not sure why this just started happening. Has your charm changed, or have you never done a series upgrade in the past? Assuming we can understand why this started happening, there are a couple of options:

1) Update the charm to use ops storage for whatever this use case is instead.
2) Charmhelpers [allows](https://github.com/juju/charm-helpers/commit/515f34b27ce24dd492fa91b1392e70229894f769) you to provide a path to its Storage class, or set the `UNIT_STATE_DB` environment variable to override the default path. Maybe that's a simple workaround?

**Comment by dparv** [comment]
Changing the db_path should be an easy change for charmhelpers, however the question arises: what will happen to charms that are deployed and rely on data stored in the .unit-state.db, looking for keys/values that do not exist might be either destructive or cause production workload outages for some charms on charm upgrade.

Using the ops storage sounds better, but still there needs to be some logic preventing the above.

**Comment by benhoyt** [comment]
I guess the thing to do would be to migrate to a different .db file in a charm upgrade hook. But yeah, it's a bit messy, isn't it.

@jameinel Do you know why ops chose to use the same filename (`.unit-state.db`) for this that charmhelpers had been using for a long time? Was it just an oversight, or should it be the same file?

**Comment by jameinel** [comment]
I don't think I was part of the specific decision as to what file to use.
There are a few options

a) use_juju_for_storage=True would cause the charm to write the contents to
Juju (state-set/get) rather than to .unit-state.db, though we now give a
deprecation warning if they do that.
b) I think a goal would be to move away from charmhelpers kv store to ops
objects, but I totally understand that you need to be able to read the old
one to write the new one, and it gets very awkward if they are the same one
opened 2 separate times. We *could* provide an ops library to help do the
conversion. (or plausibly something in charmhelpers that would convert it
to an ops structure)

John
=:->

**Comment by benhoyt** [comment]
For the record, @jameinel said about why we have the exclusive locking:

> IIRC we wanted to give people consistency, so that you didn't end up with surprising race conditions where things seemed to work, but you actually had a race condition that would surprise you.
>
> We didn't want to have a case where you initialized a framework, and then it trips up and you have to write your charm code with retries in it because you might have a conflict writing to the database.

**Comment by benhoyt** [comment]
@dparv or @lmlg, just wondering what you ended up with a workaround for this issue in your charms?

**Comment by lmlg** [comment]
> @dparv or @lmlg, just wondering what you ended up with a workaround for this issue in your charms?

We migrated the DB in the charm itself: https://opendev.org/openstack/charm-ceph-mon/commit/616c4e3367f2816774d8629396340a5b3b48f680

**Comment by benhoyt** [comment]
Thanks @lmlg. Seeing this hasn't come up since, I'm going to close this issue. Most people aren't affected by this as they don't use charmhelpers with ops, but if someone does, they can always use the same approach you've used.
