### ISSUE TITLE
No interface to `juju-reboot` hook tool in ops

### ISSUE THREAD

**Issue by NucciTheBoss** [canonical/operator#929]
Hello there! I am currently working through a predicament in the [SLURM charms](https://charmhub.io/?q=slurm) where the machines need to be rebooted after package installation to apply security updates. Originally, the SLURM charms were deployed manually so the human operator would issue a machine reboot command based on the substrate being used (e.g. `openstack server reboot <machine_id>`). We are now working to make deploying SLURM an automatic process, however, we still have the issue where the machines need to be rebooted to apply updates.

My idea was to use the `juju-reboot` hook tool located in `/var/lib/juju/tools/machine-<#>/`, however, it does not seem that ops has a direct method for invoking `juju-reboot`. It would be nice if ops had a defined method for scheduling machine reboots at the end of hook execution:

```python3
# Assume charm is fully defined

def _on_install(self, _: InstallEvent) -> None:
    # Install some packages, update base image, etc.
    ...

    if pathlib.Path("/var/run/reboot-required").exists():
        logger.info("Scheduling machine for reboot...")
        self.unit.reboot()
```

Currently I can circumvent my reboot issue by directly invoking the `juju-reboot` hook tool, but I thought that this might be a nice edition to ops. Let me know what your thoughts are!

**Comment by benhoyt** [comment]
It's a reasonable idea -- thanks. We're thinking of doing this as a top-level function, say `ops.reboot()`, rather than an `Unit.reboot()` method, because it only applies to "our" unit (and not other units), so it seems a bit awkward to keep adding stuff to `Unit` only to have to test at runtime that it's our unit and fail if not.

It could be defined in `ops/model.py`, or even a new `ops/functions.py` or similar.

Thoughts?

**Comment by NucciTheBoss** [comment]
You bring up a good point. I was in pylib-juju mode where you need to "pull down" the unit to run a command on it :sweat_smile: 

I think something like `ops/functions.py` would be a good edition. I don't think `ops/model.py` would be a good place for reboot functionality since `ops/model.py` is more focused on representing Juju-specific data structs such as models, applications, and units. Only thing about `ops/functions.py` is that I am worried the name _functions_ might be too ambiguous. Are they functions used throughout ops to mask complex operations in the framework or are they meant for use within charms?

Perhaps `ops/tools.py` or `ops/hooktools.py` would be good place to define a reboot method? Let me know your thoughts.

**Comment by benhoyt** [comment]
Thinking about this further, `ops.reboot()` might make sense in some respects, but isn't a good idea -- we need the "backend" object to be attached to something, like the `Unit` instance. We are rebooting the unit, so that does make sense -- it would just need to do an `is_our_unit` check like several of the other methods.

**Comment by benhoyt** [comment]
FWIW, here's a use of `juju-reboot` in the wild: https://github.com/canonical/github-runner-operator/blob/2462acae4002c1c68dad73362ebbc5f98a17587b/src/charm.py#L374

We could potentially submit a PR to that charm after this work is in a released ops version to update it to use `Unit.reboot`.
