### ISSUE TITLE
Automatically clear workload version on stop

### ISSUE THREAD

**Issue by sed-i** [canonical/operator#930]
Assuming
1. charm code is idempotent
2. an unsuccessful upgrade shouldn't display the old workload version

it seems that ops should automatically clear the workload version on stop.

Currently, charm authors need to remember to clear the workload version on stop (and have a unit test confirming it).

**Comment by jameinel** [comment]
I don't think that `stop` is correlated well enough with a workload version change to say that all applications should have this behavior. (and if they should, then we should do it at the Juju level, rather than a default ops hook handler.)

(eg, you could very easily be stopped, and not be upgrading anything).

I might argue slightly more that if you are doing an *upgrade*, but the charm upgrade is independent of the workload (it might be config that tells the charm what actual workload to run for Machine charms, and juju should already be reporting what container image we are running for things that upgrade the container itself.)

**Comment by benhoyt** [comment]
Thanks @jameinel. I agree with that assessment. And even if we did want to do something automatic here (though I don't think it would be on `stop`), it should be done at the Juju level.

@sed-i In your specific case, if the upgrade flow involves stop, I think it's fine that the charm needs to explicitly clear/update the workload version.

**Comment by sed-i** [comment]
Agreed that it should probably be a juju thing if any.

Afaict, an upgrade sequence begins with a stop. At least in k8s.

Fwiw, emptying out the workload version in `juju status` conveys a lot, and very quickly, which is useful when e.g. across an upgrade, workload exited too quickly.

**Comment by sed-i** [comment]
Or perhaps some kind of a pebble check that would be attached to service lifecycle.
