### ISSUE TITLE
simultaneously update app and unit databags in harness

### ISSUE THREAD

**Issue by PietroPasotti** [canonical/operator#934]
Suppose we have a relation interface that requires both app and unit databags to contain some data.
Right now:
```python
harness.update_relation_data(id, 'remote', {foo:bar})  # emits relation-changed, which puts the charm in an inconsistent state, as there is no unit data yet
harness.update_relation_data(id, 'remote/0', {foo:bar})  # emits another relation-changed, which goes well
```

Currently the solution is to use the `Harness.hooks_disabled` context:

```python
with harness.hooks_disabled():
    harness.update_relation_data(id, 'remote', {foo:bar})  # does not emit anything

harness.update_relation_data(id, 'remote/0', {foo:bar})  # emits another relation-changed, which goes well
```

However that is somewhat annoying. Can we make it better?
How about:
```python
def Harness.update_relation_data(self, app_name='remote', app_data={foo:bar}, units_data={0: {baz:qux}, 1: {...}}): ...
```
where we get to update all at once?

**Comment by jameinel** [comment]
You could do that, and we had a few designs that had more attributes per
method. (add_relation_unit used to optionally take the relation data for
that unit at the same time.)
The reason we moved away from it, was because it ends up that there is
always a reason to add a little bit more data to a given request (set up
the config and the relation data simultaneously, etc). And it seemed better
to provide ways to do multiple things 'simultaneously' rather than trying
to put them all into the same function.
It is true that for relation data the charm won't partially expose the
content (the relation data isn't actually shared until the hook finishes,
which means it can set the app level and the unit level data
simultaneously). I'm not sure if it is great for *consuming* charms to
assume that, however. (It seems like it would lead to more brittle charms
in case something changes in the upstream code in the future.)

John
=:->

**Comment by PietroPasotti** [comment]
Yeah, I didn't consider that 'what this charm considers as a valid state' is very charm specific, for some it might be 'there's data here and there' and for some other it might be 'there's data here and my config is foo'.
So there's no generalizing there.
Maybe because I conceive of relation data as a single data structure with multiple entries (one for each entity partaking in the relation), it makes more sense to me to have a unified update. Updating a unit databag and a relation databag (for the same relation) feel like should be kept tied together a lot more than updating a unit databag and charm config.

But yeah, `hooks_disabled` is still the generic way to go.

**Comment by benhoyt** [comment]
I think we should stick with the `hooks_disabled` status quo for now, and lean in more on scenario-based testing as usage of that picks up steam and is validated. It does solve this problem in a cleaner way!

**Comment by PietroPasotti** [comment]
can't disagree with that
