### ISSUE TITLE
Inconsistency in `relation-list` output with subordinates

### ISSUE THREAD

**Issue by sed-i** [canonical/operator#945]
@simskij and myself are considering interrelating two subordinates, to make sure both of them scale together with the principal.

```yaml
---
name: hw-test

applications:
  ubuntu:
    charm: ubuntu
    scale: 2
    channel: edge
  zk:
    charm: zookeeper
    scale: 2
    channel: edge
  agent:
    charm: grafana-agent
    scale: 0
    channel: edge
  hw-health:
    charm: hw-health
    scale: 0
    channel: edge

relations:
  - [agent:juju-info, ubuntu:juju-info]
  - [agent:cos-agent, zk:cos-agent]
  - [hw-health:general-info, zk:juju-info]
  - [hw-health:general-info, ubuntu:juju-info]
  - [agent:juju-info, hw-health:juju-info]
```

Juju accepted the topology, but `relation-list` gives unexpected results that also seem to contradict `juju show-unit`.
This seems like a juju bug, but posting here for the mermaid rendering, code blocks, and links to related issues.

## `juju status`
```
Model    Controller  Cloud/Region         Version  SLA          Timestamp
welcome  lxd         localhost/localhost  3.2.0    unsupported  23:28:39-04:00

App        Version  Status       Scale  Charm          Channel  Rev  Exposed  Message
agent               error            4  grafana-agent  edge      10  no       hook failed: "config-changed"
hw-health           maintenance      4  hw-health      edge      31  no       Installing freeipmi,libipc-run-perl
ubuntu     22.04    active           2  ubuntu         edge      24  no       
zk                  active           2  zookeeper      3/edge   101  no       

Unit            Workload     Agent  Machine  Public address  Ports  Message
ubuntu/0*       active       idle   0        10.105.175.67          
  agent/0*      error        idle            10.105.175.67          hook failed: "config-changed"
  hw-health/5   maintenance  idle            10.105.175.67          Installing freeipmi,libipc-run-perl
ubuntu/1        active       idle   1        10.105.175.157         
  agent/1       error        idle            10.105.175.157         hook failed: "config-changed"
  hw-health/4   maintenance  idle            10.105.175.157         Installing freeipmi,libipc-run-perl
zk/0            active       idle   2        10.105.175.207         
  agent/3       blocked      idle            10.105.175.207         Missing relation: [send-remote-write|grafana-cloud-config]
  hw-health/3*  maintenance  idle            10.105.175.207         Installing freeipmi,libipc-run-perl
zk/1*           active       idle   3        10.105.175.57          
  agent/2       blocked      idle            10.105.175.57          Missing relation: [send-remote-write|grafana-cloud-config]
  hw-health/2   maintenance  idle            10.105.175.57          Installing freeipmi,libipc-run-perl

Machine  State    Address         Inst id        Base          AZ  Message
0        started  10.105.175.67   juju-436131-0  ubuntu@22.04      Running
1        started  10.105.175.157  juju-436131-1  ubuntu@22.04      Running
2        started  10.105.175.207  juju-436131-2  ubuntu@22.04      Running
3        started  10.105.175.57   juju-436131-3  ubuntu@22.04      Running

Relation provider    Requirer                Interface              Type         Message
agent:peers          agent:peers             grafana_agent_replica  peer         
hw-health:juju-info  agent:juju-info         juju-info              subordinate  
ubuntu:juju-info     agent:juju-info         juju-info              subordinate  
ubuntu:juju-info     hw-health:general-info  juju-info              subordinate  
zk:cluster           zk:cluster              cluster                peer         
zk:cos-agent         agent:cos-agent         cos_agent              subordinate  
zk:juju-info         hw-health:general-info  juju-info              subordinate  
zk:restart           zk:restart              rolling_op             peer
```

## Relation view

```mermaid
graph LR
hw-health ---|"general-info (8) juju-info"| ubuntu
hw-health ---|"general-info (5) juju-info"| zookeeper
ubuntu ---|"juju-info (3) juju-info"| agent
zookeeper ---|"cos-agent (4) cos-agent"| agent
hw-health ---|"juju-info (7) juju-info"| agent
```

## Machine view

```mermaid
graph TD


subgraph "Machine 0"

subgraph "Subordinates 0"
agent/0 ---|juju-info:7| hw-health/5
end

ubuntu/0 ---|juju-info:3| agent/0
ubuntu/0 ---|general-info:8| hw-health/5

end

subgraph "Machine 1"

subgraph "Subordinates 1"
agent/1 ---|juju-info:7| hw-health/4
end

ubuntu/1 ---|juju-info:3| agent/1
ubuntu/1 ---|general-info:8| hw-health/4
end

subgraph "Machine 2"

subgraph "Subordinates 2"
agent/3 ---|juju-info:7| hw-health/3
end

zk/0 ---|cos-agent:4| agent/3
zk/0 ---|general-info:5| hw-health/3
end

subgraph "Machine 3"

subgraph "Subordinates 3"
agent/2 ---|juju-info:7| hw-health/2
end

zk/1 ---|cos-agent:4| agent/2
zk/1 ---|general-info:5| hw-health/2
end
```

### Asymmetry between a principal and a subordinate: the principal "does not see" the subordinate
`hw-health/2`  and `zk/1`  are related over `general-info (5) juju-info` (respectively).
I expected `relation-list`  to show `zk/1` for `hw-health/2` and `hw-health/2` for `zk/1`, but that is not the case -- for `zk/1` I get an empty return:
```
$ juju exec --unit hw-health/2 -- relation-list -r juju-info:5
zk/1
$ juju exec --unit hw-health/2 -- relation-list -r general-info:5
zk/1
$ juju exec --unit zk/1 -- relation-list -r juju-info:5
$ juju exec --unit zk/1 -- relation-list -r general-info:5
```

### Asymmetry between two subordinates
`hw-health` and `agent` are related over `juju-info:7`.
I expexted `relation-list` to show `agent/2` for `hw-health/2` and `hw-health/2` for `agent/2`, but that is not the case -- for `agent/0` and `agent/1` I get an empty return:
```
$ juju exec --unit agent/0 -- relation-list -r juju-info:7
$ juju exec --unit agent/1 -- relation-list -r juju-info:7
$ juju exec --unit agent/2 -- relation-list -r juju-info:7
hw-health/2
$ juju exec --unit agent/3 -- relation-list -r juju-info:7
hw-health/3
```

and for `hw-health` it's always empty:
```
$ juju exec --unit hw-health/2 -- relation-list -r juju-info:7
$ juju exec --unit hw-health/3 -- relation-list -r juju-info:7
$ juju exec --unit hw-health/4 -- relation-list -r juju-info:7
$ juju exec --unit hw-health/5 -- relation-list -r juju-info:7
```

BTW: In `juju show-unit hw-health/4`, all `agent` units are indeed listed under `- relation-id: 7`. Same for `juju show-unit agent/1`.

### Principal and subordinate invisible to each other
`agent` and `ubuntu` are related over `juju-info:3`.
Given the above, I expected `list-relation` to at least show `agent/0` for `ubuntu/0`, but in this case they were all invisible to each other:
```
$ juju exec --unit agent/0 -- relation-list -r juju-info:3
$ juju exec --unit agent/1 -- relation-list -r juju-info:3
$ juju exec --unit ubuntu/0 -- relation-list -r juju-info:3
$ juju exec --unit ubuntu/1 -- relation-list -r juju-info:3
```

### Subordinate relation between subordinate charms
Is a subordinate relation (`juju-info`) between two subordinates valid? Seems like only regular relations should be allowed between subordinates.

Related to:
- https://github.com/canonical/operator/pull/924
- https://github.com/canonical/grafana-agent-k8s-operator/issues/158#issuecomment-1487394310

**Comment by jameinel** [comment]
So the `juju-info` relation is *only* for those subordinates that are fundamentally monitoring the machine, and not the unit, which is why they can be run anywhere. As such, we *don't* run any relation-joined / relation-changed hooks on the primary application, because it is *not* a relation protocol (interface) that has any data bags associated with it.

If you have a primary and subordinate that want to know about each other, and communicate anything they should use a custom protocol and not `juju-info`. Then the primary will see the one unit of the subordinate, and the subordinate will see its associated primary unit. Note that on the *subordinate* relation, you will not see *all units* of the other application. (eg zk/0 could see agent/3 but it won't see agent/2, and agent/3 will only see zk/0 and not zk/1)

At present, Juju does not 'chain' subordinates (if you relate ubuntu to agent and then relate hw-health to agent, you won't end up with a unit of hw-health scheduled to the same container as ubuntu/0). That is something we are looking to fix, so that you don't have to relate hw-health to agent *and* ubuntu in order to get the unit to show up.

However, we know that with the extra relation workaround, you *can* get the data flows to work, because people are using them for local proxies to databases. (eg pgbouncer or mysql-proxy running locally on your primary machine, proxying a subordinates relation back to an external database).

In general, though, `juju-info` should be used sparingly. Once we have "machine subordinates" (where instead of relating to a primary application, you configure juju to say 'all machines like X should run this subordinate') I would actually think that juju-info should not be used. Though that is probably at least another year before we look to tackle that modeling exercise.

**Comment by sed-i** [comment]
Thanks @jameinel! Yes, I'm looking forward to the 'chained' subordinates fix.

In the meanwhile:

> If you have a primary and subordinate that want to know about each other, and communicate anything they should use a custom protocol and not juju-info. Then the primary will see the one unit of the subordinate, and the subordinate will see its associated primary unit.

This is surprising. In fact, we have an [itest](https://github.com/canonical/grafana-agent-k8s-operator/blob/main/tests/integration-machine/test_juju_info.py) for `juju-info` that relies on the principle being visible to the subordinate.
I was thinking that we don't have the some behavior here because there are _multiple_ juju-info relations. Which seems like a bug.

> We know that with the extra relation workaround, you can get the data flows to work, because people are using them for local proxies to databases.

Perhaps it works because they only have one `juju-info` relation?

I am particularly concerned about how asymmetric the behavior is. Seems inconsistent.

**Comment by jameinel** [comment]
juju-info as an endpoint was not supposed to be something a charm could
create, but something that juju created for every charm. (At one point I'm
pretty sure that we had logic that refused an entry in "metadata.yaml" that
had a juju- endpoint, apparently we let that lapse.

Essentially every charm *gets* a juju-info, but we don't run associated
hooks on it.

Any other charm can choose to create an endpoint, with whatever name, and
then have it implement the "juju-info" interface protocol, which won't
trigger hooks on the charm that has juju-info,but will trigger hooks in the
named endpoint. And if that relation is container scoped, then you will
only see the one unit that is co-located in your process space (eg, the
same container or VM).

Because juju is adding that interface to everything, we don't allow them to
define anything custom for that endpoint. And we *shouldn't* have let you
define your own thing named "juju-info". You *can* have an endpoint that
does exactly what you're doing with it, but the name collision is just
worlds of confusion for everyone.

John
=:->

**Comment by benhoyt** [comment]
@sed-i Without having digested all the info here, this looks more like a Juju domain issue than an `ops` issue if anything -- is that correct?

**Comment by benhoyt** [comment]
Sorry, missed your comment about why you'd posted here. Does not seem quite appropriate to post a Juju issue here, but I see why you've done it. :-) Closing this -- feel free to re-open this on Launchpad if needed. Suggestion for future if you need fancy formatting: use https://gist.github.com which supports Markdown, and link to that from the Launchpad issue.
