### ISSUE TITLE
Remove references to "you" and "your" in API docstrings

### ISSUE THREAD

**Issue by benhoyt** [canonical/operator#959]
Per Jon's comment [here](https://github.com/canonical/operator/pull/953#discussion_r1247545755), we should clean up the style in our API docstrings to avoid using "you".

**Comment by tonyandrewmeyer** [comment]
@benhoyt are we specifically avoiding *you/your* referring to the developer, or also when it's used to refer to the charm/unit/etc?

For example:

> You can use this to determine (for example) whether *you* are the departing unit.

The first "you" is clearly one we want to change, for example to:

> Use this to determine (for example) whether *you* are the departing unit.

Do we also want to remove the second "you" as well? For example to:

> Use this to determine (for example) whether the caller is the departing unit.

Or, another example:

> This might be your unit, another unit of your application, or a unit of another application that you are related to.

This doesn't match the main case referenced in #953 where we want to use imperative language. Would we change it to, for example:

> This might be the local unit, another unit in the same application, or a unit of another application via an integration.

(Secondary question from that example: when working on things like this, do we adjust to say "integration" rather than "relation"?)

**Comment by benhoyt** [comment]
I would say we do want to remove all those usages of "you", yeah, for clarity and consistency. For one, the person reading might not be the charm author. Perhaps:

> Use this to determine (for example) whether this unit is the departing one.

> This might be the current unit, another unit of this application, or a unit of an application this charm is related to.

I don't think we want to change all instances to "integration" -- at least let's leave that for another PR. I'm not actually sure "related to" is incorrect there; "integrated with" feels clumsy, but maybe it is what we've settled on. You could also ask that on the Juju Mattermost channel (maybe ping `@tmihoc`, the Juju team's docs person). Either way, let's leave for a separate PR for easier review.
