### ISSUE TITLE
Add method for "wholesale" port management

### ISSUE THREAD

**Issue by sed-i** [canonical/operator#989]
#905 added convenient API for "deltas" in port management, and it works well:

```python
    def set_ports(self):
        """Open necessary (and close no longer needed) workload ports."""
        planned_ports = {
            OpenedPort("tcp", self._ports.api),
            OpenedPort("tcp", self._ports.ha),
        }
        actual_ports = self.unit.opened_ports()

        # Ports may change across an upgrade, so need to sync
        ports_to_close = actual_ports.difference(planned_ports)
        for p in ports_to_close:
            self.unit.close_port(p.protocol, p.port)

        new_ports_to_open = planned_ports.difference(actual_ports)
        for p in new_ports_to_open:
            self.unit.open_port(p.protocol, p.port)
```

It seems like the same function would be repeated in every COS Lite charm (and others?), so I was wondering if it would make sense to add something like this "wholesale" approach to port management to ops.

**Comment by benhoyt** [comment]
@sed-i Yeah, sounds like a useful idea, especially for charms that use the "wholistic" approach. Here are a couple of API possibilities:

```python
class Unit:
    # Existing functions:
    def open_port(self, protocol: typing.Literal['tcp', 'udp', 'icmp'],
                  port: Optional[int] = None):
        ...

    def close_port(self, protocol: typing.Literal['tcp', 'udp', 'icmp'],
                   port: Optional[int] = None):
        ...

    def opened_ports(self) -> Set['OpenedPort']:
        ...

    # New option 1:
    def open_ports(self, ports: List[OpenedPort], close_others: bool = False):
        ...

    # New option 2:
    def open_ports(self, protocol: typing.Literal['tcp', 'udp', 'icmp'],
                   ports: List[int], close_others: bool = False):
        ...

    # New option 3:
    def set_ports(self, ports: List[OpenedPort]):
        ...


# Example of option 1
self.unit.open_ports([ops.OpenedPort('tcp', self._ports.api),
                      ops.OpenedPort('tcp', self._ports.ha)], close_others=True)

# Example of option 2
self.unit.open_ports('tcp', [self._ports.api, self._ports.ha], close_others=True)

# Example of option 3
self.unit.set_ports([ops.OpenedPort('tcp', self._ports.api),
                     ops.OpenedPort('tcp', self._ports.ha)])    
```

I think I prefer option 1, even though it's a bit more verbose: it allows opening multiple ports without closing the others, and the name fits the existing `open_port` method better. Option 2 is nice and succinct to use, but you couldn't use it if you want to open multiple protocols (UDP or ICMP as well). Option 3 is closest to what I think you're suggesting, and arguably it's good to have a different name for this rather than a `close_others` boolean option.

I'm not totally sold on it yet, but what do you (or others) think? CC: @PietroPasotti @jdkandersson

**Comment by sed-i** [comment]
BTW is it feasible to specify this via a pebble layer?

**Comment by benhoyt** [comment]
> is it feasible to specify this via a pebble layer?

@sed-i Not really -- this isn't a Pebble concern, but rather a Juju one, so it's not something that Pebble would/should know about.

**Comment by sed-i** [comment]
### Option 2
What I like in option 2 is that it doesn't leak `OpenedPort`.
But even if we limit the scope of `close_others` to the same protocol, the API is still not great.

### Option 3
I think option 3 complement best the existing methods.
I imagine that for most charms that's the only method needed.

**Comment by jdkandersson** [comment]
Sounds like a useful API, I also think option 3 looks good. One small proposed change:

```python
# New option 3:
def set_ports(self, ports: Iterable[OpenedPort]):
    ...
```

Note the use of `Iterable` rather than `List` to make the API support tuples, generators etc. Also, the type `OpenedPort` in this case is a bit confusing, as a user I would have to build them up and my code will say `OpenedPort` and then I'm asking for them to be opened which is confusing since the name of the class I'm creating says that the port is already open. Perhaps rename the type to `Port`?

**Comment by benhoyt** [comment]
@jdkandersson Yeah, I agree the name `OpenedPort` is a bit odd / unfortunate. I chose it originally because `ops.Port` seemed too general (what if we have other kinds of ports?). But that's probably being too worried about some unknown future possibility. `Port` seems reasonable (it's the only first-class use of ports in ops / hook tools), and we can always alias to `OpenedPort` for backwards-compatibility.

**Comment by Abuelodelanada** [comment]
From my point of view @jdkandersson suggestions are great.

**Thinking out loud**: Should `set_port` be idempotent and/or raise `ModelError` if there is an error openning/closing a port? 🤔 

From a charm author perspective I would like to know which port was the problematic and do something in that situation.

**Comment by sed-i** [comment]
> > is it feasible to specify this via a pebble layer?
> 
> @sed-i Not really -- this isn't a Pebble concern, but rather a Juju one, so it's not something that Pebble would/should know about.

You obviously know best. From first glance it seemed attractive to use pebble for this:
- We already specify per-service instructions in pebble layers, and `ports` could be another per-service list.
- The pebble daemon resides together with hook tools.
- This "expose" functionality seems to be able to work consistently for both k8s and machine charms.
- Pebble layers already support both "delta" (add layer) and "holistic" (combine-override-replace).

**Comment by benhoyt** [comment]
For the record, I discussed with @jameinel and he likes the basic idea, though he prefers the `set_ports(self, ports: List[OpenedPort])` signature. On second look, I don't like the `close_others=True` messiness now either.

I also think `set_ports(*ports)`, allowing `set_ports(Port('tcp', 1234), Port('tcp', 4321))` is a bit nicer than `set_ports(list_of_ports)` which would require the extra brackets in most cases. So I think here's what we should add:

```python
class Unit:
    def set_ports(self, *ports: Port) -> None:
        """Set the open ports for this unit, closing any others that are open."""

# rename class OpenedPort to Port, and then alias OpenedPort to it
OpenedPort = Port
```

Optionally, we could also:

1) Allow the items in the `ports` arg to be either a `Port` instance or an `int` port number, which means `Port('tcp', port_number)`. I think TCP would by far be the most common usage.
2) Make a similar change to the `open_port` and `close_port` signatures, making the default `protocol='tcp'`, allowing `open_port(port=1234)` for those functions.

I'm going to mark this as "good first item" as I think it'd be a nice way for new hire @tonyandrewmeyer to get into ops development after he starts in a couple of weeks.
